### ISSUE TITLE
Windows Container for Action Runner

### ISSUE THREAD

**Issue by ttasharski73** [actions-runner-controller/actions-runner-controller#1001]
Is a windows container image supported for the action-runner-controller system? I am able to get Linux working fine, but we want the ability to do both Linux and Windows.

**Comment by mumoshu** [comment]
@ttasharski73 Hey! Unfortunately, it isn't supported today. I don't even know- is self-hosted runner agent supposed to run on Windows?

**Comment by ttasharski73** [comment]
@mumoshu if I could do just Linux runners I would, but need some Windows runners for builds that can only be done on Windows. Github offers Windows hosted runners, but I would prefer to run self-hosted and on my AKS. I was just seeing if anyone has experience with it, if not I will try to figure it out.

**Comment by mumoshu** [comment]
@ttasharski73 Thanks for the clarification! I think what you would need to do would be:

- Build a Windows container image(is there anything like that?) that looks like a Windows version of https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Dockerfile and https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/entrypoint.sh
- Point `RunnerDeployment.Spec.Template.Spec.RunnerImage` to your custom docker image

Probably https://github.com/actions/virtual-environments/tree/main/images/win can be your source of inspiration when building your Windows container image for runners.

**Comment by ttasharski73** [comment]
@mumoshu thanks! I will give it a try! I think I can use a Windows 2019 base image that what it looks like Github is using.

**Comment by isarkis** [comment]
I was able to get windows based runner working in GKE. Had to make changes in actions-runner-controller code.  Not sure about other Kubernetes services, but GKE wouldn't admit windows based pod with 'privileged=true'.

Is there a particular reason actions-runner-controller sets 'prileged=true' even with 'dockerEnabled: false' ?  I would imagine it would be useful to allow users make their self hosted runners run in unprivileged mode.  This might be a good option for those who want to harden security around running self hosted runner, albeit at the expense of not being able to run container based workflows in K8s.

**Comment by mumoshu** [comment]
@isarkis Thanks for sharing your experience!

I imagine there would be cases that you use docker in workflows but without privileges, e.g. you use kata containers or sysbox containers to make dind work without privileged containers.

That said, I think adding `privileged: [true|false]` option to runner and runnerdeployment specs seem to be a valid approach, which enough caution to users!
Would you mind submitting a pull request based on your work?

**Comment by isarkis** [comment]
According to the readme, setting 'dockerEnabled: false' should create unprivileged container, but it doesn't appear to be doing so:

```
# true (default) = A privileged docker sidecar container is included in the runner pod.
# false = A docker sidecar container is not included in the runner pod and you can't use docker.
# If set to false, there are no privileged container and you cannot use docker.
dockerEnabled: false
```

I am thinking of just fixing that instead of adding another mutually exclusive option (i.e. 'privileged').  What do you think?

BTW.  I was able to get the actions-runner-controller working with sysbox, that should make dind workflows more secure.

**Comment by mumoshu** [comment]
@isarkis Good catch! Yeah, that should be enough for this specific issue.

> adding another mutually exclusive option (i.e. 'privileged')

I think the `privileged` option would be still handy, because it can be used to enable docker while disabling privilege, which is impossible with `dockerEnabled` alone.

In the end you'd use:

1. `privileged: false` + `dockrEnabled: true` for sysbox (i.e. `dockerEnabled: true` implies `privileged: true` but you explicitly negate privileged with `privileged: false
2. `dockerEnabled: false` for Windows containers on GKE (i.e. `dockerEnabled: false` implies `privileged: false`, if that's fine for you

> BTW. I was able to get the actions-runner-controller working with sysbox, that should make dind workflows more secure.

Good news! Thanks for sharing ☺️

**Comment by sbrinkerhoff** [comment]
How have folks managed with Windows runners?  What is working, what isn't?  Any overview of how to get it setup?

**Comment by GoranHalvarsson** [comment]
I would also like to know this. 
How to setup windows runners with actions-runner-controller? Is this possible today?

**Comment by GoranHalvarsson** [comment]
Hello @isarkis :-)
Could please share how you got windows runners working  in actions-runner-controller.

**Comment by antgrutta** [comment]
I too have been working on this problem, [Windows Runner Container](https://github.com/antgrutta/windows-runner-container).  I ended up not having to make any changes to the `actions-runner-controller` code as I was using `containerd` on my Windows nodepool.  I am going to further refine my `entrypoint.ps1` to account for the different switches beyond what my POC used (organization based runners).  @isarkis would you like to combine effort and maybe put up a PR together?

**Comment by isarkis** [comment]
@antgrutta, did you try your windows runners on GKE or some other Kubernetes cluster?

**Comment by antgrutta** [comment]
> @antgrutta, did you try your windows runners on GKE or some other Kubernetes cluster?

I am testing this in Azure using AKS, sorry should have added that detail first.

**Comment by GoranHalvarsson** [comment]
Thank you @isarkis for your fork! This is great news!!

I also run on AKS @antgrutta. So would it work to just point to a windows image in the runner deployment:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: windows-runner
spec:
  nodeSelector:
    kubernetes.io/os: windows
  repository: XXXXXX
  image:  mcr.microsoft.com/windows/servercore:ltsc2019
  dockerEnabled: false
  env: []
```
Could this work on AKS?

**Comment by antgrutta** [comment]
> Is that what you are doing using the entrypoint.ps1, @antgrutta ?

Yes, it provides a mechanism to update switches based on the incoming environment variables from the controller.

**Comment by shinji62** [comment]
@isarkis Any chance to publish the sysbox implementation that will be more than welcome. ?

**Comment by isarkis** [comment]
@shinji62, here is what I did:

- Create new GKE cluster version 1.21.5-gke.1302 using Ubuntu with containerd (ubuntu_containerd) image.  Review k8s distro [requirements](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#kubernetes-distro-requirements) and cluster setup notes as they are different for each k8s provider.  There is also k8s version [requirement](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#kubernetes-version-requirements).
   - Add 'sysbox-install: yes' kubernetes label in Metadata (this will make sure that all existing and new nodes get Sysbox installed)
   - Do NOT enable secure-boot (might be GKE specific).
 - Follow these [directions](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#installation-of-sysbox) to install Sysbox on your cluster.
 - Install Actions Runner Controller.
 - Follow Sysbox Pod Deployment [instructions](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#pod-deployment) to deploy your runners. Here is how my deployment looks like:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: linux-runner
  namespace: default
spec:
  replicas: <NUMBER_OF_RUNNERS>
  template:
    metadata:
      annotations:
        io.kubernetes.cri-o.userns-mode: "auto:size=65536"
    spec:
      repository: <YOUR_REPO>
      labels:
        - self-hosted
      env:
        # Tell controller to use --ephemeral vs to be deprecated --once flag.
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
        # Delay start to avoid hitting
        # https://github.com/actions-runner-controller/actions-runner-controller/issues/787
        - name: STARTUP_DELAY_IN_SECONDS
          value: "5"
      runtimeClassName: "sysbox-runc"
      imagePullPolicy: Always
      ephemeral: true
      dockerdContainerResources:
        limits:
          cpu: "16"
          memory: "64Gi"
        requests:
          cpu: "10"
          memory: "32Gi"
```

Keep in mind, Sysbox CE has certain limitations.  For instance, number of pods per node is capped at 16.
