### ISSUE TITLE
Allow volumeStorageMedium for the 'work' mount

### ISSUE THREAD

**Issue by edspencer** [actions-runner-controller/actions-runner-controller#1007]
**Is your feature request related to a problem? Please describe.**
Yes - our runners grind to a halt, apparently because of the large amount of I/O performed by Yarn. We have a fairly standard Node JS + React application - on each push on any branch we run a series of jobs to build the Node JS API server artifact, the UI artifacts, run tests, etc.

Each job starts by running yarn install. As we're relatively package-heavy, this is extremely I/O intensive, making hundreds of thousands of reads and especially writes. This is partly due to Yarn not being particularly efficient, but that's another story, and we'd want this ability regardless.

We use the `volumeStorageMedium: 'Memory'` option to configure the `runner` mount to use the system's memory. This works great. I believe that if there was an equivalent config for the `work` mount, our jobs would speed up tremendously.

**Describe the solution you'd like**
I would like to be able to set the `Medium` of the `work` mount to `Memory`, just as I can for the `runner` mount using `volumeStorageMedium: 'Memory'`

**Describe alternatives you've considered**
Currently I'm only able to use the actions-runner-controller for 1 out of our dozen or so jobs, because running more than one at a time appears to saturate the underlying k8s node's drive with I/O requests. So our pipelines run pretty slowly because we have to rely on the github cloud-hosted runners for most 

**Additional context**

![Screen Shot 2021-12-13 at 11 28 39 PM](https://user-images.githubusercontent.com/6929/145933307-55e03c5e-207c-4d68-b97b-bf412064be19.png)

**Comment by mumoshu** [comment]
@edspencer Hey! Thanks for reporting.

I think you can do that today, by setting `runner.spec.workDir` to somewhere else than the default `/runner/_work` and adding a corresponding pair of volume and volume mount definition to `runner.spec.volumes` and `runner.spec.volumeMounts` respectively.

If you do need to implement this, probably adding `workerVoumeStorageMedium` and use that from `runner_controller.go` would do the job.

That said, I'm not entirely sure if that's the right approach! AFAIK `medium: memory` consumes the node memory so you won't be able to serve a lot of runner pods on one node when your git repo and project dependencies(like node modules) can take GBs of a disk, which defeats the purpose of your original goal of making it possible for a single node to serve two or more runner pods.

Which cloud platform are you running actions-runner-controller on? I was going to say, if you're using e.g. AWS, you'd better use bigger EC2 instance types with more EBS throughput or with a NVMe SSD.

**Comment by edspencer** [comment]
Hi @mumoshu :) 

I'm using an AWS [c6gd.12xlarge](https://aws.amazon.com/ec2/instance-types/c6g/), which has 48vCPU, 96Gb RAM and 2x 1425 NVMe SSDs. I'd hoped that this would be easily beefy enough to run these jobs, but even if 2 jobs are running concurrently they both grind to (almost) a halt. Poking around in the AWS console I see the IOPs quickly hitting 3000, which is the rated capacity of that machine.

I guess there's some thrashing going on because when 1 job runs it takes ~1 min to run `yarn install`, but when 2 jobs run concurrently each takes more like 6 mins. Aside from the `yarn install` part, the jobs run like lightning. This coupled with the AWS console observations is what makes me believe we're being swamped with IO.

We're trying to achieve a <5 minute pipeline, so the nature of the use case is short bursts of intensive building, followed by long stretches of complete idleness. So I think because we have 96Gb RAM on that machine we can probably get away with running a ~10 jobs concurrently - even if they were to try to consume ~10Gb each we'd probably still be ok, and the pipeline speed would be well worth it for us.

Anyway, here's what I tried based on your suggestion:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
spec:
  replicas: 10
  template:
    spec:
      repository: SECRET!
      image: SECRET!
      volumeStorageMedium: 'Memory'
      env: []
      workDir: /runner/memory/_work
      volumes:
        - name: workmem
          emptyDir:
            medium: Memory
      volumeMounts:
        - mountPath: /runner/memory/_work
          name: workmem
```

Which gives the error:

`2021-12-14T15:59:23.820Z	ERROR	controller-runtime.manager.controller.runner-controller	Reconciler error	{"reconciler group": "actions.summerwind.dev", "reconciler kind": "Runner", "name": "example-runnerdeploy-fhq94-gbxgl", "namespace": "default", "error": "Pod \"example-runnerdeploy-fhq94-gbxgl\" is invalid: spec.containers[0].volumeMounts[3].mountPath: Invalid value: \"/runner/memory/_work\": must be unique"}`

If I comment out `workDir` then it creates the mount and volume mount just fine, but obviously the work dir doesn't actually use the new mount. I think I'm getting the error because I'm making a volume mount that conflicts with the one made for `workDir`, so unless I'm missing something I don't think I can achieve what I'm trying to do from config alone. I'd need to be able to tell the runner_controller to use my configured `workDir` but to skip the step in https://github.com/actions-runner-controller/actions-runner-controller/blob/f0fccc020b66b4d8b4cb4970f3d36a96562f5da9/controllers/runner_controller.go#L980 where it makes its own mount for it. I also tried setting the `RUNNER_WORKDIR` env var on a hunch, but it gets overwritten.

So as far as I can tell, I would indeed need a code change here - do you agree? Currently I install using:

`kubectl apply -f https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.20.2/actions-runner-controller.yaml`

Which is super easy and Just Works. I'm nervous about changing the Go code but happy to give it a try if you think that's what I need to do :)

**Comment by mumoshu** [comment]
> I'm using an AWS c6gd.12xlarge, which has 48vCPU, 96Gb RAM and 2x 1425 NVMe SSDs

OMG it turns out you were using 10x beefier machines than I have thought!!! 🤣 The world is big.

> So I think because we have 96Gb RAM on that machine we can probably get away with running a ~10 jobs concurrently

Yeah, this makes sense now.

Also, sorry about sharing seemingly wrong workaround. Yeah, as you pointed out it seems like we need code change.

I reviewed the codebase. Probably the change should be made around:

https://github.com/actions-runner-controller/actions-runner-controller/blob/f0fccc020b66b4d8b4cb4970f3d36a96562f5da9/controllers/runner_controller.go#L964-L969

This hard-coded volume should be dynamically generated depending on a new field added to runner spec.

And the new logic to generate the volume would look very similar to

https://github.com/actions-runner-controller/actions-runner-controller/blob/f0fccc020b66b4d8b4cb4970f3d36a96562f5da9/controllers/runner_controller.go#L925-L935

A completely untested example of new code I had in my mind is:


```
workVolumeName := "work"
workVolumeEmptyDir := &corev1.EmptyDirVolumeSource{}

if runnerSpec.WorkVolumeStorageMedium != nil {
	workVolumeEmptyDir.Medium = corev1.StorageMedium(*runnerSpec.WorkVolumeStorageMedium)
}

if runnerSpec.WorkVolumeSizeLimit != nil {
	workVolumeEmptyDir.SizeLimit = runnerSpec.WorkVolumeSizeLimit
}

...

pod.Spec.Volumes = append(pod.Spec.Volumes,
	corev1.Volume{
		Name: workVolumeName,
		VolumeSource: corev1.VolumeSource{
			EmptyDir: workVolumeEmptyDir,
		},
	},
	// unchanged
	corev1.Volume{
		Name: "certs-client",
		VolumeSource: corev1.VolumeSource{
			EmptyDir: &corev1.EmptyDirVolumeSource{},
		},
	},
)
```

> I'm nervous about changing the Go code but happy to give it a try if you think that's what I need to do :)

I always appreciate your contribution ☺️

**Comment by genisd** [comment]
Hello I'm kind of experiencing a similar challenge. I don't want to hijack this issue, so if you feel like I am doing that please let me know and I'll open a separate issue.

The challenge is exactly the same, disk i/o is just not sufficient so we would like the `workDir` or `work` volume to reside on NVME ssd.

I have done this for docker in docker like so (note this is on GKE).
On the host node nvme ssd is available at /mnt/disks/ssd0

```
       dockerVolumeMounts:
        - mountPath: /var/lib/docker
          name: scratch
          subPathExpr: $(POD_NAME)-docker
       dockerEnv:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
       volumes:
        - hostPath:
            path: /mnt/disks/ssd0
          name: scratch
```

So basically I would like to create and provide the `work` volume myself, but i cannot override the existing volume. Like @edspencer the error is that subsequently the `work` volume is defined twice -> duplicate key error.

Like so:
```
       dockerVolumeMounts:
        - mountPath: /runner/_work/
          name: work
          subPathExpr: $(POD_NAME)-work
       volumeMounts:
        - mountPath: /runner/_work/
          name: work
          subPathExpr: $(POD_NAME)-work
       dockerEnv:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
       env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

       volumes:
        - hostPath:
            path: /mnt/disks/ssd0
          name: work
```

The issue is really related. Mr spencer would like a in-memory volume and I would like a NVME volume.

As far as a potential solution goes, would it not be feasible to not re-create the volume(mount) if it has been provided outside?
This would give users maximum flexibility and I think that solution would work for both of us.

Alternatively perhaps it would be helpful if when a workDir is specified, that this directory is "simply" used under the assumption that the operator knows what he is doing ?

Right now if `workDir: /foo/bar` is provided, a `work` volume is automatically created under that directoy which prevents us from using a different volume to hold that data.

**Comment by edspencer** [comment]
Well, I was able to get this kinda working by following the contribution steps and @mumoshu's suggestions (thanks for that!). I made basically the changes you suggested @mumoshu (though I had to add a couple of things into `runner_types.go` too).

Was able to build a docker image with the changes and get it deployed onto my k8s cluster by downloading https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.20.2/actions-runner-controller.yaml, changing the image name for the controller deployment, and applying using `kubectl apply`. This feels like a pretty horrible way of doing that, but it worked. I should probably be rebuilding that big ole yaml file with helm?

Perhaps because of this, when I tried specifying the new `workVolumeStorageMedium: 'Memory'`, kubernetes complained that this failed validation. Seems like the Go controller knows about the config but there's some k8s-level validation going on. Wasn't sure how to get past that - presumably something grabs my new fields added to `runner_types.go` and moves them into some k8s definition. If you can give a hint on how to do that I'll try it out.

Anyway long story short I temporarily bypassed all that and made the Go controller use the same `Medium` for both the runner and work mounts, giving me the following:

```
    Mounts:
      /certs/client from certs-client (rw)
      /runner from runner (rw)
      /runner/_work from work (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g8vjg (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  runner:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  work:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
```

Cool. That's what I wanted. But, for reasons I don't understand, when I run my job, which I can see is definitely doing its work inside the `/runner/_work` directory, it is ALSO writing to the underlying disk. So it's still every bit as slow as it was before :'( I really have no idea why it's doing that, as I would have thought that an `EmptyDir` configured as `Memory` would never write anything to any underlying disk, but I can clearly see it making 120k IOPs in my AWS console.

I feel like I'm 95% of the way there, just can't figure out why the disk is still being written to. The files that are written are ending up in `/runner/_work/myproject/myproject/node_modules/*`. My mental model is that everything under `/runner/_work` should be writing only against Memory, but maybe the subdirs somehow get assigned back to the disk? Confused 😐

**Comment by edspencer** [comment]
I did a little more digging - turns out yarn creates a cache dir at `/home/runner/.cache/yarn/v6` and performs a gigantic number of reads/writes there. In our case, hundreds of thousands. By running `yarn config set cache-folder /runner/_work/.yarn-cache` I got it to use my Memory volume, which ended up being enormously faster 🙌🏻

I'd love to understand the mechanics of how `/home/runner/` (not to be confused with `/runner/`) is tied into the k8s node's underlying disk - I don't see any mounts defined anywhere that set this up but it's clearly happening. A bit later in the job I run a webpack build command (via yarn), which seems to dump a bunch of files in `/tmp`, so that seems like a good candidate to be backed by a memory volume too.

Overall this is much better though :)

**Comment by mumoshu** [comment]
Ah, that makes sense! Thanks a lot for your efforts and sharing your experience(and insights!).

There's no dedicated volume mount at `/home/runner` so I guess it's based on the storage driver your container engine is using. If docker it might be overlayfs, btrfs, etc backed. In that case it would be natural it's read/write goes to the disk in the end.

I don't have immediate access to a test environment but if you could try- running `df -h` or something like that within your runner pod's runner container would reveal what's backing `/home/runner` (or there's isn't one specific to `/home/runner`, you'd see one tied to `/home`, or even `/`)

**Comment by edspencer** [comment]
Yeah good call - looks like it's the overlayfs. I'll keep poking around to see if I can eliminate the remaining SSD writes, but things are already much better now :)

It's my last day before a Christmas break so I may not get round to making a PR for this stuff until I'm back. I see 2 options there:

1. Easy option: Just make both the `runner` and the `work` volumes be configured by the existing `volumeStorageMedium` config
2. Slightly harder: Introduce a second config called workVolumeStorageMedium as discussed. I'd need to figure out how to deploy this such that kubernetes accepts the new `workVolumeStorageMedium` config though as right now it complains about that.

Do you have a preference?

**Comment by mumoshu** [comment]
Thanks! I'd prefer option 2 for consistency.

> I'd need to figure out how to deploy this such that kubernetes accepts the new workVolumeStorageMedium config though as right now it complains about that.

Still curious but how did to complain? Perhaps sharing the exact error of more context of what happened would be super helpful for me!

I was even wondering if something like the below just works:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
spec:
  replicas: 10
  template:
    spec:
      volumes:
        - name: home
          emptyDir:
            medium: Memory
      volumeMounts:
        - mountPath: /home/runner
          name: home
      dockerVolumeMounts:
        - mountPath: /home/runner
          name: home
```

Or even this if `/home/runner` mount conflicts with something already in the container:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
spec:
  replicas: 10
  template:
    spec:
      env:
      - name: HOME
        value: /elsewhere/home/runner
      dockerEnv:
      - name: HOME
        value: /elsewhere/home/runner
      volumes:
        - name: home
          emptyDir:
            medium: Memory
      volumeMounts:
        - mountPath: /elsewhere/home/runner
          name: home
      dockerVolumeMounts:
        - mountPath: /elsewhere/home/runner
          name: home
```
