### ISSUE TITLE
RunnerDeployment pod not resolving internal DNS record

### ISSUE THREAD

**Issue by wilinger** [actions-runner-controller/actions-runner-controller#1022]
I'm trying to use the self hosted runner to apply terraform changes to my vault instance hosted internally on my network and the runner deployment is having issues resolving the internal DNS record for vault when the terraform plan step is ran.  I added the hostAliases in spec for the RunnerDeployment and I am able to ping the hostname when I connect to the container inside the pod but I'm still getting a lookup error.  I tried setting dnsPolicy and dnsConfig under spec but it doesn't work. 

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "10"
spec:
  template:
    spec:
      repository: wilinger/terraform-homelab
      hostAliases:
      - ip: "10.10.30.50"
        hostnames:
        - "vault.mycluster.org"
```

```
Run terraform plan
  terraform plan
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TERRAFORM_CLI_PATH: /runner/_work/_temp/548d26c0-924d-4f07-a427-bb1f281162cd
/runner/_work/_temp/548d26c0-924d-4f07-a427-bb1f281162cd/terraform-bin plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/mycluster/terraform-homelab/runs/run-999792BUx3tPY93L

Waiting for the plan to start...

Terraform v1.1.2
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
╷
│ Error: Get "https://vault.mycluster.org/v1/auth/token/lookup-self": dial tcp: lookup vault.mycluster.org on 127.0.0.53:53: no such host
│ 
│   with provider["registry.terraform.io/hashicorp/vault"],
│   on main.tf line 16, in provider "vault":
│   16: provider "vault" {
│ 
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```
