### ISSUE TITLE
HorizontalRunnerAutoscaler doesn't scale RunnerSet

### ISSUE THREAD

**Issue by erplsf** [actions-runner-controller/actions-runner-controller#1100]
**Describe the bug**
It seems that in current release, I can't get `HorizontalRunnerAutoscaler` to target `RunnerSet`, but with `RunnerDeployment` it works just fine.

Here's my code (ignore the helm variables, important thing is that the name in `scaleTargetRef` matches the one in the `RunnerSet`:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: reproduce-set
spec:
  organization: {{ required "orgName is required" .Values.orgName | quote }}
  selector:
    matchLabels:
      runnerset-name: reproduce-set
  serviceName: reproduce-set
  template:
    metadata:
      labels:
        runnerset-name: reproduce-set
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: reproduce-set-autoscaler
spec:
  scaleTargetRef:
    name: reproduce-set
  minReplicas: 3
  maxReplicas: 5
```

**Checks**

- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Apply the above manifest to a cluster.

**Expected behavior**
I expected my RunnerSet to be scaled from 1 to 3 (as required by `HorizontalRunnerAutoscaler`, but it didn't happen.

**Screenshots**
<img width="1906" alt="Screenshot 2022-02-08 at 13 13 22" src="https://user-images.githubusercontent.com/4072364/152985151-20539c20-f964-45a0-926f-1ee9c1acaaf6.png">
<img width="1904" alt="Screenshot 2022-02-08 at 13 14 59" src="https://user-images.githubusercontent.com/4072364/152985157-9d08bc31-04cd-4880-8a4d-4d013fdc9566.png">

In the screenshot `default-runner-set` has manually set `replicas` to 3.

**Environment (please complete the following information):**
 - Controller Version [0.15.2]
 - Deployment Method [Helm]
 - Helm Chart Version [0.15.2]

**Additional context**

**Comment by erplsf** [comment]
And this is what works:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: reproduce-deployment
spec:
  template:
    spec:
      organization: {{ required "orgName is required" .Values.orgName | quote }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: reproduce-deployment-autoscaler
spec:
  scaleTargetRef:
    name: reproduce-deployment
  minReplicas: 3
  maxReplicas: 5
```
![Uploading Screenshot 2022-02-08 at 13.27.13.png…]()
