### ISSUE TITLE
CustomResourceDefinition.apiextensions.k8s.io "runners.actions.summerwind.dev" is invalid: metadata.annotations: Too long

### ISSUE THREAD

**Issue by donovanmuller** [actions-runner-controller/actions-runner-controller#1102]
**Describe the bug**

After updating to the `0.15.3` Chart I am getting the following error when sync'ing the Chart via ArgoCD:

```
Failed sync attempt to f4b6f0a64ab13ed7478264478306ca231b22ff44: one or more objects failed to apply, reason: CustomResourceDefinition.apiextensions.k8s.io "runners.actions.summerwind.dev" is invalid: metadata.annotations: Too long: must have at most 262144 bytes,unable to recognize "/dev/shm/471866979": no matches for kind "RunnerDeployment" in version "actions.summerwind.dev/v1alpha1",CustomResourceDefinition.apiextensions.k8s.io "runnerdeployments.actions.summerwind.dev" is invalid: metadata.annotations: Too long: must have at most 262144 bytes,CustomResourceDefinition.apiextensions.k8s.io "runnerreplicasets.actions.summerwind.dev" is invalid: metadata.annotations: Too long: must have at most 262144 bytes (retried 5 times).
```

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Update ArgoCD Application with the `0.15.3` Chart version
2. After a failed sync, the error message above presented
3. Controller fails to start with `no matches for kind \"RunnerReplicaSet\"`

**Expected behavior**
ArgoCD Application syncs successfully and controller is running.

**Environment (please complete the following information):**
 - Controller Version: `0.20.4`
 - Deployment Method: Helm via ArgoCD Application
 - Helm Chart Version: `0.15.3`

**Additional context**
This is a similar/same issue as faced in https://github.com/prometheus-community/helm-charts/issues/1500

**Comment by mumoshu** [comment]
@donovanmuller This is the limitation of K8s. You need to use `kubectl replace` instead of `kubectl apply` to upgrade CRDs.

**Comment by donovanmuller** [comment]
@mumoshu agreed, however, using the Helm chart and then especially when using Argo CD makes this more challenging than it should be.

I've worked around it by applying the [advice](https://github.com/prometheus-community/helm-charts/issues/1500#issuecomment-968892923) from the Prometheus thread and using a [Helm + Kustomize](https://github.com/argoproj/argocd-example-apps/blob/master/plugins/kustomized-helm/README.md) setup to add the `argocd.argoproj.io/sync-options: Replace=true` annotation to the affected CRD's.

If there's nothing to action, happy to close.

**Comment by mumoshu** [comment]
@donovanmuller Hey, thanks for sharing your work-around!
JFYI, having two ArgoCD apps, one for skipCRDs=true and another for Replace=true is said to work in recent RC version of ArgoCD. Perhaps that's a cleaner solution once released.

https://github.com/prometheus-operator/prometheus-operator/issues/4439#issuecomment-1030198014

**Comment by jimmyh85** [comment]
@donovanmuller , would you mind sharing your solution? How did you include the CRDs into your kustomiziation folder? Do they need to be added manually or can they be referenced in a smarter way? Might be helpful for everyone who is using ArgoCD and the actions runner controller :)

**Comment by yohang88** [comment]
> advice

I'm following solution at https://github.com/prometheus-operator/prometheus-operator/issues/4439#issuecomment-1030198014 at get this problem solved.

```yaml
    syncOptions:
    - Replace=true
 ```

**Comment by donovanmuller** [comment]
> @donovanmuller , would you mind sharing your solution? How did you include the CRDs into your kustomiziation folder? Do they need to be added manually or can they be referenced in a smarter way? Might be helpful for everyone who is using ArgoCD and the actions runner controller :)

@jimmyh85 Using the [Helm + Kustomize](https://github.com/argoproj/argocd-example-apps/blob/master/plugins/kustomized-helm/README.md?rgh-link-date=2022-02-16T05%3A39%3A13Z) approach, we just use `patchesStrategicMerge` to add just the annotation to the CRD's rendered from the Helm Chart.

E.g.
`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../helm

patchesStrategicMerge:
  - patch/runners-crd.yaml
```

`patch/runners-crd.yaml`
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: runners.actions.summerwind.dev
```

**Comment by KENNYSOFT** [comment]
> > advice
> 
> I'm following solution at [prometheus-operator/prometheus-operator#4439 (comment)](https://github.com/prometheus-operator/prometheus-operator/issues/4439#issuecomment-1030198014) at get this problem solved.
> 
> ```yaml
>     syncOptions:
>     - Replace=true
> ```

Thanks, can achieve the same result by setting in web dashboard:

![image](https://user-images.githubusercontent.com/6624567/154666574-70cd23d8-b5f9-47b2-967b-70a25dcd5196.png)

**Comment by jimmyh85** [comment]
@norman-zon, I also had some issues in setting it up via kustomized-helm, as the helm template and solved it by using below plugin config
`
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE --include-crds > all.yaml && kustomize build"]
`
Main problem was that the example of helm-kustomized did not consider the namespace. Hope this helps, but the approach to use the sync option replace=true might be easier

**Comment by donovanmuller** [comment]
> @donovanmuller, what does your `kustomized-helm` plugin config look like? If I use the [default config](https://github.com/argoproj/argocd-example-apps/blob/master/plugins/kustomized-helm/README.md?rgh-link-date=2022-02-18T12%3A56%3A51Z) CRDs are not rendered. Do you just add `--include-crds` ?

@norman-zon 👍 

```yaml
configManagementPlugins: |
  - name: kustomized-helm
    init:
      command: ["/bin/sh", "-c"]
      args: ["helm dependency build ../../helm || true"]
    generate:
      command: ["/bin/sh", "-c"]
      args: ["echo \"$HELM_VALUES\" | helm template ../../helm --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE $HELM_ARGS -f - --include-crds > ../../helm/all.yaml && kustomize build"]
```
