### ISSUE TITLE
0.21.0 with organization seems requiring group

### ISSUE THREAD

**Issue by KENNYSOFT** [actions-runner-controller/actions-runner-controller#1131]
**Describe the bug**
I think #1012 broke my workload. We're using the organization with GitHub Team plan, so we're not available to make an additional runner group; only 'Default' exists. We have only organization-level runners like:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  namespace: actions-runner-system
  name: github-actions-runnerdeploy
spec:
  template:
    spec:
      organization: myorg
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  namespace: actions-runner-system
  name: github-actions-runner
spec:
  scaleTargetRef:
    name: github-actions-runnerdeploy
  scaleUpTriggers:
    - githubEvent: {}
      duration: "30m"
```

To 0.20.4, there were two logs that tried to find HRAs by key:

> Found 0 HRAs by key    {"key": "myorg/repo-name"}
> Found 1 HRAs by key    {"key": "myorg"}

But in 0.21.0, only the former one appears.

If I modify RunnerDeployment as:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  namespace: actions-runner-system
  name: github-actions-runnerdeploy
spec:
  template:
    spec:
      organization: myorg
      group: Default
```

now I get two logs but it's somehow different and not understood well.

> Found 0 HRAs by key    {"key": "myorg/repo-name"}
> Found some runner groups are managed by ARC    {..., "groups": {}}
> groups    {..., "groups": {}}
> Found 1 HRAs by key    {"key": "myorg/group/Default"}
> job scale up target found    {..., "organization": "myorg", "repository": "repo-name", "key": "myorg/group/Default"}

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Install v0.20.4, make a `HorizontalRunnerAutoscaler` with provided manifests, and confirm that it works well.
2. Upgrade to v0.21.0 and see that auto-scale does not work.
3. Add `group` property to the `RunnerDeployment` and see it re-works.

**Expected behavior**
If it's an intended change, it should be documented.

**Screenshots**
Since the object in logs can contain sensitive information, I can share only some parts of screenshots. Check for the quote block.

![image](https://user-images.githubusercontent.com/6624567/154720739-b4004d19-1457-4c4d-9cc1-f99750a6e5b0.png)
▲ With 0.20.4

![image](https://user-images.githubusercontent.com/6624567/154787038-ea3737ee-9b4e-47b6-b06d-596798f64956.png)
▲ With 0.21.0, without `group: Default` added (![image](https://user-images.githubusercontent.com/6624567/154787079-1bbb7f3d-4110-4828-af8f-8da721c07a8f.png) RED = myorg, ![image](https://user-images.githubusercontent.com/6624567/154787089-f2ea6fa2-20a1-43bf-b95d-ced90d4956a2.png) YELLOW = repo-name)

![image](https://user-images.githubusercontent.com/6624567/154721003-4d8fe7fc-565f-43a0-b46b-78ac971e33de.png)
▲ With 0.21.0 and `group: Default` added

**Environment (please complete the following information):**
 - Controller Version: 0.21.0
 - Deployment Method: Argo CD, with Helm values given in apps.argoproj.io/v1alpha1/applications
 - Helm Chart Version: 0.16.0

**Additional context**
