### ISSUE TITLE
no matches for kind "RunnerDeployment" in version "actions.summerwind.dev/v1alpha1" after upgrading from 0.14.0 to 0.16.1

### ISSUE THREAD

**Issue by roshvin** [actions-runner-controller/actions-runner-controller#1155]
**Describe the bug**
our setup was working fine with action runner controller version 0.14.0 
after upgrading to version 0.16.1  we are getting below error while creating runnderdeployment.

```
#kubectl  apply -f runner.yaml_1
error: unable to recognize "runner.yaml_1": no matches for kind "RunnerDeployment" in version "actions.summerwind.dev/v1alpha1"
```

```
# cat runner.yaml_1
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dot-runner
spec:
  template:
    spec:
      enterprise: daimler123
      labels:
      - dot-enterprise-runner
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      image: registry.actions-runner
      dockerEnabled: false
      securityContext:
        runAsUser: 1000
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
```

NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
github-actions-runner   github-actions-runner   2               2022-02-22 16:03:29.606710079 +0530 IST deployed        actions-runner-controller-0.16.1        0.21.1

**Checks**

- [ ] My actions-runner-controller version (0.16.1 - 0.21.1) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [e.g.-0.16.1]
 - Deployment Method [e.g. Helm and Kustomize ]
 - Helm Chart Version [e.g. 0.11.0, if applicable]

**Additional context**
