### ISSUE TITLE
how to scale HRA only with specific workfflow label and not with label self-hosted 

### ISSUE THREAD

**Issue by roshvin** [actions-runner-controller/actions-runner-controller#1186]
**Describe the bug**
in below Runnerdeployment , i am giving label as ```dot-enterprise-runner``` . but if i run a workflow with label ```self-hosted``` . HRA is scaling Runnerdeployment.

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dot-runner
spec:
  template:
    spec:
      enterprise: xxxxxx
      labels:
      - dot-enterprise-runner
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      image: rxxxxxx/actions-runner
      dockerEnabled: false
      securityContext:
        runAsUser: 1000
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
```

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [Latest]
 - Deployment Method [Latest ]
 - Helm Chart Version [e.g. 0.11.0, if applicable]

**Additional context**
