### ISSUE TITLE
Webhook autoscaller ignore currently idle runners and spawn new runner

### ISSUE THREAD

**Issue by askoriy** [actions-runner-controller/actions-runner-controller#1219]
**Is your feature request related to a problem? Please describe.**

I have the next configuration:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner
spec:
  template:
    spec:
      labels:
      - runner
      repository: askoriy/test-repo
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: autoscaller
spec:
  scaleTargetRef:
    name: runner
  scaleUpTriggers:
  - githubEvent: {}
    amount: 1
    duration: "5m"
  minReplicas: 3
  maxReplicas: 10
```

I want to have several _hot_ runners and use autoscaller _only_ if they are not enough.
But currently, every time workflow_job webhook is received the new runner is spawned, regardless there are enough idle runners to catch the job without scaling up.

Keeping non-zero `minReplicas` makes faster workflow running, but Webhook Driven Scaling makes resource utilization ineffective because of unnecessary extra scaling up.

**Describe the solution you'd like**
I expect to scale only if the number of current workflow_job `queue` events is more than the `minReplicas` runners.
