### ISSUE TITLE
dnsConfig doesn't seem to translate to created pods for the Runners

### ISSUE THREAD

**Issue by billimek** [actions-runner-controller/actions-runner-controller#1226]
**Describe the bug**

With the following `RunnerDeployment` config snippet,

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: myorg-ephemeral-dns
  namespace: actions
spec:
  replicas: 1
  template:
    spec:
      organization: myorg
      labels:
        - myorg-onprem-dns
      dnsConfig:
        - options:
          - name: "ndots"
            value: "1"
```

... The `Runners` get created with the dnsConfig settings, but the associated pods do not.  I've experimented with different indenting and even other dnsConfig type settings, but nothing seems to translate to a change to the pod spec configuration or the actual `/etc/resolv.conf` file being changed.

I think we may be missing something like this in `controllers/runner_controller.go`, based on comparing this change with a [similar change](https://github.com/actions-runner-controller/actions-runner-controller/pull/456)

```go
	if len(runner.Spec.DnsConfig ) != 0 {
		pod.Spec.DnsConfig = runner.Spec.DnsConfig 
	}
```

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

Please see context in the description above.

**Expected behavior**

Expect to see the pods being created for the Runner(s) contain the appropriate dnsConfig settings as well as the actual pod execution runtime with the expected changes in `/etc/resolv.conf`

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version: 0.20.4
 - Deployment Method: Helm
 - Helm Chart Version: 0.15.3

**Additional context**
I intend to submit a PR for what I think the fix may be.  Currently struggling with getting the make/environment to build properly (trying on both in MacOS and a linux VM without success)
