### ISSUE TITLE
runners are not scaling up as per job count 

### ISSUE THREAD

**Issue by roshvin** [actions-runner-controller/actions-runner-controller#1238]
**Describe the bug**
i am trigger 100 workflow job
i can see 100 runners created.
after some time 50 job will be pending to run
but that moment i can only see 5 to 10 runners avaialbe. and the workflow run will slow down and use only available runners.
am i missing something in the configuration.

```
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
github-actions-runner   actions-runner-system   5               2022-03-17 18:18:41.462305267 +0530 IST deployed        actions-runner-controller-0.17.0        0.22.0
```

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dot-runner
spec:
  template:
    spec:
      enterprise: xxxxx
      labels:
      - dot-enterprise-runner
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      image: rxxxxxxxx/actions-runner
      dockerEnabled: false
      securityContext:
        runAsUser: 1000
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
```

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
   name: ent-runner-auto-scaller
spec:
  scaleDownDelaySecondsAfterScaleOut: 5
  scaleTargetRef:
    name: dot-runner
  minReplicas: 1
  maxReplicas: 300
  scaleUpTriggers:
  - githubEvent: {}
    duration: "30m"
```
