### ISSUE TITLE
Webhook server is throwing 'error while finding visible runner groups'

### ISSUE THREAD

**Issue by lolletsoc** [actions-runner-controller/actions-runner-controller#1240]
**Describe the bug**
```
"error": "error while finding visible runner groups: failed to list organization runner groups: GET https://api.github.com/orgs/*****/actions/runner-groups?per_page=100: 404 Not Found []"
```
The webhook server seems to be trying to hit a GitHub Enterprise only API (https://docs.github.com/en/rest/reference/actions#list-self-hosted-runner-groups-for-an-organization)

I've not configured for Enterprise - at least I don't think I have.

**To Reproduce**
1. Deploy webhook server using either PAT or GitHub App

**Expected behavior**
The webhook server should work

**Environment (please complete the following information):**
 - Controller Version is 0.22.0
 - Deployment Method is Kubernetes YAMLs

**Comment by toast-gear** [comment]
What does your yaml look like?

**Comment by mumoshu** [comment]
I think ARC's current behavior implies that you must not pass GitHub credentials to githubhookserver in case you aren't using runner groups at all.
https://github.com/actions-runner-controller/actions-runner-controller/blob/c06a806d759f0a83b8b5b03942dd9dc42b521f7e/controllers/horizontal_runner_autoscaler_webhook.go#L496-L516

**Comment by lolletsoc** [comment]
> I think ARC's current behavior implies that you must not pass GitHub credentials to githubhookserver in case you aren't using runner groups at all.
> 
> https://github.com/actions-runner-controller/actions-runner-controller/blob/c06a806d759f0a83b8b5b03942dd9dc42b521f7e/controllers/horizontal_runner_autoscaler_webhook.go#L496-L516

Ah, thank you, that's really helpful! I will investigate a bit further and let you know.

**Comment by lolletsoc** [comment]
In case anyone else comes across this, do not provide any credentials, just the `GITHUB_WEBHOOK_SECRET_TOKEN`

For example
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-github-webhook-server
  namespace: ***
  labels:
    control-plane: controller-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-webhook
  template:
    metadata:
      labels:
        control-plane: controller-webhook
    spec:
      containers:
      - args:
        - "--metrics-addr=127.0.0.1:8080"
        - "--sync-period=10m"
        - "--watch-namespace=***"
        command:
        - "/github-webhook-server"
        env:
        - name: GITHUB_WEBHOOK_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: github-webhook-secret-token
        image: summerwind/actions-runner-controller:v0.22.0
        name: github-webhook-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: quay.io/brancz/kube-rbac-proxy:v0.11.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      terminationGracePeriodSeconds: 10
```
