### ISSUE TITLE
what does it mean "user repositories not supported"?

### ISSUE THREAD

**Issue by yourmoonlight** [actions-runner-controller/actions-runner-controller#1253]
**Describe the bug**

I had finished the webhook configuration，but when I tried to push，I got the following DEBUG message

`2022-03-21T15:40:28Z	DEBUG	controllers.webhookbasedautoscaler	user repositories not supported	{"event": "push", "hookID": "349188636", "delivery": "3b6da0c4-a92d-11ec-9628-7beee63ddb82", "owner": "yourmoonlight"}`

**Environment (please complete the following information):**
 - Controller Version [0.22]
 - Deployment Method [Helm]
 - Helm Chart Version [0.17.0]

**Comment by sbrinkerhoff** [comment]
Are you attempting to connect a runner to a user repository? (as apposed to an org/repo)?

**Comment by yourmoonlight** [comment]
> Are you attempting to connect a runner to a user repository? (as apposed to an org/repo)?

yes, it does not support user repo?

**Comment by mumoshu** [comment]
It's just a DEBUG-level log message that shouldn't harm the functionality of the webhook-based autoscaler
https://github.com/actions-runner-controller/actions-runner-controller/blob/f28cecffe9731926309bdd5e6f1419a8fd87dcf1/controllers/horizontal_runner_autoscaler_webhook.go#L474

**Comment by yourmoonlight** [comment]
> user repositories not supported

2022-03-21T15:40:28Z	DEBUG	controllers.webhookbasedautoscaler	Scale target not found. If this is unexpected, ensure that there is exactly one repository-wide or organizational runner deployment that matches this webhook event	{"event": "push", "hookID": "349188636", "delivery": "3b6da0c4-a92d-11ec-9628-7beee63ddb82"}

this is the log after that

**Comment by mumoshu** [comment]
@yourmoonlight That's an error unrelated to the debug message and points out that you should have a configuration mistake

**Comment by mumoshu** [comment]
@yourmoonlight Do you have any repository to share all your HRA and RunnerDeployment that I can see?
Perhaps you're trying to use an organizational runners for an useraccount(it won't work), or you just don't have RunnerDeployment pointed tot your repository.

**Comment by jgreat** [comment]
I ran into this too when trying to connect the autoscaler to a user/repo.  Looks like line 475 would end up returning nil and triggering the misleading `Scale target not found` message.

https://github.com/actions-runner-controller/actions-runner-controller/blob/f28cecffe9731926309bdd5e6f1419a8fd87dcf1/controllers/horizontal_runner_autoscaler_webhook.go#L475

Can I ask why a the HRA webhook doesn't support a user repository?

**Comment by mumoshu** [comment]
@jgreat The log was added in https://github.com/actions-runner-controller/actions-runner-controller/commit/4ebec3820810e9d72032118870d44b23c1a47cc2 and it basically says that everything after line "478" that is intended to support runner groups(which are enterprise features not available to user repos).

User repositories are indeed supported by ARC. If you configured your RunnerDeplomeny for a user repo correctly, the webhook event should hit the if block at #468 and triggers a scale https://github.com/actions-runner-controller/actions-runner-controller/blob/f28cecffe9731926309bdd5e6f1419a8fd87dcf1/controllers/horizontal_runner_autoscaler_webhook.go#L468-L471

**Comment by jgreat** [comment]
Thanks for clarifying. I've read and re-read the documentation and I seem to be stuck with the webhook autoscaler.  I don't understand why the webhook server can't seem to find the HRA.

I get this in the webhook server logs:

```
2022-03-23T01:07:08Z	DEBUG	controllers.webhookbasedautoscaler	Found 1 HRAs by key	{"key": "jgreat/mobilecoin"}
2022-03-23T01:07:08Z	DEBUG	controllers.webhookbasedautoscaler	user repositories not supported	{"event": "check_run", "hookID": "349422206", "delivery": "8fc91c70-aa45-11ec-8b74-c6eef2be3c5c", "owner": "jgreat"}
2022-03-23T01:07:08Z	DEBUG	controllers.webhookbasedautoscaler	Scale target not found. If this is unexpected, ensure that there is exactly one repository-wide or organizational runner deployment that matches this webhook event	{"event": "check_run", "hookID": "349422206", "delivery": "8fc91c70-aa45-11ec-8b74-c6eef2be3c5c", "checkRun.status": "queued", "action": "created"}
```

My RunnerDeployment and HRA:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-runner-org-small
spec:
  template:
    spec:
      # RunnerConfig
      # organization: jgreat
      repository: jgreat/mobilecoin
      labels:
      - self-hosted
      - small
      dockerdWithinRunnerContainer: true
      dockerMTU: 1350
      ephemeral: true
      image: summerwind/actions-runner-dind

      # RunnerPodSpec
      imagePullSecrets:
      - name: docker-credentials
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "2"
          memory: "4Gi"
      tolerations:
      - effect: NoSchedule
        key: builder
        operator: Exists
      nodeSelector:
        builder-node: 'true'
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: gha-runner-org-hra-small
spec:
  scaleTargetRef:
    name: gha-runner-org-small
    kind: RunnerDeployment
  minReplicas: 2
  maxReplicas: 30
  scaleUpTriggers:
  - githubEvent: {}
    amount: 1
    duration: "5m"
```

I've deployed the latest controller helm chart (0.17.0). I'm using the GitHub app authentication and configured the app webhook. I have the ingress setup and working, and I seem to be getting successful webhook deliveries.

Not sure what I'm doing wrong here.  Any help would be appreciated.
