### ISSUE TITLE
RunnerSet not using persistent storage after v0.20.2 -> v0.22.0 upgrade

### ISSUE THREAD

**Issue by larstiq** [actions-runner-controller/actions-runner-controller#1265]
**Describe the bug**

When we were using v0.20.2 with `ephemeral: false` RunnerSets we had docker laying caching working.  After upgrading to `v0.22.0` and dropping the `ephemeral: false` because my understanding from https://github.com/actions-runner-controller/actions-runner-controller/pull/1211/ was that this was not needed, there is no longer any persistent storage for the RunnerSets.

Adding the `ephemeral: false` back in does not help either.

Perhaps I misunderstood how this is supposed to work and it was either luck or having longer running pods that hid this problem? But the documentation https://github.com/actions-runner-controller/actions-runner-controller/#runnersets does make me think this should work.

One more clue, though the pods have `.metadata.labels.runnerset-name: persistent-runner` set, their name is `persistent-runner-<hash>-0`, not at all `StatefulSet` like.

**Checks**

- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Install/upgrade https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.22.0/actions-runner-controller.yaml
2. have a RunnerSet with this definition:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: persistent-runner
  namespace: default
spec:
  organization: myorg
  replicas: 2
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: persistent-runner
  serviceName: persistent-runner
  template:
    metadata:
      labels:
        app: persistent-runner
```
3. Trigger a GHA build with docker layer caching repeatedly
4. Observe lack of layer caching
5. Note lack of actual volume mounting:
```
> k get pods persistent-runner-857b4-0 -o yaml | yq eval .spec.volumes -
- emptyDir: {}
  name: runner
- emptyDir: {}
  name: work
- emptyDir: {}
  name: certs-client
- name: default-token-qzc5m
  secret:
    defaultMode: 420
    secretName: default-token-qzc5m

```

**Expected behavior**

Either the above `RunnerSet` definition should have persistent storage, or the documentation should be updated to not give that impression. 

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.18.2]
 - Deployment Method: download https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.22.0/actions-runner-controller.yaml and use it with kustomize
 - Helm Chart Version: not used

**Additional context**

The upgrade was a bit troublesome with `actions-runner-controller.yaml` too big to apply and deleting it ran into stuck finalizers. However, `k diff -f actions-runner-controller.yaml` now only lists changes in managed fields so there should be no issue there.

**Comment by toast-gear** [comment]
I think there has been a misunderstanding of how this works.

https://github.com/actions-runner-controller/actions-runner-controller/pull/1211 just changed the flag we are pass by default to a runner which is `ephemeral: true` (the default) from the legacy `--once` flag to the new (not that new now) GitHub supported `--ephemeral` flag. This is seperate and not related to the `ephemeral:` attribute. This attribute when set to `false` configures the runner as [persistent runner](https://github.com/actions-runner-controller/actions-runner-controller#persistent-runners). A persistent runner is just a runner that is not recreated after a job is completed and has neither the `--ephemeral` or the `--once` flags set for the runner service. You were getting docker layer caching before because the pod wasn't getting recreated rather than due to anything special about the RunnerSet kind. You could achieve the same thing with a RunnerDeployment with `ephemeral: false`.

The idea of RunnerSets is you can use the StatefulSet feature set enabling you to use PVCs in conjuction with `ephemeral: true` allowing for durable storage which brings benefits like docker cache (once PVCs and Docker are configured) whilst retaining the benefits of a determanistic environment (i.e. a new pod after each job completion).

**Comment by mumoshu** [comment]
@larstiq Probably toast-gear has answered everything you'd need to know, but anyway treat me as another data point;

`ephemeral: true|false` and `--ephemeral` are two different things. If you do want to keep your volumes reused across workflow jobs, do keep using static/persistent runners by setting `ephemeral: false`.

JFYI, in the context of ARC, `--once` and `--ephemeral` are the two different sub-modes of `ephemeral: true`(=ephemeral runners. `--once` has been deprecated and being replaced by `--ephemeral` so ARC 0.22.0 or greater uses `--ephemeral` by default for `ephemeral: true`. That's what https://github.com/actions-runner-controller/actions-runner-controller/pull/1211 does. You seems to prefer the behavior of static/persistent runners so you shouldn't use ephemeral runners, hence my answer above.

**Comment by larstiq** [comment]
> I think there has been a misunderstanding of how this works.

Right, I was afraid of that.

> You were getting docker layer caching before because the pod wasn't getting recreated rather than due to anything special about the RunnerSet kind. 

I swore I had seen storage stick after pod restarts, but couldn't confirm so there was a chance I was remembering the wrong thing, alas.

> The idea of RunnerSets is you can use the StatefulSet feature set enabling you to use PVCs in conjuction with ephemeral: true allowing for durable storage which brings benefits like docker cache (once PVCs and Docker are configured) whilst retaining the benefits of a determanistic environment (i.e. a new pod after each job completion). The initial implementation had limitations but I think they've all been lifted.

Good, that description is exactly what I want.   Can you confirm the Pod naming `persistent-runner-857b4-0` is the determinism that is expected?

> You'll need to configure PVs and PVCs on your RunnerSets to get durable storage, we don't implement that as it's going to be highly environment and cluster specific.

Fair enough, the GKE auto-provisioned persistent disks sometimes look like magic but they're not, back to the usual storage provisioning we go.

Thank you for you answer, even if it confirmed that my previous results were wishful thinking and a misunderstanding of an accident, I was braced for that and it's really helpful to get it straight.

**Comment by larstiq** [comment]
@mumoshu hmm, your answer on 

>  If you do want to keep your volumes reused across workflow jobs, do keep using static/persistent runners by setting ephemeral: false.

seems to contradict @toast-gear's answer on 

> The idea of RunnerSets is you can use the StatefulSet feature set enabling you to use PVCs in conjuction with ephemeral: true allowing for durable storage which brings benefits like docker cache (once PVCs and Docker are configured) whilst retaining the benefits of a determanistic environment (i.e. a new pod after each job completion). 


What I want is
1) persistent storage for caching (docker layers, mainly, so in the docker container)
2) clean runner environments after each build, seemingly easiest by just restarting the runner, what I hoped to get with `ephemeral: true`.

I've now added in the volumeClaimTemplates like so:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: persistent-runner
  namespace: default
spec:
  organization: myorg
  replicas: 2
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: persistent-runner
  serviceName: persistent-runner
  template:
    metadata:
      labels:
        app: persistent-runner
    spec:
      containers:
        - name: docker
          volumeMounts:
            - mountPath: /var/lib/docker
              name: persistent-runner-data
  volumeClaimTemplates:
    - metadata:
        name: persistent-runner-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
```

And that works to get storage:

```
> k get pod persistent-runner-k2ksm-0 -o yaml | yq eval .spec.volumes -
- name: persistent-actions-runner-data
  persistentVolumeClaim:
    claimName: persistent-runner-data-persistent-runner-k2ksm-0
```

But the StatefulSet part doesn't seem to be working, with the 2 replicas I'd expect a `-0` and a `-1` but instead end up with a new pod/pvc every time a build finishes:

```
NAME                                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistent-runner-data-persistent-runner-2dkrs-0   Bound    pvc-10e59266-c289-4e3f-ae82-c382bd8cecd3   100Gi      RWO            standard       12m
persistent-runner-data-persistent-runner-6szk8-0   Bound    pvc-c81507c9-5b0c-464b-a2df-7513ead64ac7   100Gi      RWO            standard       22s
persistent-runner-data-persistent-runner-8wrb7-0   Bound    pvc-c89051d1-6c87-4cc7-afae-dfe617c660fe   100Gi      RWO            standard       8m36s
persistent-runner-data-persistent-runner-k2ksm-0   Bound    pvc-7fa3d63c-d612-436e-8c03-8947be7e4286   100Gi      RWO            standard       6m26s
persistent-runner-data-persistent-runner-l8mr2-0   Bound    pvc-2646db7c-5ef1-443e-aa47-dd8d5f220d28   100Gi      RWO            standard       12m
```

and of course then docker layer caching won't work either.   I don't understand the point of this behaviour?  I can probably make it do what I want by being more careful with where the volumes come from, but in the end I'm still going to need the `StatefulSet` guarantee of a stable mapping from pod to volume, how do I get that in this case?

> Regardless, you seem to prefer the behavior of static/persistent runners so you shouldn't use ephemeral runners, hence my answer above.

Well, I really dislike the fact that the runner pod environment is shared between builds, but if that is the only way to get the docker caching to work I guess I'll have to live with it.  Maybe tell people to do all their builds inside containers and not the runner itself..
