### ISSUE TITLE
run as root drops capabiltiies

### ISSUE THREAD

**Issue by splitice** [actions-runner-controller/actions-runner-controller#1269]
**Describe the bug**

Trying to convert from a docker runner to kubernetes runner a priveledge job fails that previously worked.

```
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
```

I've set 
```
  env:
   - name: RUNNER_ALLOW_RUNASROOT
     value: "1"
  securityContext:
    runAsUser: 0
    fsGroup: 0
  volumes:
   - name: dev
     hostPath:
       path: /dev
       type: DirectoryOrCreate
  volumeMounts:
   - name: dev
     mountPath: /dev
```

To get this I'm using a loop device (mounting a image) for test purposes.

Does anyone have any ideas?

Perhaps `privileged` (which is not supported)? or are capabilities being dropped?
