### ISSUE TITLE
The SSL connection could not be established

### ISSUE THREAD

**Issue by mauriciodou** [actions-runner-controller/actions-runner-controller#1275]
**Describe the bug**
After installing a RunnerDeployment logs show:
```
[Fri Mar 25 23:38:13 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Using /etc/docker/daemon.json with the following content
--
Fri, Mar 25 2022 5:38:13 pm | {}
Fri, Mar 25 2022 5:38:13 pm | [Fri Mar 25 23:38:13 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Using /etc/supervisor/conf.d/dockerd.conf with the following content
Fri, Mar 25 2022 5:38:13 pm | [program:dockerd]
Fri, Mar 25 2022 5:38:13 pm | command=/usr/local/bin/dockerd
Fri, Mar 25 2022 5:38:13 pm | autostart=true
Fri, Mar 25 2022 5:38:13 pm | autorestart=true
Fri, Mar 25 2022 5:38:13 pm | stderr_logfile=/var/log/dockerd.err.log
Fri, Mar 25 2022 5:38:13 pm | stdout_logfile=/var/log/dockerd.out.log
Fri, Mar 25 2022 5:38:13 pm | [Fri Mar 25 23:38:13 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Starting supervisor
Fri, Mar 25 2022 5:38:13 pm | [Fri Mar 25 23:38:13 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Waiting for processes to be running
Fri, Mar 25 2022 5:38:13 pm | [Fri Mar 25 23:38:13 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Process dockerd is not running yet. Retrying in 1 seconds
Fri, Mar 25 2022 5:38:13 pm | [Fri Mar 25 23:38:13 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Waited 0 seconds of 30 seconds
Fri, Mar 25 2022 5:38:14 pm | [Fri Mar 25 23:38:14 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Process dockerd is not running yet. Retrying in 1 seconds
Fri, Mar 25 2022 5:38:14 pm | [Fri Mar 25 23:38:14 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Waited 1 seconds of 30 seconds
Fri, Mar 25 2022 5:38:15 pm | [Fri Mar 25 23:38:15 UTC 2022] [INFO] [/usr/local/bin/startup.sh] dockerd is running
Fri, Mar 25 2022 5:38:15 pm | Docker enabled runner detected and Docker daemon wait is enabled
Fri, Mar 25 2022 5:38:15 pm | Waiting until Docker is avaliable or the timeout is reached
Fri, Mar 25 2022 5:38:15 pm | CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
Fri, Mar 25 2022 5:38:15 pm | Github endpoint URL https://github.com/
Fri, Mar 25 2022 5:38:16 pm | Passing --ephemeral to config.sh to enable the ephemeral runner.
Fri, Mar 25 2022 5:38:16 pm | Configuring the runner.
Fri, Mar 25 2022 5:38:16 pm |  
Fri, Mar 25 2022 5:38:16 pm | --------------------------------------------------------------------------------
Fri, Mar 25 2022 5:38:16 pm | \| ____ _ _ _ _ _ _ _ _ \|
Fri, Mar 25 2022 5:38:16 pm | \| / ___(_) \|_\| \| \| \|_ _\| \|__ / \ ___\| \|_(_) ___ _ __ ___ \|
Fri, Mar 25 2022 5:38:16 pm | \| \| \| _\| \| __\| \|_\| \| \| \| \| '_ \ / _ \ / __\| __\| \|/ _ \\| '_ \/ __\| \|
Fri, Mar 25 2022 5:38:16 pm | \| \| \|_\| \| \| \|_\| _ \| \|_\| \| \|_) \| / ___ \ (__\| \|_\| \| (_) \| \| \| \__ \ \|
Fri, Mar 25 2022 5:38:16 pm | \| \____\|_\|\__\|_\| \|_\|\__,_\|_.__/ /_/ \_\___\|\__\|_\|\___/\|_\| \|_\|___/ \|
Fri, Mar 25 2022 5:38:16 pm | \| \|
Fri, Mar 25 2022 5:38:16 pm | \| Self-hosted runner registration \|
Fri, Mar 25 2022 5:38:16 pm | \| \|
Fri, Mar 25 2022 5:38:16 pm | --------------------------------------------------------------------------------
Fri, Mar 25 2022 5:38:16 pm |  
Fri, Mar 25 2022 5:38:16 pm | # Authentication
Fri, Mar 25 2022 5:38:16 pm |  
Fri, Mar 25 2022 5:38:17 pm | The SSL connection could not be established, see inner exception.
Fri, Mar 25 2022 5:38:17 pm | Configuration failed. Retrying
Fri, Mar 25 2022 5:38:18 pm | Configuring the runner.
```
and it falls into CrashLoopBackoff.

Yaml:
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
  namespace: self-hosted-runners
spec:
  template:
    spec:
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      repository: krogertechnology/kps-alcatraz-github-runners
      labels:
        - alcatraz-runner
      env:
        - name: DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER
          value: "0"
```

**Environment (please complete the following information):**
 - Controller Version: v0.22.0
 - Deployment Method: helm
 - Helm Chart Version : 0.17.0
