### ISSUE TITLE
webhook based autoscaling not working 

### ISSUE THREAD

**Issue by srvmsr** [actions-runner-controller/actions-runner-controller#1284]
**Describe the bug**
I was facing issue with gitwebhook based autoscaling , so i even updated to latest helm templates.

**To Reproduce**
Runnerdeployment
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: org-abc
  namespace: actions-abc
spec:
  template:
    spec:
      image: docker.artifactory.dhl.com/rancher-docker-dev/dpdhl-gha-runner:16ce4e54eead5b727f52acfc7bf52bc15378d267      
      organization: corporate-data-analytics
      labels:
      - abc-analytics
      - org-runner
```
HRA
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: abc-autoscaler
  namespace: actions-abc
spec:
  scaleTargetRef:
    name: org-abc
  minReplicas: 1
  maxReplicas: 5
  scaleUpTriggers:
  - githubEvent:
      push:
    amount: 1
    duration: "5m"
```
A job config 

```
jobs:
  build:
    runs-on: [ abc-analytics, org-runner ]

```
on webhook server logs i am getting below 
<html>
<body>

2022-03-29T15:35:34Z DEBUG controllers.webhookbasedautoscaler Found 0 HRAs by key {"key": "corporate-data-analytics/Invoice-Overdue-Risk"}
Tue, Mar 29 2022 5:35:34 pm | 2022-03-29T15:35:34Z DEBUG controllers.webhookbasedautoscaler Found some runner groups are managed by ARC {"event": "push", "hookID": "186568", "delivery": "dfc84770-af75-11ec-9d60-8b2cc53f0c4c", "groups": "RunnerGroup{Scope:Organization, Kind:Default, Name:}"}
Tue, Mar 29 2022 5:35:34 pm | 2022-03-29T15:35:34Z DEBUG controllers.webhookbasedautoscaler groups {"event": "push", "hookID": "186568", "delivery": "dfc84770-af75-11ec-9d60-8b2cc53f0c4c", "groups": "RunnerGroup{Scope:Organization, Kind:Default, Name:}"}
Tue, Mar 29 2022 5:35:34 pm | 2022-03-29T15:35:34Z DEBUG controllers.webhookbasedautoscaler Found 1 HRAs by key {"key": "corporate-data-analytics"}
Tue, Mar 29 2022 5:35:34 pm | 2022-03-29T15:35:34Z DEBUG controllers.webhookbasedautoscaler no repository/organizational/enterprise runner found {"event": "push", "hookID": "186568", "delivery": "dfc84770-af75-11ec-9d60-8b2cc53f0c4c", "repository": "corporate-data-analytics/Invoice-Overdue-Risk", "organization": "corporate-data-analytics", "enterprise": "dhl-it-services"}
Tue, Mar 29 2022 5:35:34 pm | 2022-03-29T15:35:34Z DEBUG controllers.webhookbasedautoscaler Scale target not found. If this is unexpected, ensure that there is exactly one repository-wide or organizational runner deployment that matches this webhook event {"event": "push", "hookID": "186568", "delivery": "dfc84770-af75-11ec-9d60-8b2cc53f0c4c"}

</body>
</html>

I am testing on github enterprise , and org hook settings are correctly configured 
Can you please help understanding why autoscaling is not working .
