### ISSUE TITLE
RunnerDeployment not correctly reacting to failed jobs

### ISSUE THREAD

**Issue by hans-m-song** [actions-runner-controller/actions-runner-controller#1325]
**Describe the bug**

After a job has failed, the runner container within a runner deployment transitions to a `Completed` state (which is fine).
However, the controller does not seem to recreate the container (sometimes for almost 10m) even with a queued job. 

Not sure if this is related but the `HorizontalRunnerAutoscaler` also never scales down runners to 0 (let me know if i should open a new issue for that)

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

1. Trigger a job (which fails)
2. Check pod status (see below for details)
3. See runner container is in `Completed` state
4. See `RunnerDeployment` incorrectly assumes the desired replicas is satisfied
5. Wait (sometimes up to 10m) for controller to recreate runner `Pod`

**Expected behavior**
Once a pod enters a `Completed` state, I expect the controller to recreate the runner immediately (or soonish).

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.18.2] - 0.22.3
 - Deployment Method [e.g. Helm and Kustomize ] - Helm
 - Helm Chart Version [e.g. 0.11.0, if applicable] - actions-runner-controller-0.17.3

**Additional context**

Running on k3s.

`HorizontalRunnerAutoscaler` and `RunnerDeployment` [here](https://github.com/hans-m-song/kube-stack/tree/master/actions-runner-system)

The `docker` container stays running

Failed `Pod` spec

```yaml
Name:         huisheng-ci-xfv84-wzdww
Namespace:    actions-runner-system
Priority:     0
Node:         deep-thought/192.168.1.250
Start Time:   Sat, 09 Apr 2022 09:26:24 +0000
Labels:       actions-runner-controller/inject-registration-token=true
              pod-template-hash=76cb54bd8
              runner-deployment-name=huisheng-ci
              runner-template-hash=6bb6947f44
              runnerset-name=huisheng-ci-xfv84-wzdww
Annotations:  actions-runner-controller/token-expires-at: 2022-04-09T20:26:24+10:00
              sync-time: 2022-04-09T09:26:24Z
Status:       Running
IP:           10.42.0.135
IPs:
  IP:           10.42.0.135
Controlled By:  Runner/huisheng-ci-xfv84-wzdww
Containers:
  runner:
    Container ID:   containerd://f8c8212b457e9ad18aa1dbc6554f8e04b5f2e30fae7179d95abd7f1b5d87e9f0
    Image:          summerwind/actions-runner:latest
    Image ID:       docker.io/summerwind/actions-runner@sha256:28197e3c5f73e741e0f725d1dab1427380ff56f347bc2430cb71fea7912f54bc
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 09 Apr 2022 09:26:27 +0000
      Finished:     Sat, 09 Apr 2022 09:27:02 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      RUNNER_ORG:
      RUNNER_REPO:                    hans-m-song/huisheng
      RUNNER_ENTERPRISE:
      RUNNER_LABELS:
      RUNNER_GROUP:
      DOCKER_ENABLED:                 true
      DOCKERD_IN_RUNNER:              false
      GITHUB_URL:                     https://github.com/
      RUNNER_WORKDIR:                 /runner/_work
      RUNNER_EPHEMERAL:               true
      DOCKER_HOST:                    tcp://localhost:2376
      DOCKER_TLS_VERIFY:              1
      DOCKER_CERT_PATH:               /certs/client
      RUNNER_FEATURE_FLAG_EPHEMERAL:  true
      RUNNER_NAME:                    huisheng-ci-xfv84-wzdww
      RUNNER_TOKEN:                   AFBDYP36I2JTKAHLPNIO4TTCKFPVA
    Mounts:
      /certs/client from certs-client (ro)
      /runner from runner (rw)
      /runner/_work from work (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vn588 (ro)
  docker:
    Container ID:   containerd://87bf20aa9220ea2ebd79aa5fd727662ef2ccc0afbeaebc30b9f0bfafd5fc01bf
    Image:          docker:dind
    Image ID:       docker.io/library/docker@sha256:e816908591767e57b84fec6b5edb483cfdae5309c2446d2164c4a5bde44f26b4
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Sat, 09 Apr 2022 09:26:27 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      DOCKER_TLS_CERTDIR:  /certs
    Mounts:
      /certs/client from certs-client (rw)
      /runner from runner (rw)
      /runner/_work from work (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vn588 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  runner:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  work:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  certs-client:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-vn588:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  5m24s  default-scheduler  Successfully assigned actions-runner-system/huisheng-ci-xfv84-wzdww to deep-thought
  Normal  Pulling    5m24s  kubelet            Pulling image "summerwind/actions-runner:latest"
  Normal  Pulled     5m22s  kubelet            Successfully pulled image "summerwind/actions-runner:latest" in 2.235812683s
  Normal  Created    5m22s  kubelet            Created container runner
  Normal  Started    5m22s  kubelet            Started container runner
  Normal  Pulled     5m22s  kubelet            Container image "docker:dind" already present on machine
  Normal  Created    5m22s  kubelet            Created container docker
  Normal  Started    5m22s  kubelet            Started container docker
```

`RunnerDeployment` spec

```yaml
Name:         huisheng-ci
Namespace:    actions-runner-system
Labels:       <none>
Annotations:  <none>
API Version:  actions.summerwind.dev/v1alpha1
Kind:         RunnerDeployment
Metadata:
  Creation Timestamp:  2022-04-09T09:26:24Z
  Generation:          1
  Managed Fields:
    API Version:  actions.summerwind.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:template:
          .:
          f:spec:
            .:
            f:repository:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-04-09T09:26:24Z
    API Version:  actions.summerwind.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:availableReplicas:
        f:desiredReplicas:
        f:readyReplicas:
        f:replicas:
        f:updatedReplicas:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2022-04-09T09:26:24Z
  Resource Version:  1500768
  UID:               54a7c129-6409-4d16-a5bc-51d371778193
Spec:
  Effective Time:  <nil>
  Selector:        <nil>
  Template:
    Metadata:
    Spec:
      Dockerd Container Resources:
      Image:
      Repository:  hans-m-song/huisheng
      Resources:
Status:
  Available Replicas:  1
  Desired Replicas:    1
  Ready Replicas:      1
  Replicas:            1
  Updated Replicas:    1
Events:                <none>
```
