### ISSUE TITLE
HRA is no longer working using TotalNumberOfQueuedAndInProgressWorkflowRuns

### ISSUE THREAD

**Issue by renperez-cpi** [actions-runner-controller/actions-runner-controller#1336]
I have actions-controller installed in our eks cluster. everything was working fine until yesterday. HRA is no longer working using TotalNumberOfQueuedAndInProgressWorkflowRuns. I have the min set to 0 and max to 5. when there is a workflow run its no longer scaling to run the self-hosted runner. please advice. below is my configurations

i've installed the controller using argocd application. 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    github-actions: controller
    owner: devops
    kubernetes: application-addons
    environment: nonprod
spec:
  project: application-addons
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    targetRevision: 0.17.3
    chart: actions-runner-controller
    helm:
      values: |
        replicaCount: 2
        syncPeriod: 1m
        enableLeaderElection: true
  destination:
    server: https://kubernetes.default.svc
    namespace: actions
  syncPolicy:
    automated: 
    syncOptions:
    - Replace=true   
    - CreateNamespace=true
  ```
Runner Deployment
```
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: nonprod-runner-autoscaler
  namespace: actions
spec:
  scaleTargetRef:
    name: nonprod-runner
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 0
  maxReplicas: 5
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - repo_name
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: nonprod-runner
  namespace: actions
spec:
  template:
    spec:
      image: container_image
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "1"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "3900Mi"
      dockerdWithinRunnerContainer: true
      repository: repo_name
      labels:
        - nonprod-runner
