### ISSUE TITLE
Introduce a `type` field for a HRA's `scaleTargetRef:`

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#1343]
When autoscaling a RunnerSet you must set `kind: RunnerSet` as part of the `scaleTargetRef:` field, this isn't needed when the HRA is backing a RunnerDeployment. It would be nicer to just always have to set the type so it's less confusing. easier to document and consistent between the 2 runner kinds.

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runner-deployment
spec:
  template:
    spec:
      repository: example/myrepo
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
    # For a RunnerSet this type: field would be set to RunnerSet
    type: RunnerDeployment  # <--------- the new field
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'
```
