### ISSUE TITLE
Horizontalrunnerautoscaler is throwing 0 for TotalNumberOfQueuedAndInProgressWorkflowRuns metric Even though there are jobs working

### ISSUE THREAD

**Issue by PJEstrada** [actions-runner-controller/actions-runner-controller#1346]
**Describe the bug**
I have a `horizontalrunnerautoscaler` deployed along with a deployment and the actions runner on my cluster.

This is my autoscaler:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: actions-autoscaler
spec:
  # Runners in the targeted RunnerDeployment won't be scaled down
  # for 5 minutes instead of the default 10 minutes now
  scaleDownDelaySecondsAfterScaleOut: 60
  scaleTargetRef:
    name: k8s-runners
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  minReplicas: 1
  maxReplicas: 40
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'
```
The problem I have is that when I deploy it, and then run a workflow (using workflow disptach) that triggers a matrix of 7 jobs. I would expect a scale to get triggered, however this is not happening.

If I check the controller logs I see this:

```
2022-04-13T21:53:31Z	DEBUG	actions-runner-controller.horizontalrunnerautoscaler	Suggested desired replicas of 0 by TotalNumberOfQueuedAndInProgressWorkflowRuns	{"workflow_runs_completed": 0, "workflow_runs_in_progress": 0, "workflow_runs_queued": 0, "workflow_runs_unknown": 0, "namespace": "actions", "kind": "runnerdeployment", "name": "k8s-runners", "horizontal_runner_autoscaler": "k8s-runners-autoscaler"}
2022-04-13T21:53:31Z	DEBUG	actions-runner-controller.horizontalrunnerautoscaler	Calculated desired replicas of 1	{"horizontalrunnerautoscaler": "actions/k8s-runners-autoscaler", "suggested": 1, "reserved": 0, "min": 1, "max": 30}
```
Note that `workflow_runs_in_progress` and `workflow_runs_queued` is 0 even while my workflow is queued on github actions.

**Checks**

- [ x ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Create an autoscaler with the above yaml.
2. Trigger a workflow dispatch that creates a 7 workflow parallel matrix
3. Check the actions runner controller job
4. Observe metrics similar to these:
```
{"workflow_runs_completed": 0, "workflow_runs_in_progress": 0, "workflow_runs_queued": 0, "workflow_runs_unknown": 0, "namespace": "actions", "kind": "runnerdeployment", "name": "k8s-runners", "horizontal_runner_autoscaler": "k8s-runners-autoscaler"}
```

**Expected behavior**
Get the right number of queued jobs on the metric for the autoscaler.

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version 0.22.1
```
2       	Wed Apr 13 15:44:04 2022	deployed  	actions-runner-controller-0.17.1	0.22.1     	Upgrade complete
```

 - Deployment Method Helm
 - Helm Chart Version [e.g. 0.11.0, if applicable]

**Additional context**
I'm running my cluster on AWS EKS with a cluster autoscaler.
