### ISSUE TITLE
The /runner Directory Shows "No space left on device"

### ISSUE THREAD

**Issue by TheDarkula** [actions-runner-controller/actions-runner-controller#1355]
Using the latest helm chart, my runners are hitting the `No space left on device` error:
```
Error: No space left on device : '/runner/_diag/pages/752fd09a-f897-4df1-ac69-ad32d94ec844_4ce08df6-71a4-5677-3e19-a8eb82872882_1.log'
```

My `RunnerDeployment` yaml file is as follows:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: themelio
spec:
  replicas: 8
  template:
    spec:
      image: summerwind/actions-runner-dind
      organization: themeliolabs
      resources:
        limits:
          cpu: "24000m"
          memory: "24Gi"
        requests:
          cpu: "2850m"
          memory: "3Gi"
```

I saw [this issue](https://github.com/actions-runner-controller/actions-runner-controller/issues/840), which led me to play around with the `spec.volumeSizeLimit` setting, but I have not been able to remedy the situation.

Does anyone have a solution for this?

Cheers :)
