### ISSUE TITLE
Configuring A Docker Image Cache (And Possibly Others)

### ISSUE THREAD

**Issue by TheDarkula** [actions-runner-controller/actions-runner-controller#1362]
Coming from [this discussion](https://github.com/actions-runner-controller/actions-runner-controller/issues/1355#issuecomment-1103390564), I currently have this:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: themelio
spec:
  replicas: 8
  image: summerwind/actions-runner-dind
  organization: themeliolabs
  selector:
    matchLabels:
      app: themelio
  serviceName: themelio
  template:
    metadata:
      labels:
        app: themelio
    spec:
      containers:
        - name: runner
          env: []
          resources:
            limits:
              cpu: "24000m"
              memory: "24Gi"
            requests:
              cpu: "2850m"
              memory: "3Gi"
        - name: docker
          volumeMounts:
            - mountPath: /var/lib/docker
              name: themelio-data
  volumeClaimTemplates:
    - metadata:
        name: themelio-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
```

The first time I ran the CI, [it succeeded](https://github.com/themeliolabs/mellis/actions/runs/2197196138).

The second time, it hit [no space left on device](https://github.com/themeliolabs/mellis/actions/runs/2197223699).

Is this a misconfiguration on my part?

**Comment by mumoshu** [comment]
@TheDarkula Hey. I don't know the details of how docker pull works but anyway, try giving your host's root volume more capacity(or the one that backs your host's /tmp). This doesn't look like an issue in ARC.

**Comment by toast-gear** [comment]
I would avoid symlinking as your limit will be the root volume, not your PV. I'd try physically moving the Docker data directory with the `-g` flag. Something like DOCKER_OPTS="-g /mnt/docker"

**Comment by TheDarkula** [comment]
@toast-gear Brilliant!
That sorted out the free space issue. The curious thing is, it does not appear to be using a cache for the docker images.
If you look [here](https://github.com/themeliolabs/mellis/runs/6116909747?check_suite_focus=true), you will see that it is still pulling the latest image:
```
Status: Downloaded newer image for ghcr.io/themeliolabs/windows-32-bit:latest
```
I ran the CI twice so the runners would already have the image downloaded, but it is not functioning properly.
The link I pasted is the second run of the `RunnerSet`.

**Comment by TheDarkula** [comment]
Could the cache issue be due to the access mode being `ReadWriteOnce`?

**Comment by TheDarkula** [comment]
I just tried it with `ReadWriteMany`, but that has not changed anything.
Each job is pulling a fresh image.

To give some more detail, this is how I have the workflow configured:
```
  mellis-create-installer-windows:
    runs-on: self-hosted

    container:
      image: ghcr.io/themeliolabs/wine:latest
```

**Comment by TheDarkula** [comment]
I did some digging through the ARC codebase, and I found [this](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/config/crd/bases/actions.summerwind.dev_runnersets.yaml#L762-L763):
```
                              imagePullPolicy:
                                description: 'Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images'
```
Given that I have my image tags set to `latest`, do I need to update the `RunnerSet` to specify `imagePullPolicy: IfNotPresent`?

**Comment by TheDarkula** [comment]
I just tried changing the workflow to specify a tag instead of using the `latest` tag, and it still always pulls.

**Comment by toast-gear** [comment]
> Could the cache issue be due to the access mode being `ReadWriteOnce`?

No, this controls if access to the moount is exclusive or not

> I did some digging through the ARC codebase, and I found [this](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/config/crd/bases/actions.summerwind.dev_runnersets.yaml#L762-L763):
> 
> ```
>                               imagePullPolicy:
>                                 description: 'Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images'
> ```
> 
> Given that I have my image tags set to `latest`, do I need to update the `RunnerSet` to specify `imagePullPolicy: IfNotPresent`?

No, this will only impact the pull policy on the node, not the runner.

Your problem will be related to docker on the runner in some way, I don't have a answer other than look in that general direction. Please do update this issue with a single comment outlinging what you've tried as you've tried it etc

**Comment by toast-gear** [comment]
>  Is that in the runner pod?

the runner pod, you can confirm in lots of ways:

- attempt to use the `container:` syntax on a runner witih Docker disabled
- setup a workflow which uses the `container:` field and then sleeps for 10 minutes, exec into the pod and see if the image is in the runner
- check to see if the image after successfully being pulled is on the eks node itself or not

I noted from a quick google that from v17.05.0 apparently the `-g` flag is deprecated and instead you are supposed the to use `--data-root` to set the directory path of the Docker persistnent data store. I doubt that will make a difference

**Comment by TheDarkula** [comment]
@toast-gear Those are all brilliant ideas.
When I have the PV/PVC issue sorted out over [here](https://github.com/actions-runner-controller/actions-runner-controller/issues/1286), I will test the docker image cache out.

**Comment by Eldarrin** [comment]
So, I've a workaround for the docker/dind/sidecar caching issue by not using the sidecar dind but using a separate one.

If you create a standard deployment for docker:18.05-dind and I would advise adding /etc/docker/daemon.json with an MTU lower than your eth (I used 1440).

Then in your deployment use a pvc, such as:

`          volumeMounts:
            - mountPath: /var/lib/docker
              name: dind-swarm
      volumes:
        - name: dind-swarm
          persistentVolumeClaim:
            claimName: dind-swarm`

Next, create a service such as:

`apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    app: dind-swarm
  name: dind-swarm
spec:
  ports:
    - name: docker
      port: 2375
      protocol: TCP
      targetPort: 2375
  selector:
    app: dind-swarm
  type: ClusterIP
`
finally, in your actual runnerdeployment add these environment variables:

`        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DOCKER_HOST
          value: tcp://dind-swarm:2375
        - name: MTU
          value: "1440"`

This means that your runner connects to a shared container in your cluster attached to a PVC that will cache your build images across runs and multiple concurrent runners.

I always have a simple script at the end of my build to cleanse it to stop polluting the pvc with too much cache (edit to suit)

`docker rmi $(docker images -aq)`

Hope what I have done can help with your issue.

Cheers, Andy

**Comment by mumoshu** [comment]
@Eldarrin Hey! Thanks for sharing. Are you basically trying to share /var/lib/docker across the clients and the server-side of your in-clulster dockerd, using a shared ReadWriteMany PV, right? (Because I think that's the only way it could work as you described

**Comment by Eldarrin** [comment]
@mumoshu Not quite. I use a single dind container with a ReadWriteOnce PVC then network the dind container. Its the same as if you use Docker on a different machine with the dockerd setup as a network exposed dockerd then connect to it from your pods on the cluster. I just moved the external dockerd machine into its own separate dind container.

**Comment by mumoshu** [comment]
@Eldarrin Thanks for clarifying! Just be extra sure, you gave up using bind mounts for docker containers run in remote dockerd, and that was fine for your use-case, right? (I think it's a fine trade-off when you don't rely on docker-runs in your job steps and you use docker only for docker builds)

**Comment by Eldarrin** [comment]
That's true, my use case is a scaling build farm and I tend to test my containers in as pods themselves in a test namespace. I'm going to try multi-running my setup and see what explodes though :)

**Comment by Eldarrin** [comment]
So I did some tests, not overly heavy. I just had 6 docker runners, each one running an action script containing a docker run command with an alpine docker counting and logging and this worked. If you can think of a special scenario to test I can try it

**Comment by Eldarrin** [comment]
Here: https://github.com/Eldarrin/ARC-DinDooD

This is my setup, this needs work to actually function but you can see the idea. look in the root dind-swarm and bases/dind-swarm

Then bases/docker and gitrunners/docker

**Comment by toast-gear** [comment]
I'm going to consider this ticket complete now we have base documentation for the new RunnerSets complete, cheers for your contributions in testing the feature!

**Comment by TheDarkula** [comment]
@toast-gear Sure thing!

**Comment by sagar-bud** [comment]
Hello Eldarrin,

I have registered the GitHub action runner on GKE cluster. I have followed the below document for docker image layer caching and it's work fine without any issue.  https://github.com/actions/actions-runner-controller/blob/master/docs/using-custom-volumes.md#docker-image-layers-caching

But if one runner pod is running at a time, it will use existing PV to store docker cache but when multiple runners(more than one or two) pods are running at same time. It will create new PV and docker cache is not available in new PV. how runner pods will use same PV. or how we can store docker cache centrally?

I have followed your suggestion https://github.com/actions/actions-runner-controller/issues/1362#issuecomment-1119528887 but it is not working properly. Can you please guide me how we can configure docker-dind with Github action runner?

**Comment by Eldarrin** [comment]
HI @sagar-bud, you don't mount the PV in the runner. You have a separate `deployment` running `docker:dind` and have a `service` point to the `docker:dind deployment`. This has a PV mount. Your runner now just need the docker client and to use an env variable of `DOCKER_HOST` pointing to the service of the `docker:dind deployment`

**Comment by sagar-bud** [comment]
Hello Eldarrin,

Thank you for your quick response.

I have already configured the docker-dind as per your https://github.com/actions/actions-runner-controller/issues/1362#issuecomment-1119528887 but not working properly.

I have attached the docker-dind deployment, service, PVC, and runner deployment YAML files. Can you please review it?

**docker-dind deployment YAML file.**
```

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-dind
  name: docker-dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-dind
  template:
    metadata:
      labels:
        app: docker-dind
    spec:
      containers:
        - image: docker:19.03-dind
          name: docker-dind
          env:
            - name: DOCKER_HOST
              value: tcp://docker-dind:2375/
            - name: DOCKER_TLS_CERTDIR #Disable TLS as traffic is not going outside of network.
              value: ""
          volumeMounts:
            - name: docker-dind-data-vol #Persisting the docker data
              mountPath: /var/lib/docker/
          ports:
            - name: daemon-port
              containerPort: 2375
              protocol: TCP
          securityContext:
            privileged: true #Required for dind container to work.
      volumes:
        - name: docker-dind-data-vol
          persistentVolumeClaim:
            claimName: docker-dind-data
```
**docker-dind service YAML file.**

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-dind
  name: docker-dind
spec:
  ports:
    - port: 2375
      protocol: TCP
      targetPort: 2375
  selector:
    app: docker-dind
```
****docker-dind PVC YAML file

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: docker-dind
  name: docker-dind-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
Github action runner YAML file

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: example
spec:
  organization: Rapid-test
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: example  # Match this label with the template labels
  serviceName: example
  template:
    metadata:
      labels:
        app: example  # Add labels to match the selector
    spec:
      containers:
      - name: runner
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
        securityContext:
          privileged: true
      - name: docker
        env:
          - name: DISABLE_RUNNER_UPDATE
            value: "true"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DOCKER_HOST
            value: tcp://docker-dind:2375/
          - name: MTU
            value: "1440"
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
```

**Comment by Eldarrin** [comment]
The deployment looks fine, do you have DOCKER_HOST set in the runner?

**Comment by sagar-bud** [comment]
Hello Eldarrin,

I have edited my pervious response. Can you please review it? Yes, I have added DOCKER_HOST in runner deployment YAML file.

**Comment by Eldarrin** [comment]
Heya,

It looks like in your RunnerSet you have 2 containers declared `docker` and `runner`. You don't need this. Just 1 container `runner` that will talk to `DOCKER_HOST`

```
spec:
      containers:
      - name: runner
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
        env:
          - name: DISABLE_RUNNER_UPDATE
            value: "true"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DOCKER_HOST
            value: tcp://docker-dind:2375/
          - name: MTU
            value: "1440"
```

Note: The runner will have the docker client executable on it

**Comment by sagar-bud** [comment]
Hello Eldarrin,

As per your suggestion, I have removed the docker container portion from the runner deployment YAML file. But when I apply the runner deployment YAML file, it will create docker and runner container both. Can you please review the below file?

Runner deployment YAML file
```

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: example
spec:
  organization: Rapid-test
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: example  # Match this label with the template labels
  serviceName: example
  template:
    metadata:
      labels:
        app: example  # Add labels to match the selector
    spec:
      containers:
      - name: runner
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
        env:
          - name: DISABLE_RUNNER_UPDATE
            value: "true"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DOCKER_HOST
            value: tcp://docker-dind:2375/
          - name: MTU
            value: "1440"
```
I think runner docker image by default create the sidecar docker container. Hence, the docker container is created. After that, i am using the image eldarrin/gitrunners/basebuild but getting "imagepullBackoff" error.

Can you please guide me or provide the runner image which you're using? 

Moreover, I have installed action-runner-controller using helm.
