### ISSUE TITLE
Delay in  allocating a  runner for a job

### ISSUE THREAD

**Issue by shankarRaman** [actions-runner-controller/actions-runner-controller#1387]
**Describe the bug**
We noticed an unusual amount of delay  (almost 1 hour) for the runners to pick the jobs in Github. Usually this happens instantly and there were a bunch  of runners in "idle" state. 
How can one troubleshoot this to find out where the root cause is?

**Checks**

- [X] My actions-runner-controller version (v0.22.2) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**Expected behavior**
I expect the runners to pick the jobs asap

**Comment by toast-gear** [comment]
ARC isn't involved in jobs acutally getting allocated to runners, all ARC is responsible for is scaling runners up and down effectively. Once the runner container is up, outside of the entrypoint, GitHub's runner software takes over. Is this a regular problem or something that only happens now and again? github.com is not reliable so perhaps you are just suffering from their API having issues?

**Comment by mumoshu** [comment]
Yeah, this is unlikely to be triggered by ARC. GitHub should assign jobs to idle runners with matching labels. As you see idle runners, ARC seems to be working correctly. Have you already contacted GitHub support?

**Comment by shankarRaman** [comment]
Thanks @toast-gear @mumoshu - that's what my suspicion was too. I assumed, since the ARC communicates with Github to determine scaling needs, that the ARC is also responsible for notifying Github about the availability of the runners.

**Comment by shankarRaman** [comment]
@mumoshu another question - how does ARC handle pods that are still running because the `minReplicas` count has be maintained? Wouldn't those hanging pods create a persistent runner scenario causing unwanted behavior (we see that with "permission denied" messages when  trying to clean up working  directory  as part of actions/checkout)

**Comment by toast-gear** [comment]
> Wouldn't those hanging pods create a persistent runner scenario causing unwanted behavior (we see that with "permission denied" messages when trying to clean up working directory as part of actions/checkout

No, when a pod finishes a job is is destroyed and created again, runners are single use so nothing is persistended between jobs unless you have actvely tuned off the ephemeral design https://github.com/actions-runner-controller/actions-runner-controller#persistent-runners

**Comment by toast-gear** [comment]
Mmmm, that doesn't sound right. Could you:

- confirm your ARC controller version? 
- send your runner*.yaml and HRA yaml?

**Comment by shankarRaman** [comment]
This is the image version 0.21.1, here's our deployment and HRA yaml
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: krogertechnology-runner-deployment
spec:
  template:
    spec:
      image: docker-prod.registry.kroger.com/tools/actions-runner-dind:v2.289.2-ubuntu-20.04-no-proxy
      imagePullPolicy: IfNotPresent
      organization: krogertechnology
      labels:
      - nonprod-region-east
      - aks
      group: AKS Non-prod
      dockerdWithinRunnerContainer: true
      dockerRegistryMirror: https://docker.registry.kroger.com/
      resources:
        limits:
          cpu: "8"
          memory: "8Gi"
        requests:
          cpu: "1"
          memory: "8Gi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: krogertechnology-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: krogertechnology-runner-deployment
  minReplicas: 10
  maxReplicas: 200
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.5'    
    scaleDownThreshold: '0.2'  
    scaleUpAdjustment: 10      
    scaleDownAdjustment: 1   
```
