### ISSUE TITLE
[HorizontalRunnerAutoscaler] Can scaler control replicas of RunnerDeployment?

### ISSUE THREAD

**Issue by RRoundTable** [actions-runner-controller/actions-runner-controller#139]
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
spec:
  template:
    spec:
      image: summerwind/actions-runner-dind
      imagePullPolicy: Always
      dockerWithinRunnerContainer: true
     organization: {organization_name}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
spec:
  scaleTargetRef: 
    name: runner-deployment
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
  - repositoryNames:
     - {private repository name}
```
This config file can't  control replicas of RunnerDeployment. 
Current kubectl version is like above

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
