### ISSUE TITLE
unknown field "workflowJob" in dev.summerwind.actions.v1alpha1.HorizontalRunnerAutoscaler.spec.scaleUpTriggers.githubEvent;

### ISSUE THREAD

**Issue by roshvin** [actions-runner-controller/actions-runner-controller#1444]
### Controller Version

0.18.0

### Helm Chart Version

actions-runner-controller-0.18.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dot-runner
spec:
  template:
    spec:
      enterprise: xxxxx
      labels:
      - dot-enterprise-runner
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      image: xxxxxx/actions-runner
      imagePullPolicy: Always
      dockerEnabled: false
      securityContext:
        runAsUser: 1000
-------------------------------

apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
   name: ent-runner-auto-scaller
spec:
  scaleDownDelaySecondsAfterScaleOut: 5
  scaleTargetRef:
    name: dot-runner
  minReplicas: 1
  maxReplicas: 300
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"
```

### To Reproduce

```markdown
after upgrading from actions-runner-controller-0.17.3 to actions-runner-controller-0.18.0 auto scaling is not working . as per https://github.com/actions-runner-controller/actions-runner-controller/blob/master/docs/releasenotes/0.23.md  i have added below change .

Change this:

  scaleUpTriggers:
  - githubEvent: {}
    duration: "30m"
To this:

  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"

and during HRA creating with above i am getting above error during the HRA deployment.

k create  -f HorizontalRunnerAutoscaler.yaml_new
error: error validating "HorizontalRunnerAutoscaler.yaml_new": error validating data: ValidationError(HorizontalRunnerAutoscaler.spec.scaleUpTriggers[0].githubEvent): unknown field "workflowJob" in dev.summerwind.actions.v1alpha1.HorizontalRunnerAutoscaler.spec.scaleUpTriggers.githubEvent; if you choose to ignore these errors, turn validation off with --validate=false
```

### Describe the bug

after upgrading from actions-runner-controller-0.17.3 to actions-runner-controller-0.18.0 auto scaling is not working . as per https://github.com/actions-runner-controller/actions-runner-controller/blob/master/docs/releasenotes/0.23.md  i have added below change .

Change this:

  scaleUpTriggers:
  - githubEvent: {}
    duration: "30m"
To this:

  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"

and during HRA creating with above i am getting above error during the HRA deployment.

k create  -f HorizontalRunnerAutoscaler.yaml_new
error: error validating "HorizontalRunnerAutoscaler.yaml_new": error validating data: ValidationError(HorizontalRunnerAutoscaler.spec.scaleUpTriggers[0].githubEvent): unknown field "workflowJob" in dev.summerwind.actions.v1alpha1.HorizontalRunnerAutoscaler.spec.scaleUpTriggers.githubEvent; if you choose to ignore these errors, turn validation off with --validate=false

### Describe the expected behavior

it should create the HRA 

### Controller Logs

```shell
2022-05-12T10:22:35Z    DEBUG   controllers.webhookbasedautoscaler      Found 1 HRAs by key     {"key": "enterprises/xxxxx"}
2022-05-12T10:22:35Z    DEBUG   controllers.webhookbasedautoscaler      Skipping this HRA as it has no `githubEvent.workflowJob` scale trigger configured       {"hra": "ent-runner-auto-scaller"}
2022-05-12T10:22:35Z    DEBUG   controllers.webhookbasedautoscaler      no repository/organizational/enterprise runner found    {"event": "workflow_job", "hookID": "4926067", "delivery": "70ba7c10-d1dd-11ec-9e65-d83d6c38ab8c", "workflowJob.status": "queued", "workflowJob.labels": ["self-hosted", "azure-runners"], "repository.name": "smyle-test-automation", "repository.owner.login": "MBLD", "repository.owner.type": "Organization", "enterprise.slug": "daimler", "action": "queued", "repository": "xxxx/xxxxxxx", "organization": "MBLD", "enterprise": "xxxxx"}
```

### Runner Pod Logs

```shell
no runner started since we are not able to deploy HRA
```
