### ISSUE TITLE
Bug `hostedtoolcache` has bad permission in container job

### ISSUE THREAD

**Issue by Gentoli** [actions-runner-controller/actions-runner-controller#1476]
### Controller Version

63be0223

### Helm Chart Version

63be0223

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: <...>
  namespace: github-runners
spec:
  volumeSizeLimit: 32Gi
  serviceName: <...>-runner
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  repository: <...>
  volumeClaimTemplates:
    - metadata:
        name: docker
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: longhorn
  template:
    metadata:
      labels:
        repo: <...>
    spec:
      containers:
        - name: docker
          resources:
            limits:
              devices.kubevirt.io/kvm: '1'
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker
      volumes:
        - emptyDir: {}
          name: tools-cache
  image: >-
    image-registry.openshift-image-registry.svc:5000/github-runners/actions-runner:latest
  replicas: 1
  ephemeral: false
  selector:
    matchLabels:
      repo: <...>
  labels:
    - <...>
status:
  availableReplicas: 1
  desiredReplicas: 1
  readyReplicas: 0
  replicas: 1
  updatedReplicas: 1
```

### To Reproduce

```markdown
1. Create a workflow with a job running a container image with a non root user
2. add a step that calls a `setup-*` action (in this case `google-github-actions/setup-gcloud@v0`)
```

### Describe the bug

The step fails with:
```
Run google-github-actions/setup-gcloud@v0
/usr/local/bin/docker exec  66ae8977d88321ec05edcfde5dfdf33afeb9956ad990d918675e47470b9dfc59 sh -c "cat /etc/*release | grep ^ID"
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /__w/_temp/ba52ea93-aaf4-4774-9008-3e710111d472 -f /__w/_temp/b2203d86-2554-450d-a60a-f3b4a5376114
Error: google-github-actions/setup-gcloud failed with: EACCES: permission denied, mkdir '/__t/gcloud'
```

### Describe the expected behavior

The step succeeds.

### Controller Logs

```shell
N/A
```

### Runner Pod Logs

```shell
N/A
```

### Additional Context

Split from https://github.com/actions-runner-controller/actions-runner-controller/issues/336

To my understanding, there are two scenarios on using the tool cache in the separate docker container setup. 
1. A job _without_ a container image: uses `/opt/hostedtoolcache` in the `runner` container.
2. A job _with_ a container image: uses  `/opt/hostedtoolcache` in the `docker` container.

I would imagen the directory should be shared between the containers, but it's unlikely it relates this issue.
This issue concerns the second case.
 
`/__t` is a bind from `/opt/hostedtoolcache` in the `docker` container, it has `root:root` owner. 
In `docker`:
```
/ # id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
/ # ls -l /opt/
total 0
drwx--x--x    4 root     root            28 May 23 21:36 containerd
drwxr-xr-x    4 root     root            32 May 23 22:24 hostedtoolcache
```
In job container:
```
docker exec -it b5cccc6b4bb3 bash
bash-5.1$ ls -l /
total 76
drwxr-xr-x.    6 builder builder   76 May 23 21:36 __e
drwxr-xr-x.    2 root    root       6 May 23 21:40 __t
drwxrwxrwx.    6 builder    1001   81 May 23 21:45 __w
...
bash-5.1$ id
uid=1000(builder) gid=1000(builder) groups=1000(builder),10(wheel),36(kvm),78(kvm78),124(kvm124),232(kvm232)
```
`builder` is the default user used by the job in the container, it does not have write permission to `/__t`.

The bind in docker inspect:
```json
{
  "Type": "bind",
  "Source": "/opt/hostedtoolcache",
  "Destination": "/__t",
  "Mode": "",
  "RW": true,
  "Propagation": "rprivate"
}
```

The `docker` container is running `docker:dind`, so I am unsure how `/opt/hostedtoolcache` is created.

**Comment by mumoshu** [comment]
@Gentoli OOT, but `storageClassName: longhorn` seems too general. AFAIK, statefulset (which powers RunnerSet) reuses existing PV as long as storageClassName matches and the volume has more capacity than requested. Imagine a case when you had two volumeClaimTemplates, one for `hostedtoolcache(just for example) and one for `/var/lib/docker`. Specifying `storageClassName: longhorn` for both vc templates may result in statefulset reusing the existing PV for `hostedtoolcache` as `/var/lib/docker`, or vice versa.

**Comment by Gentoli** [comment]
@mumoshu

If I do this:
<details>
  <summary>RunnerSet</summary>

```
...
  volumeClaimTemplates:
    - metadata:
        name: docker
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: longhorn
    - metadata:
        name: docker-2
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
...
```

</details>

It will create two PVC per pod:
```
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
docker-2-<...>-6vcvb-0   Bound    pvc-03e10343-d960-4d17-b506-1e6da3629473   1Gi        RWO            longhorn       2m54s
docker-<...>-6vcvb-0     Bound    pvc-50df009a-cc8b-4924-9818-81e809d4d085   100Gi      RWO            longhorn       2m54s
```
