### ISSUE TITLE
Cannot specify GPU limits in the runner

### ISSUE THREAD

**Issue by JCMais** [actions-runner-controller/actions-runner-controller#1483]
### Controller Version

0.23.0

### Deployment Method

Kustomize

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
    name: runner-deployment
spec:
    template:
        spec:
            repository: org/repo
            labels:
                - gke-gpu-runner
            resources:
                limits:
                    nvidia.com/gpu: 1 # requesting 1 GPU
```

### To Reproduce

```markdown
1. Have a GPU node on GKE
2. Specify the `nvidia.com/gpu` resource limit
```

### Describe the bug

The created pod does not have the GPU limit

### Describe the expected behavior

It should have the `nvidia.com/gpu` limit

### Controller Logs

```shell
https://gist.github.com/JCMais/101e494b52967b7b70ea7ba221063674
```

### Runner Pod Logs

```shell
https://gist.github.com/JCMais/101e494b52967b7b70ea7ba221063674

This also includes the generated POD yaml.
```
