### ISSUE TITLE
Runner Deployment pods in NotReady state after job completion

### ISSUE THREAD

**Issue by MattMencel** [actions-runner-controller/actions-runner-controller#1515]
### Controller Version

0.24.0

### Helm Chart Version

0.19.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
  namespace: actions-runner-system
spec:
  template:
    spec:
      image: ghcr.io/myorg/actions-runner:latest
      organization: myorg
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: runner-deployment
  minReplicas: 2
  maxReplicas: 25
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: "0.75" # The percentage of busy runners at which the number of desired runners are re-evaluated to scale up
      scaleDownThreshold: "0.3" # The percentage of busy runners at which the number of desired runners are re-evaluated to scale down
      scaleUpFactor: "1.4" # The scale up multiplier factor applied to desired count
      scaleDownFactor: "0.7" # The scale down multiplier factor applied to desired count
```

### To Reproduce

```markdown
1. Runner picks up a job from GitHub
2. Job Completes
3. Runner stays in NotReady state
```

### Describe the bug

After job completion the runners are staying in `NotReady` state.

``` sh
pod/runner-deployment-2g9rm-z2smp             1/2     NotReady   0          23m
pod/runner-deployment-2g9rm-zc2tb             2/2     Running    0          23m
pod/runner-deployment-4krwn-q6w5d             1/2     NotReady   0          34m
pod/runner-deployment-4krwn-rq6p9             1/2     NotReady   0          34m
```

### Describe the expected behavior

Runners should terminate upon completion

### Controller Logs

```shell
kubectl get pods
NAME                                      READY   STATUS     RESTARTS   AGE
actions-runner-controller-5948594-z47xb   2/2     Running    0          45m
runner-deployment-2g9rm-5cv5n             2/2     Running    0          34m
runner-deployment-2g9rm-z2smp             1/2     NotReady   0          34m
runner-deployment-2g9rm-zc2tb             2/2     Running    0          34m
runner-deployment-4krwn-q6w5d             1/2     NotReady   0          45m
runner-deployment-4krwn-rq6p9             1/2     NotReady   0          45m

https://gist.github.com/MattMencel/9ba75390146855d370fba20c8adecc86
```

### Runner Pod Logs

```shell
kubectl get pods
NAME                                      READY   STATUS     RESTARTS   AGE
actions-runner-controller-5948594-z47xb   2/2     Running    0          45m
runner-deployment-2g9rm-5cv5n             2/2     Running    0          34m
runner-deployment-2g9rm-z2smp             1/2     NotReady   0          34m
runner-deployment-2g9rm-zc2tb             2/2     Running    0          34m
runner-deployment-4krwn-q6w5d             1/2     NotReady   0          45m
runner-deployment-4krwn-rq6p9             1/2     NotReady   0          45m

https://gist.github.com/MattMencel/e8966552d0fc7fd410a8d59d131b2f88
```

### Additional Context

I upgraded to the helm chart version 0.19.0 today. I did upgrade the CRDs.
