### ISSUE TITLE
`RunnerSet` terminates pods even when they are still running jobs

### ISSUE THREAD

**Issue by danxmoran** [actions-runner-controller/actions-runner-controller#1534]
(Apologies for not using the bug template, I ran into #1533. Will attempt to recreate it)

### Controller Version
0.24.0

### Helm Chart Version
0.19.0

### CertManager Version
1.4.1

### Deployment Method
Helm

### cert-manager installation
Deploying `cert-manager` Helm chart from https://charts.jetstack.io

### Checks
- [x] Not a question / user support case
- [x] Read release notes
- [x] ARC version does support the feature
- [x] Already upgraded ARC

### Resource Definitions
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: clr-runner
  namespace: actions-runner-groups
spec:
  dockerdWithinRunnerContainer: false
  ephemeral: true
  labels:
  - clr-runner
  organization: color
  replicas: 1
  selector:
    matchLabels:
      app: clr-runner
  serviceName: clr-runner
  template:
    metadata:
      labels:
        app: clr-runner
    spec:
      containers:
      - image: 301643779712.dkr.ecr.us-east-1.amazonaws.com/color-actions-runner:master_c704c14c
        name: runner
        resources:
          limits:
            cpu: 8
            memory: 32Gi
          requests:
            cpu: 8
            memory: 32Gi
      - image: public.ecr.aws/docker/library/docker:dind
        name: docker
      securityContext:
        fsGroup: 1000
      serviceAccountName: actions-runner
      terminationGracePeriodSeconds: 1800
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: clr-runner
  namespace: actions-runner-groups
spec:
  maxReplicas: 30
  metrics:
  - scaleDownFactor: "0.7"
    scaleDownThreshold: "0.2"
    scaleUpFactor: "2.5"
    scaleUpThreshold: "0.5"
    type: PercentageRunnersBusy
  minReplicas: 1
  scaleDownDelaySecondsAfterScaleOut: 3600
  scaleTargetRef:
    kind: RunnerSet
    name: clr-runner
```

### To Reproduce
1. Wait for a job to start running on one of the pods in the `RunnerSet`
2. `kubectl -n actions-runner-groups delete pod <the-pod>`

### Describe the bug
The pod terminates immediately. The in-flight job is dropped, and appears to hang in the UI until it eventually times out (much later)

### Expected behavior
I expected `terminationGracePeriodSeconds: 1800` to prevent the pod from being forcibly shut down.

### Controller Logs
Will post in a follow-up comment
