### ISSUE TITLE
Runners that should not scale up scales up and never down again

### ISSUE THREAD

**Issue by ekarlso** [actions-runner-controller/actions-runner-controller#1602]
### Controller Version

0.24.1

### Helm Chart Version

0.19.1

### CertManager Version

1.7.1

### Deployment Method

Helm

### cert-manager installation

Helm based installation

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: default
  namespace: default
spec:
  replicas: 2
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                runner-deployment-name: default
            topologyKey: kubernetes.io/hostname
      dockerEnabled: true
      dockerdContainerResources: {}
      dockerdWithinRunnerContainer: false
      env:
      - name: ENV_LANG
        value: en_US.UTF-8
      - name: ENV_LANGUAGE
        value: en_US:en
      - name: ENV_LC_ALL
        value: en_US.UTF-8
      ephemeral: true
      group: Default
      labels:
      - dp-global
      nodeSelector:
        buildertype: small
      organization: myorg
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dp-testing
  namespace: default
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                runner-deployment-name: dp-testing
            topologyKey: kubernetes.io/hostname
      dockerEnabled: true
      dockerdContainerResources: {}
      dockerdWithinRunnerContainer: false
      env:
      - name: ENV_LANG
        value: en_US.UTF-8
      - name: ENV_LANGUAGE
        value: en_US:en
      - name: ENV_LC_ALL
        value: en_US.UTF-8
      ephemeral: true
      group: Default
      labels:
      - testing
      nodeSelector:
        buildertype: small
      organization: myorg
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: dp-testing
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 0
  scaleDownDelaySecondsAfterScaleOut: 120
  scaleTargetRef:
    kind: RunnerDeployment
    name: dp-testing
  scaleUpTriggers:
  - amount: 1
    duration: 10m
    githubEvent:
      checkRun:
        status: queued
        types:
        - created
```
```


### To Reproduce

```markdown
Setup the webhook ingress's and apply the config in Resource Definitions
```

### Describe the bug

It seems the `testing` pool scales up when there are jobs starting on the `default` pool and they should be 0 since there haven't been any jobs on it.

### Describe the expected behavior

Runners should not be scaling up if there are no events that should trigger it.

### Controller Logs

```shell
https://gist.github.com/ekarlso/1f946a6e932e2d45caaec56467e12699
```

### Runner Pod Logs

```shell
NA
```
