### ISSUE TITLE
Rationalise supported webhook events to just `workflow_job` removing `check_run`, `pull_request` and `push` events

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#1607]
Currently ARC supports the following webhook events:

1. workflow_job
2. check_run
3. pull_request
4. push

Events 2 - 4 were introduced before the `workflow_job` event was created by GitHub and added to ARC. The ARC maintainers believe that there is no really need at a technical level any event type other than `workflow_job` for the ARC project nor is there any community demand for any other event types.

We are planning on **removing support** for all events other than `workflow_job`.

If you have a legitimate use case used in the world today for the other event types please do comment on this issue.

Currently having these unneeded events results in end user confusion and additional support overhead for the maintainers.

**Note** we are to keep the contract
```yaml
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"
```

**Comment by mumoshu** [comment]
@raunyoliveira-hotmart Do you really need to restrict a `workflow_job` event trigger scaling only on a specific repository?

To be clear, a `repository` runner is by definition tied to a specific repository and I thought ARC is able to scale the repository-specific runners on a `workflow_job` event just fine without explicit additional filters, as ARC already reads the repository contained within the `workflow_job` event and match that to an appropriate HorizontalRunnerAutoscaler+RunnerDeployment of the said repository.

**Comment by raunyoliveira-hotmart** [comment]
hey @mumoshu, thanks for answering!

just to make sure I understood correct, instead of having the `HorizontalRunnerAutoscaler` being restrict by specific repositories:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: <name>
spec:
  minReplicas: <min>
  maxReplicas: <max>
  scaleTargetRef:
    name: <targetref>
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
        repositories:
        - Org/repo1
        - Org/repo2
    amount: 1
```

I should configure an HRA and a RunnerDeployment in the following way:

```
kind: HorizontalRunnerAutoscaler
metadata:
  name: <name>
spec:
  minReplicas: <min>
  maxReplicas: <max>
  scaleTargetRef:
    name: <targetref>
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"
```

and on the `RunnerDeployment` I filter by the repository:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
spec:
  replicas: 1
  template:
    spec:
      repository: <repository>
```

is that correct?

thank you!
