### ISSUE TITLE
Docker caching is gone when cancelling CI

### ISSUE THREAD

**Issue by bangnh1** [actions-runner-controller/actions-runner-controller#1626]
### Controller Version

0.25.1

### Helm Chart Version

0.20.1

### CertManager Version

1.8.2

### Deployment Method

Helm

### cert-manager installation

helm repo update
helm install  \ 
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.8.2 

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: large-runnerset
spec:
  replicas: 1
  ephemeral: true
  repository: bangnh1/playground
  labels:
    - custom-runner
    - large-runnerset
  selector:
    matchLabels:
      app:  large-runnerset
  serviceName:  large-runnerset
  template:
    metadata:
      labels:
        app: large-runnerset
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: runner
        env:
        - name: GOMODCACHE
          value: "/home/runner/.cache/go-mod"
        volumeMounts:
        - name: cache
          mountPath: "/home/runner/.cache"
      - name: docker
        volumeMounts:
        - name: var-lib-docker
          mountPath: /var/lib/docker
  volumeClaimTemplates:
  - metadata:
      name: var-lib-docker
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  - metadata:
      name: cache
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: large-runnerset-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: large-runnerset
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '1'
    scaleDownFactor: '0.5'
  scheduledOverrides:
  - startTime: "2021-07-01T20:00:00+07:00"
    endTime: "2021-07-02T07:00:00+07:00"
    recurrenceRule:
      frequency: Daily
    minReplicas: 0
```

### To Reproduce

```markdown
1. Run CI with docker pull images to local

      - run: |
          docker pull ubuntu:latest
```
2. Create new CI and cancel this CI
3. A runner will start and docker caching is gone
```


### Describe the bug

docker caching is gone when canceling CI

### Describe the expected behavior

docker caching remains when canceling CI

### Controller Logs

```shell
https://gist.github.com/bangnh1/1cbec07ff0380201868dc66fa514f0ab
```

### Runner Pod Logs

```shell
https://gist.github.com/bangnh1/236d8a45e47b40273b601c41592451a8
```
