### ISSUE TITLE
Stale RunnerReplicasets are not deleted after updating the spec of RunnerDeployment

### ISSUE THREAD

**Issue by aylei** [actions-runner-controller/actions-runner-controller#1642]
### Controller Version

0.25.1

### Helm Chart Version

0.20.1

### CertManager Version

v1.8.2

### Deployment Method

Helm

### cert-manager installation

Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arm64-runner
  namespace: cicd
spec:
  effectiveTime: "2022-07-13T05:23:36Z"
  replicas: 0
  selector: null
  template:
    metadata: {}
    spec:
      dockerdContainerResources: {}
      image: ""
      labels:
      - arm64-runner
      - eks
      nodeSelector:
        beta.kubernetes.io/arch: arm64
      organization: matrixorigin
      resources:
        limits:
          cpu: "2"
          memory: 7Gi
        requests:
          cpu: "1"
          memory: 2Gi
      serviceAccountName: cicd
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runner-arm64
  namespace: cicd
spec:
  capacityReservations:
  - effectiveTime: "2022-07-13T05:23:24Z"
    expirationTime: "2022-07-13T05:28:24Z"
    replicas: 1
  - effectiveTime: "2022-07-13T05:23:36Z"
    expirationTime: "2022-07-13T05:28:36Z"
    replicas: 1
  maxReplicas: 12
  minReplicas: 0
  scaleTargetRef:
    name: arm64-runner
  scaleUpTriggers:
  - amount: 1
    duration: 5m0s
    githubEvent:
      checkRun:
        status: queued
        types:
        - created
```

### To Reproduce

```markdown
1. Create an `RunnerDeployment`
2. Trigger scale-out via github event
3. Update the `RunnerDeployment`
4. The old replicaset would not be removed nor managed
```

### Describe the bug

Old `RunnerReplicaset` is not deleted after updating the spec of `RunnerDeployment`.

### Describe the expected behavior

After updating the spec of `RunnerDeployment`, the old `RunnerReplicaSet` should be removed once the workflows they were running are done.

### Controller Logs

```shell
> kg rdeploy
NAME           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
arm64-runner   0         0         0            0           19h
> kg runnerreplicaset
NAME                 DESIRED   CURRENT   READY   AGE
arm64-runner-22qdt   0         0         0       149m
arm64-runner-brc5c   1         1         1       18h
arm64-runner-dxsbr   2         2         2       4h46m
> k logs -f arc-actions-runner-controller-7777659cb4-hp8zr  | grep arm64-runner-dxsbr
(no logs about the stale RunnerReplicaSet)
```

### Runner Pod Logs

```shell
N/A
```
