### ISSUE TITLE
Unlimited number of runner pods

### ISSUE THREAD

**Issue by pbaracska** [actions-runner-controller/actions-runner-controller#1646]
### Controller Version

0.25.1

### Helm Chart Version

0.20.1

### CertManager Version

1.8.0

### Deployment Method

Helm

### cert-manager installation

Cert manager was installed from the official source.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment-gbu-iac
  namespace: self-hosted-runners
spec:
  effectiveTime: null
  replicas: 2
  selector: null
  template:
    metadata: {}
    spec:
      dockerdContainerResources: {}
      image: ""
      labels:
      - gbu-iac-runner
      repository: ****
      resources: {}
      serviceAccountName: cluster-admin
```

### To Reproduce

```markdown
1. Deploy ARC
2. Deploy RunnerDeployment
```

### Describe the bug

RunnerDeployment replicas are not respected, new runners are being created continuously. 
`NAME                        DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
runner-deployment-gbu-iac   2         6         6            2           85m`

There should be only 2 replicas, but ARC creates new ones with this message:
`2022-07-13T17:03:15Z    INFO    actions-runner-controller.runnerreplicaset      Runner failed to register itself to GitHub in timely manner. Recreating the pod to see if it resolves the issue. CAUTION: If you see this a lot, you should investigate the root cause. See https://github.com/actions-runner-controller/actions-runner-controller/issues/288 {"runnerreplicaset": "self-hosted-runners/runner-deployment-gbu-iac-2x2dz", "owner": "self-hosted-runners/runner-deployment-gbu-iac-2x2dz-grwq5", "creationTimestamp": "2022-07-13 16:21:30 +0000 UTC", "readyTransitionTime": "2022-07-13 16:21:32 +0000 UTC", "configuredRegistrationTimeout": "10m0s"}`

### Describe the expected behavior

Controller should respect the desired replicas and shouldn't create more runners.

### Controller Logs

```shell
https://gist.github.com/pbaracska/81a9415bb7e8cd7b827748d09a57ff38
```

### Runner Pod Logs

```shell
https://gist.github.com/pbaracska/81a9415bb7e8cd7b827748d09a57ff38
```
