### ISSUE TITLE
Multi-tenancy secret values are not working because of base64 decoding

### ISSUE THREAD

**Issue by oreonl** [actions-runner-controller/actions-runner-controller#1684]
### Controller Version

79a494b2aaf11fcc95008dbdb54afb0efa664cd6

### Helm Chart Version

0.20.2

### CertManager Version

1.8.0

### Deployment Method

ArgoCD

### cert-manager installation

Installed using cert-manager helm chart from https://charts.jetstack.io 

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: xxxxxx
  namespace: actions-runner-system
spec:
  replicas: 1
  selector: null
  template:
    metadata: {}
    spec:
      dockerdContainerResources: {}
      githubAPICredentialsFrom:
        secretRef:
          name: xxxxxxx-github-secret
      image: ""
      labels:
      - self-hosted
      - linux
      - ubuntu-latest
      organization: xxxxxxx
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: xxxxxxx-hra
  namespace: actions-runner-system
spec:
  capacityReservations:
  - effectiveTime: "2022-08-01T22:40:20Z"
    expirationTime: "2022-08-01T23:10:20Z"
    replicas: 1
  githubAPICredentialsFrom:
    secretRef:
      name: xxxxxxx-github-secret
  maxReplicas: 10
  minReplicas: 0
  scaleTargetRef:
    name: xxxxxxx
  scaleUpTriggers:
  - duration: 30m0s
    githubEvent:
      workflowJob: {}
```

### To Reproduce

```markdown
1. Deploy with canary docker image
2. Create secret with github app auth
3. Set hra and RunnerDeployment to use secretRef
```

### Describe the bug

Get error in the controller logs and runners are not created

```2022-08-01T22:51:51Z ERROR Reconciler error {"controller": "horizontalrunnerautoscaler-controller", "controllerGroup": "actions.summerwind.dev", "controllerKind": "HorizontalRunnerAutoscaler", "horizontalRunnerAutoscaler": {"name":"xxxxxxx","namespace":"actions-runner-system"}, "namespace": "actions-runner-system", "name": "xxxxxxx", "reconcileID": "2c994235-92be-40f9-bc42-4f0ada10247c", "error": "strconv.ParseInt: parsing \"\\xdbm\\xf8\\xd3\": invalid syntax"}```

The controller is trying to base64 decode the secret values even though they are already being returned unencoded.

I created a PR to address  #168

### Describe the expected behavior

The controller is able to get string values from the secret and use them

### Controller Logs

```shell
[log](https://gist.github.com/oreonl/2882abed7ad35fdef39cca049a60f597)
```

### Runner Pod Logs

```shell
Runners are not created
```
