### ISSUE TITLE
Multitenancy: New RunnerDeployment not using "githubEnterpriseServerURL" value

### ISSUE THREAD

**Issue by Jalmeida1994** [actions-runner-controller/actions-runner-controller#1714]
### Controller Version

canary

### Helm Chart Version

0.20.2 (main branch)

### CertManager Version

1.9

### Deployment Method

Helm

### cert-manager installation

Followed every procedure.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
---
# Source: secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: organization-github-app-secret  
  namespace: organization
data:
  github_app_id: ***
  github_app_installation_id: ***
  github_app_private_key: ***
---
# Source: hra.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: organization-autoscaler
  namespace: organization
spec:
  githubAPICredentialsFrom:
    secretRef: 
      name: organization-github-app-secret
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: organization-runners
  minReplicas: 0
  maxReplicas: 5
  scaleUpTriggers:
  - githubEvent: {}
    amount: 1
    duration: 30m
---
# Source: runner_deployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: organization-runners
  namespace: organization
spec:
  template:
    metadata:
    spec:
      githubAPICredentialsFrom:
        secretRef: 
          name: organization-github-app-secret 
      ephemeral: true
      labels:
        - organization-runners
      organization: organization
      containers:
        - name: runner
          imagePullPolicy: IfNotPresent
```

### To Reproduce

```markdown
1. Install actions-runner-controller chart from ´main´ branch with controller tag set to 'canary'. Added a default auth secret "controller-manager" to it;
2. Deploy RunnerDeployment, HRA and Secret with App Auth in new namespace;
3. Runner can't register with GitHub Enterprise Server.
```

### Describe the bug

New `RunnerDeployment` can't register with GitHub Enterprise Server when using a new Secret for `githubAPICredentialsFrom` (multi tenancy) with a different GitHub Auth. Controller outputs:

```shell
2022-08-12T09:18:59Z	ERROR	actions-runner-controller.runner	Failed to get new registration token	{"runner": "organization-runners-dxs7p-2qnz6", "error": "failed to create registration token: Post \"https://api.github.com/orgs/organization/actions/runners/registration-token\": could not refresh installation id ***'s token: received non 2xx response status \"401 Unauthorized\" when fetching https://api.github.com/app/installations/***/access_tokens"}
```

From what I'm seeing it doesn't seem to be using the `githubEnterpriseServerURL` specified in the controller to authenticate, and yes the Cloud one: **https://api.github.com/** instead of **https://HOSTNAME/api/v3/**.

However if I deploy a `RunnerDeployment` in the same namespace as the controller and without the `githubAPICredentialsFrom` (using the default "controller-manager" secret) it uses the correct `githubEnterpriseServerURL`.

### Describe the expected behavior

To register successfully with GitHub Enterprise Server by using the correct URL specified in the controller key `githubEnterpriseServerURL`.

### Controller Logs

```shell
https://gist.github.com/Jalmeida1994/448c18fb6fa99c69e0e9fae68e0d47de
```

### Runner Pod Logs

```shell
N/A
```

### Additional Context

Well I hope this time I found a real issue and not just me being dumb ahah. 

Cheers!
