### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by skysbsb** [actions-runner-controller/actions-runner-controller#1754]
### Controller Version

0.25.2

### Helm Chart Version

0.20.2

### CertManager Version

v1.3.1

### Deployment Method

Helm

### cert-manager installation

Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gh-ci-runner-25g-5vcpu
  namespace: github
spec:
  replicas: 0
  template:
    spec:
      env:
      - name: DISABLE_RUNNER_UPDATE
        value: "true"
      imagePullPolicy: IfNotPresent
      image: 511690385103.dkr.ecr.us-east-2.amazonaws.com/avantstay-github-runner:12
      labels:
      - runner-25g-5vcpu
      nodeSelector:
        instancetype: spot
      organization: avantstay
      serviceAccountName: gh-ci-actions-runner-controller
      containers:
      - name: runner
        resources:
          limits:
            cpu: "6.0"
            memory: "25Gi"
          requests:
            cpu: "5.0"
            memory: "25Gi"
      - name: docker
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: gh-ci-runner-25g-5vcpu
  namespace: github
spec:
  maxReplicas: 7
  minReplicas: 0
  scaleDownDelaySecondsAfterScaleOut: 0
  scaleTargetRef:
    name: gh-ci-runner-25g-5vcpu
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "2h"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gh-ci-runner-1g-200mvcpu
  namespace: github
spec:
  replicas: 0
  template:
    spec:
      env:
      - name: DISABLE_RUNNER_UPDATE
        value: "true"
      imagePullPolicy: IfNotPresent
      image: 511690385103.dkr.ecr.us-east-2.amazonaws.com/avantstay-github-runner:12
      labels:
      - runner-1g-200mvcpu
      nodeSelector:
        instancetype: spot
      organization: avantstay
      serviceAccountName: gh-ci-actions-runner-controller
      containers:
      - name: runner
        resources:
          limits:
            cpu: "1"
            memory: "4Gi"
          requests:
            cpu: "200m"
            memory: "1Gi"
      - name: docker
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: gh-ci-runner-1g-200mvcpu
  namespace: github
spec:
  maxReplicas: 50
  minReplicas: 0
  scaleDownDelaySecondsAfterScaleOut: 0
  scaleTargetRef:
    name: gh-ci-runner-1g-200mvcpu
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "2h"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gh-ci-runner-without-limit
  namespace: github
spec:
  replicas: 0
  template:
    spec:
      env:
      - name: DISABLE_RUNNER_UPDATE
        value: "true"
      imagePullPolicy: IfNotPresent
      image: 511690385103.dkr.ecr.us-east-2.amazonaws.com/avantstay-github-runner:12
      labels:
      - runner-without-limit
      nodeSelector:
        instancetype: spot
      organization: avantstay
      serviceAccountName: gh-ci-actions-runner-controller
      containers:
      - name: runner
      - name: docker
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: gh-ci-runner-without-limit
  namespace: github
spec:
  maxReplicas: 30
  minReplicas: 0
  scaleDownDelaySecondsAfterScaleOut: 0
  scaleTargetRef:
    name: gh-ci-runner-without-limit
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "2h"
```

### To Reproduce

```markdown
Go to Github Project Action Page -> All workflows -> Select the workflow -> Cancel run
```

### Describe the bug

I can't stop the runner through the github page, by clicking 'cancel run'.

### Describe the expected behavior

I expected to see the controller-webhook receiving the cancel event for the selected workflow and the assigned pod being deleted/stopped.

### Controller Logs

```shell
controller log - https://gist.github.com/skysbsb/bec313ae1e668e3612e5767daa38a35b 
webhook - https://gist.github.com/skysbsb/ef5c6562475b86a7e9d4334476a4c08d
```

### Runner Pod Logs

```shell
runner - https://gist.github.com/skysbsb/8eb5328ec83bfaeb20dd8caa39dcaaa2
docker - https://gist.github.com/skysbsb/70882de2fb0957329321dc77d8ddfbb8
```

### Additional Context

![image](https://user-images.githubusercontent.com/37450297/186922843-0d5a76fb-6a9b-40d0-8349-b74b4eab200c.png)
