### ISSUE TITLE
Multi-tenancy doesn't work with Github Apps with no explicit Enterprise URL defined. 

### ISSUE THREAD

**Issue by bm1216** [actions-runner-controller/actions-runner-controller#1764]
### Controller Version

623c84f

### Helm Chart Version

0.20.2

### CertManager Version

1.2.0

### Deployment Method

Helm

### cert-manager installation

We have installed cert-manager from an official helm chart. Anyhow, certificates aren't really the issue here. 

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sre-controller
  namespace: nolimits
data:
  github_app_id: ***
  github_app_installation_id: ***
  github_app_private_key: ***
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: sre-runner
  namespace: nolimits
spec:
  template:
    spec:
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      organization: XXX
      labels:
        - k8s
      githubAPICredentialsFrom:
        secretRef:
          name: sre-controller
```

### To Reproduce

```markdown
1. Create a k8s secret containing the Github App data. Ensure that this secret is different from the one being used as the `controller-manager` secret.
2. Create a runnerdeployment and reference the secret using the `GithubAPICredentialsFrom` field.
```

### Describe the bug

The controller is not able to spawn runner pods for `RunnerDeployment` Objects (as well as HRAs) with `GithubAPICredentialsFrom` defined. 

It fails due to the error defined here:  https://gist.github.com/bm1216/090d015d1fee081857e5f6add01ce936.

 This doesn't seem to be a problem with the provided app credentials, as copying and renaming the `controller-manager` secret and providing it via `GithubAPICredentialsFrom` also leads to the same error. I can see that its picking up the  secret in the `GitHubAPICredentialsFrom` field as the installation id in the logs matches the secret. 

Upon further investigation, the issue seems to be with the URL its using. its using a `https://github.com/api/v3` URL as opposed to using `https://api.github.com` for the token calls. This is odd, considering I haven't describe an enterprise URL at any point during the setup

### Describe the expected behavior

The controller should be able to spawn runner pods based on the Custom Resource provided. 

### Controller Logs

```shell
https://gist.github.com/bm1216/090d015d1fee081857e5f6add01ce936
```

### Runner Pod Logs

```shell
The runner pod is not able to spawn.
```

### Additional Context

I understand that the Multi-tenancy feature isn't officially released yet. However, we really like the feature and are looking forward to using it ASAP. Following this comment - https://github.com/actions-runner-controller/actions-runner-controller/pull/1371#issuecomment-1210057401, I tried to use the latest image and ran into this issue. Any help would be appreciated. I'm thinking there might be a difference between the default client created by the controller and the client created using the GithubAPICredentialsRef secret.

Thanks for all the work you are doing - we really appreciate it.
