### ISSUE TITLE
Add support for ImagePullSecrets in custom image

### ISSUE THREAD

**Issue by tommymalmqvist** [actions-runner-controller/actions-runner-controller#1786]
**Is your feature request related to a problem? Please describe.**

When using a custom image in my RunnerDeployment I'm not able to use my private repos since there is no support for ImagePullSecret in the CRD

**Describe the solution you'd like**

I want to use a private repo where I have my custom runner image. My image needs terraform, terragrunt and helm installed as well as some custom terraform providers.

**Describe alternatives you've considered**

I have considered installing these dependencies in the workflow itself but it is slow and sometimes there are outtages and I cannot retrieve my dependencies.

**Additional context**
Nothing

**Comment by tommymalmqvist** [comment]
Found ImagePullSecret from a colleague

**Comment by vyas-n** [comment]
Hi @tommymalmqvist,

I have the same question now, what did you do to have ImagePullSecret defined for your RunnerDeployment?

**Comment by tommymalmqvist** [comment]
https://github.com/actions-runner-controller/actions-runner-controller/blob/5298c6ea298152d7b6422f3c75e83ed9ea019572/charts/actions-runner-controller/crds/actions.summerwind.dev_runnerdeployments.yaml#L2452

> Hi @tommymalmqvist,
> 
> I have the same question now, what did you do to have ImagePullSecret defined for your RunnerDeployment?

https://github.com/actions-runner-controller/actions-runner-controller/blob/5298c6ea298152d7b6422f3c75e83ed9ea019572/charts/actions-runner-controller/crds/actions.summerwind.dev_runnerdeployments.yaml#L2452

**Comment by tommymalmqvist** [comment]
Example code

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-controller-deployment
  namespace: actions-runner-controller
spec:
  template:
    spec:
      repository: demo-company/arc-runner
      image: demo-company.jfrog.io/actions-runner-controller:dev
      resources:
        requests:
          cpu: '1'
          memory: 2560Mi
      imagePullSecrets:
        - name: artifactory-pull-secret
      labels:
        - actions-runner-controller-dev
```
