### ISSUE TITLE
Github Webhooks EOF

### ISSUE THREAD

**Issue by AradZilberberg** [actions-runner-controller/actions-runner-controller#1788]
### Controller Version

0.20.2

### Helm Chart Version

0.25.2

### CertManager Version

v1.9.1

### Deployment Method

Helm

### cert-manager installation

yes
yes

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: go-runner-deployment
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: runner-deployment-name
                operator: In
                values:
                - python-runner-deployment
            topologyKey: kubernetes.io/hostname
            namespaceSelector: {}
      nodeSelector:
        "eks.amazonaws.com/nodegroup": '***************************'
      image: *********************************
      imagePullPolicy: Always
      organization: ***********
      labels:
        - go
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: go-runner-deployment-autoscaler
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: go-runner-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'
```

### To Reproduce

```markdown
described below -
```

### Describe the bug

Installed cert-manager on eks cluster
Installed the actions-runner-controller on the same eks with the following command:

`helm upgrade --install -f custom-values.yaml --create-namespace --wait --namespace actions-runner-system actions-runner-controller actions-runner-controller/actions-runner-controller --set "githubWebhookServer.enabled=true,service.type=NodePort,githubWebhookServer.ports[0].nodePort=33080"`

In custom values I have - 
```
nodeSelector:
  "eks.amazonaws.com/nodegroup": '********'
authSecret:
  github_token: ***********
  create: true
```

Created new alb -

```
apiVersion: v1
kind: Service
metadata:
  name: webhook-lb
  namespace: actions-runner-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/ip-address-type: dualstack
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: actions-runner-controller-github-webhook-server
```

Entered the enterprise github settings, created new webhook trigger
entered my URL (https://************.com/actions-runner-controller-github-webhook-server)
selected trigger only for push.

And created the webhook.

Now I'm getting an error from the github "We couldn’t deliver this payload: EOF" 
Any idea why this happens or how I can fix it?

### Describe the expected behavior

excepted behavior =  webhooks should reach the alb and from the alb pass to the pods

### Controller Logs

```shell
No logs related
```

### Runner Pod Logs

```shell
no logs related
```
