### ISSUE TITLE
Webhook server fails to parse webhook and returns 500's

### ISSUE THREAD

**Issue by doncorsean** [actions-runner-controller/actions-runner-controller#1789]
### Controller Version

0.20.2

### Helm Chart Version

0.25.2

### CertManager Version

v1.8.0

### Deployment Method

ArgoCD

### cert-manager installation

yes issue is not cert manager

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name:  <runner name>
spec:
  template:
    spec:
      enterprise: <enterprise name>
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name:  <runner name>
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: RunnerDeployment
    name:  <runner name>
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"
```

### To Reproduce

```markdown
Trigger webhook test
```

### Describe the bug

Webhook calls to the webhook server are returning 500's

### Describe the expected behavior

Webhoook completes successfully (not a 500)

### Controller Logs

```shell
N/A
```

### Runner Pod Logs

```shell
N/A
```

### Additional Context

2022-09-08T18:06:20Z	INFO	controllers.webhookbasedautoscaler	unknown event type	{"event": "workflow_run", "hookID": "", "delivery": "", "eventType": "workflow_run"}
2022-09-08T18:13:07Z	ERROR	controllers.webhookbasedautoscaler	could not parse webhook	{"webhookType": "workflow_run", "payload": "payload=%7B%22action%22%3A%22requested%22%2C%22workflow_run...
