### ISSUE TITLE
Multitenancy: githubAPICredentialsFrom not set on Runner

### ISSUE THREAD

**Issue by zbenamram** [actions-runner-controller/actions-runner-controller#1793]
### Controller Version

e233f7ad6adb2894a6cc2d951f2016e41586334b

### Deployment Method

Other

### cert-manager installation

I have followed the installation steps and successfully installed cert manager

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Var "deploymentName" }}
spec:
  replicas: {{ .Var "numReplicas" }}
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: {{ .Var "runnerRole" }}
      labels:
        deployment: {{ .Var "deploymentName" }}
    spec:
      githubAPICredentialsFrom:
        secretRef:
          name: {{ .Var "kubeSecretKeyRefName" }}
      organization: {{ .Var "organizationName" }}
      repository: {{ .Var "repositoryName" }}
      imagePullSecrets: {{- "\n" }}{{ indent_spaces 8 (to_yaml (.Var "pullSecrets")) }}
      labels: {{- "\n" }}{{ indent_spaces 8 (to_yaml (.Var "labels")) }}
      serviceAccountName: {{.Var "serviceAccountName" }}
      securityContext:
        # number doesnt really matter - It just needs to be set to a non-zero int
        fsGroup: 1337
      resources: {{- "\n" }}{{ indent_spaces 8 (to_yaml (.Var "resources")) }}
---
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ .Var "hpaName" }}
spec:
  githubAPICredentialsFrom:
    secretRef:
      name: {{ .Var "kubeSecretKeyRefName"}}
  scaleTargetRef:
    name: {{ .Var "deploymentName" }}
  minReplicas: {{ .Var "numReplicas" }}
  maxReplicas: {{ .Var "maxReplicas" }}
  scaleDownDelaySecondsAfterScaleOut: 400
  metrics:
    # scaleup and scaledown thresholds are the percentage of busy runners at which the number of desired runners are re-evaluated
    # scaleup and scaledown factors are the multiplicative factor applied to the current number of runners used to calculate the number of desired runners
    #
    # The values below have been chosen based off the default number of pods to be run in sandbox and in tools - 10. When more than 75% of the runners
    # are busy, scaleup will take effect up until max replicas is reached. When less than 30% of the runners are busy, scale down will take effect until min replicas.
    # These numbers should be adjusted if the number of queued jobs remains high in periods of high utilization or the default number of replicas has changed.
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.3'
      scaleUpFactor: '1.4'
      scaleDownFactor: '0.7'
```

### To Reproduce

```markdown
1. Install 2 different github apps one for each organization with appropriate permissions
2. create 2 separate kube secrets for each github app client installation secrets
3. create 2 RunnerDeployment specs for each unique organization with reference to the associated github app for each org
4. set primary github app credentials on the actions-runner-controller deployment spec (not sure why we still need to do this if we are doing it per RunnerDeployment spec)
5. deploy
```

### Describe the bug

Current master branch when using multitenancy feature fails with:
https://github.com/actions-runner-controller/actions-runner-controller/blob/master/controllers/runner_controller.go#L419

Looks like the githubAPICredentialsFrom field is not set on the Runner resource on creation. 

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  annotations:
    sync-time: "2022-09-09T01:26:27Z"
  creationTimestamp: "2022-09-09T01:26:27Z"
  finalizers:
  - runner.actions.summerwind.dev
  generateName: <>
  generation: 1
  labels:
    deployment: <>
    runner-deployment-name: <>
    runner-template-hash: 654fd64cf8
  name: test-runner-deployment-xyz
  namespace: actions-runner-system
  ownerReferences:
  - apiVersion: actions.summerwind.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: RunnerReplicaSet
    name: test-runner-deployment-xyz
    uid: 21e4fc28-f6e2-4cc5-865f-acf17c2d020c
  resourceVersion: "488224365"
  uid: b3cfe4c6-85d3-41cd-9d8f-7e9183077c38
spec:
  dockerdContainerResources: {}
  env: {}
  image: ""
  labels:
  - test
  organization: actions
  resources: {}
  securityContext:
    fsGroup: 1337
```
githubAPICredentialsFrom field has to be set on Runner resource for github client initialization to work here:
https://github.com/actions-runner-controller/actions-runner-controller/blob/master/controllers/runner_controller.go#L407

### Describe the expected behavior

Multitenancy feature to successfully get registration token from GitHub

### Controller Logs

```shell
2022-09-09T04:12:05Z	ERROR	actions-runner-controller.runner	Failed to get new registration token	{"runner": "test-actions-actions-org-runner-deployment-8tq6g-smwkp", "error": "failed to create registration token: POST https://git.enterprise.com/api/v3/orgs/actions/actions/runners/registration-token: 403 Resource not accessible by integration []"}
github.com/actions-runner-controller/actions-runner-controller/controllers.(*RunnerReconciler).processRunnerCreation
	/workspace/controllers/runner_controller.go:255
github.com/actions-runner-controller/actions-runner-controller/controllers.(*RunnerReconciler).Reconcile
	/workspace/controllers/runner_controller.go:136
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
```

### Runner Pod Logs

```shell
N/A
```
