### ISSUE TITLE
Critical and high CVE Vulnerabilities in actions-runner image

### ISSUE THREAD

**Issue by rpall08** [actions-runner-controller/actions-runner-controller#1800]
### Controller Version

summerwind/actions-runner-controller:latest

### Helm Chart Version

v3.9.0

### Deployment Method

Helm

### cert-manager installation

Did use self signed cert for actions-controller deployment.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
# runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
#kind: Runner
metadata:
  name: organization-runner
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: runner
        securityContext:
          privileged: true
      # image: CUSTOME IMAGE HERE
      imagePullPolicy: IfNotPresent
      organization: Organization
      group: Default
      labels:
        - k8s-runner
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: gha-runner-deployment-autoscaler
spec:
  # Runners in the targeted RunnerDeployment won't be scaled down
  # for 5 minutes instead of the default 10 minutes now
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: gha-runner
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'    # The percentage of busy runners at which the number of desired runners are re-evaluated to scale up
    scaleDownThreshold: '0.3'   # The percentage of busy runners at which the number of desired runners are re-evaluated to scale down
    scaleUpFactor: '1.4'        # The scale up multiplier factor applied to desired count
    scaleDownFactor: '0.7'      # The scale down multiplier factor applied to desired count
```

### To Reproduce

```markdown
Container security vulnerability tool Twistlock reported critical and high vulnerabilities in  summerwind/actions-runner:latest
```

### Describe the bug

Twistlock (Container Security Scanning) reporting below vulnerabilities in summerwind/actions-runner:latest

Docker hub Image url:
https://hub.docker.com/layers/summerwind/actions-runner/latest/images/sha256-7336329f31b9b597f9a481e57aef0b33d53951709959b5b815252a067dc304a8?context=explore

OS/ARCH is Linux/amd64

Sample Vulnerabilities report:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/rpall08/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/rpall08/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

summerwind/actions-runner | latest | ubuntu-focal |   | CVE-2022-30632 | 411 | binary | high | go |   | 1.16.12 |   | 7.5 | fixed in 1.18.4, 1.17.12 | Attack complexity: low, Attack vector:   network, Has fix, High severity, Recent vulnerability |   | Uncontrolled recursion in Glob   in path/filepath before Go 1.17.12 and Go 1.18.4 allows an attacker to cause   a panic due to stack exhaustion via a path containing a large number of path   separators. |   |   | 15:00.0 |   | sha256:7157fe1aecd18c9d2071dd2124ae94a1d5ea4b676d3ad65c736dd9b7334852b7 | https://nvd.nist.gov/vuln/detail/CVE-2022-30632
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

</body>

</html>

### Describe the expected behavior

Expecting Twistlock (Container Security Scanning) scan clean actions-runner image.

### Controller Logs

```shell
Controller logs not required as, its regarding actions-runner image security scan vulnerabilities.
```

### Runner Pod Logs

```shell
Runner pod logs not required as, its regarding actions-runner image security scan vulnerabilities.
```
