### ISSUE TITLE
PVC and STS should get stable names

### ISSUE THREAD

**Issue by kim0** [actions-runner-controller/actions-runner-controller#1825]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.

### Controller Version

0.21

### Deployment Method

Helm

### cert-manager installation

Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: example-search-runners
spec:
  ephemeral: false
  replicas: 1
  repository: example/search
  selector:
    matchLabels:
      runner: example-search-runners
  serviceName: example-search-runners
  template:
    metadata:
      labels:
        runner: example-search-runners
    spec:
      serviceAccountName: github-actions-runner
      securityContext:
      tolerations:
      - key: "workload"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: runner
        volumeMounts:
        - name: docker01
          mountPath: "/tmp/.cache"
        env: []
        resources:
          limits:
            cpu: "8.0"
            memory: "8Gi"
          requests:
            cpu: "100m"
            memory: "4Gi"
        securityContext:
      - name: docker
        resources:
          limits:
            cpu: "8.0"
            memory: "8Gi"
          requests:
            cpu: "100m"
            memory: "2Gi"
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: docker01
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-search-runners
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: RunnerSet
    name: example-search-runners
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "10m"
```

### To Reproduce

```markdown
1. Deploy the runnerset
2. `kubectl get pvc` shows unstable names like

docker01-example-search-runners-8cqz6-0
```

### Describe the bug

ARC creates a new k8s sts with a random/unstable name for ephemeral runners or when changing the runnerset. This results in unstable names for the resulting PVCs. This is bec the PVC name is calculated from the k8s sts name like so
https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd#pv_to_statefulset:~:text=Work%20out%20the%20names%20of%20the%20automatically%20generated%20PersistentVolumeClaims

As a k8s sysadmin, this is how I would expect statefulsets to behave. When deploying a mysql DB for example, pods get stable names like `mysql-0` `mysql-1` ..., and PVC disks get the same stable names. You will find the word stable mentioned many times in the k8s sts docs
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage

For more explanation wrt storage for statefulsets, this is a good article
https://aws.plainenglish.io/kubernetes-deep-dive-statefulset-storage-state-48cd2e6d9463

Deploying that nginx sts example found in both the article linked above and also in the official docs, results in
```
$ kubectl -n actions-runner-system get sts web
NAME   READY   AGE
web    2/2     92s

$ kubectl -n actions-runner-system get po -l app=nginx
NAME    READY   STATUS    RESTARTS   AGE
web-0   1/1     Running   0          102s
web-1   1/1     Running   0          69s

$ kubectl -n actions-runner-system get pvc -l app=nginx
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
www-web-0   Bound    pvc-9fe9dc1b-45e5-47b3-87d2-77e79dc35295   2Gi        RWO            gp2            110s
www-web-1   Bound    pvc-60bd82a4-307c-4ad1-a4f1-ed9f402cca6f   10Gi       RWO            gp2            77s
```

As can be seen, the sts, pods and disks, all get stable names. This is by design. And this causes PVC reuse when pods of the statefulset come and go. This does NOT happen with runnerset.

The suggested fix is to drop the random part from the sts name. i.e. for a runnerset named `myrunner` this should generate a sts also called `myrunner` without random characters in the name. This in return will cause stable PVC names, which will cause natural PVC/Disk reuse as pods spin up/down, without resorting to hacks (like in #1286 )

### Describe the expected behavior

The suggested fix is to drop the random part from the sts name. i.e. for a runnerset named `myrunner` this should generate a sts also called `myrunner` without random characters in the name. This in return will cause stable PVC names, which will cause natural PVC/Disk reuse as pods spin up/down, without resorting to hacks (like in #1286 )

### Controller Logs

```shell
N/A
```

### Runner Pod Logs

```shell
N/A
```
