### ISSUE TITLE
Bug: `Failed to check if runner is busy`

### ISSUE THREAD

**Issue by callum-tait-pbx** [actions-runner-controller/actions-runner-controller#183]
This has been mentioned in a few places, I think it would be good to have an issue raised specifically for this going forward.

**Steps to Reproduce**
1. Deploy your chosen auth method
2. cd `config`
3. kustomize build ./default > .manifest.yaml
4. kubectl apply -f ./manifest.yaml
5. Deploy your runner configuration, an example is documented below:
6. Check manager logs `kubectl logs controller-manager-777fb76ddb-4tjpz -c manager`

**Error**
```json
2020-11-12T23:24:07.206Z  ERROR  controllers.Runner. Failed to check if runner is busy. {"runner": "actions-runner-system/runner-deployment", "error": "runner not found"}
```

**Behaviour**
This doesn't appear to prevent the runner being created nor scaling from working however there is a problem somewhere as we shouldn't be getting errors thrown at all

**Example Runner Yaml**
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runners-service-account
  namespace: actions-runner-system
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      organization: YOUR_ORG
      serviceAccountName: runners-service-account
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  scaleDownDelaySecondsAfterScaleUp: 10
  scaleTargetRef:
    name: runner-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - some-repo
    - some-repo-2
```
