### ISSUE TITLE
Feature: Expose `--sync-period` to Kustomize Build

### ISSUE THREAD

**Issue by callum-tait-pbx** [actions-runner-controller/actions-runner-controller#184]
It would be good to parameterise the `--sync-period` flag as part of the kustomize build with the default of 10 minutes? I would quite like this as part of the repo as I am trying to not go down the route of forking the repo and having a highly customised copy of this repo for my env, it will make maintaining the solution much easier if I can just use this repo and configure parameters instead. We use helm in my env so I don't know anything about writing kustomize builds really. I can look into it however if someone else knows how to do this first that would be amazing!

Issue detailing what I want to add as a parameter to the kutomize build https://github.com/summerwind/actions-runner-controller/issues/83

**Comment by mumoshu** [comment]
@callum-tait-pbx Thanks for writing this up! I'd like to add that, but I'm not sure how. As far as I know, kustomize does not have an ability to set arbitrary variables in the resources.

**Comment by mumoshu** [comment]
Maybe the helm chart (#91 by @stackdumper) would be the way to go?

**Comment by callum-tait-pbx** [comment]
I don't think it will, all the helm chart implementation does is wrap the output of kutomize in helm. You would need to subsequently edit the chart to parameterise this part. If the repo used helm initially then it could be done.

**Comment by callum-tait-pbx** [comment]
@mumoshu https://blog.stack-labs.com/code/kustomize-101/ from reading that doesn't Kustomize let you just apply arbritary yaml with arbritary values along a defined path? If so, this should be possible, if only I knew anything about Kustomize 😆

**Comment by callum-tait-pbx** [comment]
In the meantime I would like to add a snippet to the docs detailing the flag a bit more. Can you confirm the possible values? Does it just take an int and treats it as minutes or do you need / can provide a unit too?

```yaml
        args:
        - --enable-leader-election
        - --sync-period 5
```

**Comment by jbuettnerbild** [comment]
i would find it also helpful to know how to change the sync period. I have the feeling that the hra does not scale very well or fast enough.

**Comment by callum-tait-pbx** [comment]
Changing the sync period is very easy however it has to be done manually to the template and so has all the negatives of manual changes. https://github.com/summerwind/actions-runner-controller/issues/83 details where you need to make the change (as an argument to the manager container), you just need to make the change, build your template and deploy. As it's not a parameter in the kustomize build it's not very intuitive to do nor is it cleanly pipeline-able. It would be great if at a minimum, we could expose it to kustomize to make configuring it much easier and less custom. 

I guess the ideal scenario would be defining this sort of thing in a ConfigMap and the manager pulling the value from there instead.

@jbuettnerbild be aware the default value is 10 minutes to prevent someone rate limiting themselves

**Comment by jbuettnerbild** [comment]
ok i found it. thx @callum-tait-pbx for the hint.
`- --sync-period=1m0s`

**Comment by mumoshu** [comment]
@callum-tait-pbx What if you manage this `kustomization.yaml`

```
bases:
- git@github.com:github.com/summerwind/actions-runner-controller.git/config/default

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: controller-manager
    namespace: system
  template:
    spec:
      containers:
      - name: manager
        args:
        - --enable-leader-election
        - --sync-period=5m
```

so that it's matter of running `kustomize build ./` to generate the manifests with `--sync-period` added to the controller container args?

```
$ kustomize build . | grep -C 5 sync-period
template:
  spec:
    containers:
    - args:
      - --enable-leader-election
      - --sync-period=5m
      name: manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
```

**Comment by callum-tait-pbx** [comment]
I don't quite understand how to integrate this into the existing kustomize build. The only way I seem to be able to get Kustomise to like adding an additional argument is by adding it to the existing `manager_auth_proxy_patch.yaml`. As far as I can tell Kutstomize doesn't like 2 patches editing the same path, it considers them conflicting? We could just add `- "--sync-period=5m"` to `manager_auth_proxy_patch.yaml` and document you manage it there, I don't know how to parameterise it still though like we have done with the `namespace`? It really needs to be parameterised so it it can build via pipeline rather than manually editing it. For me it being able to be pipelined is important as I am ultimately wrapping the output of kustomize in Helm and so the config needs to be easily editable prgramatically.


the below yaml works, I just don't know how to parameterise the `--sync-period` value in the default `kustomization.yaml`
```yaml
# This patch inject a sidecar container which is a HTTP proxy for the controller manager,
# it performs RBAC authorization against the Kubernetes API using SubjectAccessReviews.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
        args:
        - "--secure-listen-address=0.0.0.0:8443"
        - "--upstream=http://127.0.0.1:8080/"
        - "--logtostderr=true"
        - "--v=10"
        ports:
        - containerPort: 8443
          name: https
      - name: manager
        args:
        - "--metrics-addr=127.0.0.1:8080"
        - "--enable-leader-election"
        - "--sync-period=5m"
```
