### ISSUE TITLE
Missing Metrics endpoints 

### ISSUE THREAD

**Issue by gthomson31** [actions-runner-controller/actions-runner-controller#1867]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.

### Controller Version

actions-runner-controller-0.21.0

### Helm Chart Version

actions-runner-controller-0.21.0       	App Version 0.26.0

### CertManager Version

v1.8.2

### Deployment Method

Helm

### cert-manager installation

Yes Cert-manager is installed within the EKS-Cluster

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
## RunnerDeployment

Name:         github-runner-deployment
Namespace:    github-actions-runners-prod01
Labels:       app.kubernetes.io/component=RunnerDeployment
              app.kubernetes.io/instance=github-actions-runner-deployment
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/part-of=github-actions-runners
              app.kubernetes.io/version=0.1.0
              helm.sh/chart=github-actions-runners-0.1.0
Annotations:  meta.helm.sh/release-name: github-actions-runner-deployment
              meta.helm.sh/release-namespace: github-actions-runners-prod01
API Version:  actions.summerwind.dev/v1alpha1
Kind:         RunnerDeployment
Metadata:
  Creation Timestamp:  2022-09-28T10:41:22Z
  Generation:          3
  Managed Fields:
    API Version:  actions.summerwind.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:replicas:
      f:status:
        .:
        f:availableReplicas:
        f:desiredReplicas:
        f:readyReplicas:
        f:replicas:
        f:updatedReplicas:
    Manager:      manager
    Operation:    Update
    Time:         2022-09-28T10:41:53Z
    API Version:  actions.summerwind.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/part-of:
          f:app.kubernetes.io/version:
          f:helm.sh/chart:
      f:spec:
        .:
        f:template:
          .:
          f:spec:
            .:
            f:image:
            f:imagePullPolicy:
            f:imagePullSecrets:
            f:organization:
    Manager:         terraform-provider-helm_v2.4.1_x5
    Operation:       Update
    Time:            2022-09-28T10:50:33Z
  Resource Version:  49721181
  UID:               b6c34592-eebf-44ee-a032-065e16b40155
Spec:
  Effective Time:  <nil>
  Replicas:        2
  Selector:        <nil>
  Template:
    Metadata:
    Spec:
      Dockerd Container Resources:
      Image:              snowplow/github-actions-runner:0.1.68
      Image Pull Policy:  IfNotPresent
      Image Pull Secrets:
        Name:        snowplow-github-runner-deployment-dockerhub
      Organization:  snowplow-devops
      Resources:
Status:
  Available Replicas:  2
  Desired Replicas:    2
  Ready Replicas:      2
  Replicas:            2
  Updated Replicas:    2
Events:
  Type    Reason                   Age    From                         Message
  ----    ------                   ----   ----                         -------
  Normal  RunnerReplicaSetDeleted  7m29s  runnerdeployment-controller  Deleted runnerreplicaset 'github-runner-deployment-pv8xr'




## HorizontalRunnerAutoscaler

Name:         github-actions-runner-deployment-horizontalrunnerautoscaler
Namespace:    github-actions-runners-prod01
Labels:       app.kubernetes.io/component=HorizontalRunnerAutoscaler
              app.kubernetes.io/instance=github-actions-runner-deployment
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/part-of=github-actions-runners
              app.kubernetes.io/version=0.1.0
              helm.sh/chart=github-actions-runners-0.1.0
Annotations:  meta.helm.sh/release-name: github-actions-runner-deployment
              meta.helm.sh/release-namespace: github-actions-runners-prod01
API Version:  actions.summerwind.dev/v1alpha1
Kind:         HorizontalRunnerAutoscaler
Metadata:
  Creation Timestamp:  2022-09-28T10:41:22Z
  Generation:          1
  Managed Fields:
    API Version:  actions.summerwind.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/part-of:
          f:app.kubernetes.io/version:
          f:helm.sh/chart:
      f:spec:
        .:
        f:maxReplicas:
        f:minReplicas:
        f:scaleDownDelaySecondsAfterScaleOut:
        f:scaleTargetRef:
          .:
          f:name:
        f:scaleUpTriggers:
    Manager:      terraform-provider-helm_v2.4.1_x5
    Operation:    Update
    Time:         2022-09-28T10:41:22Z
    API Version:  actions.summerwind.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:desiredReplicas:
        f:lastSuccessfulScaleOutTime:
    Manager:         manager
    Operation:       Update
    Time:            2022-09-28T10:41:53Z
  Resource Version:  49718237
  UID:               3da2356d-bf77-4dcb-8d33-be98505358b9
Spec:
  Max Replicas:                              10
  Min Replicas:                              2
  Scale Down Delay Seconds After Scale Out:  300
  Scale Target Ref:
    Name:  github-runner-deployment
  Scale Up Triggers:
    Duration:  10m
    Github Event:
      Workflow Job:
Status:
  Desired Replicas:                2
  Last Successful Scale Out Time:  2022-09-28T10:41:53Z
Events:                            <none>
```

### To Reproduce

```markdown
1. Deploy the Actions-Runner-Controller / Runners using Github App Auth within a Github ORG
2. Scrape metrics with Prometheus 
3. Check Metrics 

Tried the following 
- Hard Delete and reinstall CRDS
- Manual Replace of CRDS
- Destroying and relaunching the complete deployment
- Updating Runner to the latest image

Initially Discussed new metrics here : 
https://github.com/actions-runner-controller/actions-runner-controller/discussions/1713 

Release Notes : 
https://github.com/actions-runner-controller/actions-runner-controller/blob/master/docs/releasenotes/0.26.md#enhancement--more-autoscaling-related-metrics
```

### Describe the bug

Chart has been upgraded but new metrics endpoints are not available. 

### Describe the expected behavior

Expected to have the additional new metrics within Prometheus that are part of the new chart release

### Controller Logs

```shell
https://gist.github.com/gthomson31/5b60c49470b5235de78a0a8d3a945841
```

### Runner Pod Logs

```shell
https://gist.github.com/gthomson31/5b60c49470b5235de78a0a8d3a945841
```

### Additional Context

![Screenshot 2022-09-28 at 09 15 53](https://user-images.githubusercontent.com/29544622/192727300-40d48f4e-f082-499a-a199-571db490cee4.jpg)
