### ISSUE TITLE
RunnerDeployment don't reconcile the number of Runners

### ISSUE THREAD

**Issue by Moser-ss** [actions-runner-controller/actions-runner-controller#1881]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.

### Controller Version

0.26.0

### Helm Chart Version

0.21.0

### CertManager Version

v1.6.1

### Deployment Method

Helm

### cert-manager installation

I follow the official instructions of the cert-manager installation

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: eks-runner-test-demo
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      organization: example-inc
      group: K8s-runners-test
      labels:
        - eks-runner-demo
      nodeSelector:
          inc.example.nodegroup: default
      dockerdContainerResources:
        requests:
          ephemeral-storage: 100Mi
        limits:
          ephemeral-storage: 1Gi
      resources:
        requests:
          cpu: '1.5'
          memory: 6.5Gi
          ephemeral-storage: 5Gi
        limits:
          cpu: 2
          memory: 7Gi
          ephemeral-storage: 10Gi
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: eks-runner-deployment-autoscaler-test-demo
spec:
  # Runners in the targeted RunnerDeployment won't be scaled down
  # for 5 minutes instead of the default 10 minutes now
  scaleDownDelaySecondsAfterScaleOut: 1200
  scaleTargetRef:
    name: eks-runner-test-demo
  minReplicas: 2
  maxReplicas: 20
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
```

### To Reproduce

```markdown
1. Apply the resource HRA and the RunnerDeployment
2. Trigger the following job in the GitHub Actions

name: load-testing
on:
  pull_request:
    branches:
      - master

jobs:
  load-test:
    runs-on: eks-runner-demo
    strategy:
      matrix:
       test: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - uses: actions/checkout@v3

      - name: Get Random sleep
        id: sleep
        run: |
          sleepTime=$(shuf -i 30-300 -n 1)
          echo "Sleep for ${sleepTime} second"
          echo "::set-output name=sleep::${sleepTime}"

      - name: Random wait ${{steps.sleep.outputs.sleep}}
        env: 
          SLEEP_TIME: ${{steps.sleep.outputs.sleep}}
        run: sleep "${SLEEP_TIME}"


3. Wait until all jobs finish
4. Check the RunnerDeployment status over time and check the values for status.replicas and status.desiredReplicas
```

### Describe the bug

The RunnerDeployment takes a long time to reconcile the number of Runners when a Runner finishes a GitHub Action Job. We see a reduction in the number of Runners, and only after 10 minutes do we see the RunnerDeployment reconcile the number of Runners

### Describe the expected behavior

I expect that every time a Runner terminates his job, a new Runner is created to replace him, and we keep the number of desired replicas to be equal to the number of replicas

### Controller Logs

```shell
https://gist.github.com/Moser-ss/58da1a7eb7004eb083ab668153e3c67d
The logs were collected from the controller with the timezone of UTC
```

### Runner Pod Logs

```shell
Runner Pod logs not collected
```

### Additional Context

In the following graph, we can see the values of status.replicas, and status.desiredReplicas during the period where the bug appears.
All the data and logs collected were done during the scenario described in the section **To Reporduce**
The time in the graph is in UTC+1 

![image](https://user-images.githubusercontent.com/14796637/193137943-c92de341-a1c2-46bc-bbd6-0dc47ce9220c.png)
