### ISSUE TITLE
Scaleup not working when minReplicas: 0 and using PercentageRunnersBusy

### ISSUE THREAD

**Issue by rptxeni** [actions-runner-controller/actions-runner-controller#1908]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.

### Controller Version

0.26.0

### Helm Chart Version

0.21.0

### CertManager Version

1.9.1

### Deployment Method

Helm

### cert-manager installation

Cert manager installed following the guidelines on https://cert-manager.io/docs/installation/helm/#installing-with-helm from official source

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-deployment
  namespace: mynamespace
spec:
  template:
    spec:
      organization: myorg
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: actions-runner-deployment-autoscaler
  namespace: mynamespace
spec:
  scaleTargetRef:
    name: actions-runner-deployment
  minReplicas: 0
  maxReplicas: 100
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '1'       
    scaleDownThreshold: '1'
    ScaleUpAdjustment: '1'
    ScaleDownAdjustment: '1' 
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
    amount: 1
    duration: "10m"`
```

### To Reproduce

```markdown
Launch an action from a github repositoy, the scaleup never happens.
```

### Describe the bug

Runner never scale from 0 to 1 when an action is triggered.

### Describe the expected behavior

The runner scale to 1 when an action is triggered.

### Whole Controller Logs

```shell
https://gist.github.com/rptxeni/f33e8461db88c8edb6bed2fb310da528
```

### Whole Runner Pod Logs

```shell
NA
```

### Additional Context

If minReplicas is set to 1, the action is executed on a runner and the scaleup/scaledown is working.
However, we must always have at least one runner.
