### ISSUE TITLE
Self hosted runner is not spinning up with the custom image provided from ECR

### ISSUE THREAD

**Issue by YatinGulati94** [actions-runner-controller/actions-runner-controller#1952]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.26.0

### Helm Chart Version

0.21.1

### CertManager Version

1.8

### Deployment Method

Helm

### cert-manager installation

Yes I followed the same link
https://github.com/actions-runner-controller/actions-runner-controller

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeployment
spec:
  replicas: 1
  template:
    spec:
      repository: The-Coca-Cola-Company/bkupbigit
      image: 040160424746.dkr.ecr.us-west-2.amazonaws.com/sf-pr-auto-test:latest
      env:
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
```

### To Reproduce

```markdown
1. Create a namespace of actions-runner-system.
2. run the kubectl apply -f runnerdeployment.yml
```

### Describe the bug

After running apply command, container is not spinning up with the custom image which i already build using 
FROM summerwind/actions-runner:latest.

### Describe the expected behavior

Container should spin with the custom image as well

### Whole Controller Logs

```shell
Issue is very known, logs not required
```

### Whole Runner Pod Logs

```shell
Issue is very known, logs not reuqired
```

### Additional Context

Please solve this. On Priority
