### ISSUE TITLE
webhook server: "cache contained <nil>, which is not an Object" when handling workflow_job event

### ISSUE THREAD

**Issue by samip5** [actions-runner-controller/actions-runner-controller#1974]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.21.1?

### Helm Chart Version

0.21.1

### Deployment Method

Other

### cert-manager installation

cert-manager is perfectly working.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: samipsolutions-runners-arm64
  namespace: ci
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      env:
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
      image: summerwind/actions-runner-dind
      organization: samipsolutions
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: samipsolutions-runners-arm64
  namespace: ci
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: RunnerDeployment
    name: samipsolutions-runners-arm64
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "15m"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: samipsolutions-runners-amd64
  namespace: ci
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      env:
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
      image: summerwind/actions-runner-dind
      organization: samipsolutions
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: samipsolutions-runners-amd64
  namespace: ci
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: RunnerDeployment
    name: samipsolutions-runners-amd64
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "15m"
```

### To Reproduce

```markdown
1. Create the resources
2. Setup webhook
3. Try to use an action with self-hosted label.
```

### Describe the bug

I tried to setup runners for arm64 and x64 for org-wide, and the runners appear in Github, due to self-registration but doesn't seem to be picking up jobs.

### Describe the expected behavior

I would have expected it to start working on my actions, but it doesn't seem to pick it up.

### Whole Controller Logs

```shell
https://gist.githubusercontent.com/samip5/c6583ba8a6e5ccc3eadd4a487487eaa3/raw/a7d52157409d019902f117431fad7ffe830aaa3c/controller-logs.txt
```

### Whole Runner Pod Logs

```shell
https://gist.githubusercontent.com/samip5/c6583ba8a6e5ccc3eadd4a487487eaa3/raw/a7d52157409d019902f117431fad7ffe830aaa3c/runner-logs.txt
```

### Additional Context

My current GitOps can be seen here: https://github.com/samip5/k8s-cluster/tree/838dd6b08fb15c5410abef2756cb158c47478c77/cluster/apps/ci

Seems somewhat related to an old issue (#776).
