### ISSUE TITLE
ARM runner image is broken in 87f566e

### ISSUE THREAD

**Issue by tbondarchuk** [actions-runner-controller/actions-runner-controller#2046]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.26.0

### Helm Chart Version

0.21.1  

### Deployment Method

Helm

### cert-manager installation

- yes
- yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-generic-arm
spec:
  template:
    spec:
      serviceAccountName: runner-generic-arm
      image: ghcr.io/actions-runner-controller/actions-runner-controller/actions-runner:v2.299.1-ubuntu-20.04-87f566e
      dockerEnabled: false

      organization: REDUCTED

      labels:
        - generic-arm

      resources:
        requests:
          cpu: "0.5"
          memory: "512Mi"

      nodeSelector:
        kube/nodetype: "ci-runners-arm"
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: ci-runners-arm
```

### To Reproduce

```markdown
1. run latest `87f566e` runner image on arm node
```

### Describe the bug

Runner fails with: `/usr/bin/entrypoint.sh: line 6: /usr/bin/dumb-init: cannot execute binary file: Exec format error`

I was able to track it to https://github.com/actions-runner-controller/actions-runner-controller/commit/87f566e1e6137ab7a846da800ae1c5f083016be9  though it seems that change to use TARGETPLATFORM was introduced in previous commits, but I haven't checked further.

TARGETPLATFORM is now hardcoded to x86_64 (from gha public runner arch) so it builds arm images with all downloaded binaries with incorrect arch 🤷🏻‍♂️

I guess the next step was supposed to use multiple build steps, one per arch? like `docker buildx build --build-arg TARGETPLATFORM=x86_64 ... --platform linux/amd64` and `docker buildx build --build-arg TARGETPLATFORM=arm64 ... --platform linux/arm64` but for some reason it wasn't merged (yet)?

```sh
/usr/bin/docker buildx build --build-arg TARGETPLATFORM=x86_64 ... --platform linux/amd64,linux/arm64
```
https://github.com/actions-runner-controller/actions-runner-controller/actions/runs/3544653074/jobs/5952126775#step:5:124

previous builds used correct arch - https://github.com/actions-runner-controller/actions-runner-controller/actions/runs/3527155502/jobs/5915898071#step:4:189

@mumoshu @toast-gear 

### Describe the expected behavior

arm images should be built with arm binaries

### Whole Controller Logs

```shell
definitely not relevant for image build
```

### Whole Runner Pod Logs

```shell
NOTICE --- Runner init started with pid 6
/usr/bin/entrypoint.sh: line 6: /usr/bin/dumb-init: cannot execute binary file: Exec format error
NOTICE --- Runner init exited. Exiting this process with code 0 so that the container and the pod is GC'ed Kubernetes soon.
```

### Additional Context

current fix is to use last stable version: `v2.299.1-ubuntu-20.04-154fcde`

only arm images are affected
