### ISSUE TITLE
Docker is not working

### ISSUE THREAD

**Issue by esvirskiy** [actions-runner-controller/actions-runner-controller#278]
I am running actions-runner-controller-0.2.0 installed via Helm and getting the below error

```
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged chart-testing-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 137
```

I have enabled Docker:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-runner-autoscaler
spec:
  template:
    spec:
      organization: myorg
      dockerEnabled: true
      resources:
        limits:
          cpu: "1.0"
          memory: "1Gi"
        requests:
          cpu: "0.5"
          memory: "0.5Gi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: gha-runner-autoscaler
spec:
  scaleTargetRef:
    name: gha-runner-autoscaler
  minReplicas: 1
  maxReplicas: 10
  scaleDownDelaySecondsAfterScaleOut: 60
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: "0.75"
      scaleDownThreshold: "0.3"
      scaleUpFactor: "1.4"
      scaleDownFactor: "0.7"
```

```
k version --short
Client Version: v1.20.2
Server Version: v1.18.9-eks-d1db3c
```
