### ISSUE TITLE
question, appling a downscale to  runnerdeployment not concentrate runners on the first node, so nodepool autoscaling can't downscale.

### ISSUE THREAD

**Issue by matteo-savore-deltatre** [actions-runner-controller/actions-runner-controller#299]
Hi , thank you for your work, love it.
I'm doing some experiments on my AKS with autoscale nodepool.

if a start applying a runner deployment with replica 1 to a nodepool autoscale (1  VM ) it puts the pod on this VM (obviously)
then I re-apply with replica 10 and correclty the nopool autoscale to 2 vms and all the runners are correctly started and spreaded acroos the nodes.
At this point i apply back replica 1.

should i get the pod on the first node ?
Actually i get the Pod on the second node and the nodepool is not able to downscale itself to 1 Vms as it was at the very beginning.
Is this an expected results? or i need to add something to get pods move to the very first node if there is room on it ?

Thank you

**Comment by mumoshu** [comment]
@matteo-savore-deltatre Hey! This is actually a good question. I believe that's due to that CA's default behavior is to [avoid evicting pods that are not backed by K8s deployment, replicaset, statefulset, or job](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node). Our runner pods are backed by Runner, RunnerReplicaSet, RunnerDeployment.

According to their doc, adding `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` to your runner pods would force the CA to consider it for eviction.

Would you mind giving it a shot?

For your reference, I thought I've implemented the controller to inherit runner annotations to the runner pod. So, you should be able to add arbitrary runner pod annotations via `RunnerDeployment.Spec.Template.Metadata.Annotations` or `Runner.Metadata.Annotations` like e.g.:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example
spec:
  template:
    metadata:
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      repository: your/repo
```
