### ISSUE TITLE
Only one PV is getting created by using the Runner Deployment file even though we mention 2 pv's 

### ISSUE THREAD

**Issue by vyarabot** [actions-runner-controller/actions-runner-controller#414]
Hi Team , 

We are using Runner Deployment for creating runners on the GH enterprise system by using the below yaml file . we have a need to having 2 PV's to be mounted , only one pv is getting reflected during the container creation . here is the yaml file for reference . Need help ! 

![image](https://user-images.githubusercontent.com/45797735/112072226-9b963100-8b2e-11eb-9888-2aedaba1c4e3.png)

Regards ,
Praveen .

**Comment by mumoshu** [comment]
@vyarabot Hey! Could you try merging multiple `volumes` and `volumeMounts` settings you have under `spec`, due to perhaps how YAML works?

**Comment by vyarabot** [comment]
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: cicd-ghe-runner
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      labels:
        - k8s-runner
     # nodeSelector:
      #  node-role.kubernetes.io/test: ""
​
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/test
        operator: Exists
      organization: organization
      image: summerwind/actions-runner:latest
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "4.0"
          memory: "8Gi"
        requests:
          cpu: "2.0"
          memory: "4Gi"
      volumeMounts:
      - mountPath: /runner
        name: runner
      volumes:
      - emptyDir: {}
        name: runner
      volumes:
      - name: action-multiversion
        persistentVolumeClaim:
          claimName: action-multiversion-pvc
      volumeMounts:
      - name: action-multiversion
        mountPath: "/runner/workspace/installables"
        readOnly: true
      volumes:
      - name: action-maven
        persistentVolumeClaim:
          claimName: action-maven-pvc
      volumeMounts:
      - name: action-maven
        mountPath: "/runner/workspace/.m2"
        readOnly: true
      # Timeout after a node crashed or became unreachable to evict your pods somewhere else (default 5mins)
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      # true (default) = A privileged docker sidecar container is included in the runner pod.
      # false = A docker sidecar container is not included in the runner pod and you can't use docker.
      # If set to false, there are no privileged container and you cannot use docker.
      dockerEnabled: false
      # false (default) = Docker support is provided by a sidecar container deployed in the runner pod.
      # true = No docker sidecar container is deployed in the runner pod but docker can be used within teh runner container instead. The image summerwind/actions-runner-dind is used by default.
      dockerdWithinRunnerContainer: true
      # Docker sidecar container image tweaks examples below, only applicable if dockerdWithinRunnerContainer = false
      # workDir if not specified (default = /runner/_work)
      # You can customise this setting allowing you to change the default working directory location
      # for example, the below setting is the same as on the ubuntu-18.04 image

**Comment by vyarabot** [comment]
Hi @mumoshu


We tried as above , still we dont see bot the mounts happening , can you please help ! 

Regards ,
Praveen .

**Comment by mumoshu** [comment]
@vyarabot Hey! Could you try pasting the yaml with correct indentatino using triple-backquotes in markdown?

**Comment by mumoshu** [comment]
Also how did you confirm that your volume mounts are missing?

**Comment by mumoshu** [comment]
@vyarabot Hey! Your RunnerDeployment YAML seems still broken.

You have:

```
      volumes:
      - emptyDir: {}
        name: runner
      volumes:
      - name: action-multiversion
        persistentVolumeClaim:
          claimName: action-multiversion-pvc
      volumeMounts:
      - name: action-multiversion
        mountPath: "/runner/workspace/installables"
        readOnly: true
      volumes:
      - name: action-maven
        persistentVolumeClaim:
          claimName: action-maven-pvc
      volumeMounts:
      - name: action-maven
        mountPath: "/runner/workspace/.m2"
        readOnly: true
```

But this should be more like:

```
      volumes:
      - emptyDir: {}
        name: runner
      - name: action-multiversion
        persistentVolumeClaim:
          claimName: action-multiversion-pvc
      - name: action-maven
        persistentVolumeClaim:
          claimName: action-maven-pvc
      volumeMounts:
      - mountPath: /runner
        name: runner
      - name: action-multiversion
        mountPath: "/runner/workspace/installables"
        readOnly: true
      - name: action-maven
        mountPath: "/runner/workspace/.m2"
        readOnly: true
```
