### ISSUE TITLE
bug: no label added to runner as in spec

### ISSUE THREAD

**Issue by callum-tait-pbx** [actions-runner-controller/actions-runner-controller#429]
chart: 0.10.4
manager: 0.18.0

I just created a `runner` with the label `iam`, I was expecting upon the runner being registered with github the additional label of `iam` would be assigned to it, unfortunately it was not present on github.com.

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  namespace: actions
  name: iam-runner
spec:
    repository: owner/repo
    image: registry/repository/image:tag
    labels:
      - iam
```

`RUNNER_LABELS: iam` is present as an environment variable on the runner

Interestingly:
1. I added the label manually via the website
2. Removed the label on the website
3. Deleted the pod on EKS and let the controller reprovision it the runner

At this point the label gets applied by the controller when the runner is reprovisioned. I am going to guess that this is a similar situation as the runner groups where the label needs to first be created in github before the controller can apply it to pods going forward? In which case we just need to update the docs to mention this
