### ISSUE TITLE
Add scaling `minReplicas` count to zero based on a schedule

### ISSUE THREAD

**Issue by callum-tait-pbx** [actions-runner-controller/actions-runner-controller#484]
**Background**
https://github.com/summerwind/actions-runner-controller/pull/465 added support to be able to set the `minReplicas` count down to 0, this feature request is an enhacnement to that work. 

**Feature**
Ability to scale the `minReplicas` count in a HRA spec down to 0 based on a cron style schedule rather than statically setting the `minReplicas` to 0.

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  scaleReplicasToZeroSchedule: 0 0 * * 6,0
  minReplicas: 5
  maxReplicas: 10
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.3'
    ScaleUpAdjustment: '2'
    ScaleDownAdjustment: '1'
```

**Driver**
The original driver for adding the ability to scale the min replica count to 0 was because a user was running a 1:1 mapping of runner to node. This was because their builds requiered very large servers which were expensive to run so they wanted the ability to only bring a node up when there was demand for a build saving money.

The driver for this enhancement is to reduce the cost of running this solution for a broader range of setups. Bringing a new node up can take 5+ minutes introducing lag to builds, often this lag isn't acceptable / appropriate during buisness hours but may be acceptable at weekends or during off peak hours. For people running a many runners-to-node setup this would be an essential enhancement to be able to achieve the cost savings you could make (which could be a lot of ££££ / year) with the introduction of the 0 min replicas feature from the PR https://github.com/summerwind/actions-runner-controller/pull/465

**Comment by mumoshu** [comment]
This should be a great enhancement to actions-runner-controller :)

Nit but with your example how would you increase the minReplicas to greater than 0 before your business hours begin?

Anyway, I'd prefer the syntaxes like the belows for extendabiliity:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  scheduledOverrides:
  # Set minReplicas to 0 on sat
  - schedule: "0 0 * * 6"
    minReplicas: 0
  # Set minReplicas back to 1 on mon
  - schedule: "0 0 * * 1"
    minReplicas: 1
  minReplicas: 1
```


```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  scheduledOverrides:
  # Override minReplicas to 0 only between 0am sat to 0am mon
  # NOte that I've explicitly used the term `range` because this isn't how you usually use crontab expression...
  - scheduleRange: "0 0 * * 6,0,1"
    minReplicas: 0
  minReplicas: 1
```

**Comment by mumoshu** [comment]
Or more explicitly, without exploiting crontab syntax...

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  scheduledOverrides:
  # Override minReplicas to 0 only between 0am sat to 0am mon
  # NOte that I've explicitly used the term `range` because this isn't how you usually use crontab expression...
  - weekly:
      from: {"Weekday": "Saturday", "Time", "0:00"}
      to: {"Weekday": "Monday", "Time", "0:00"}
    minReplicas: 0
  minReplicas: 1
```

I actually think this is the best as it is straightforward to read and it's open for extension like adding monthly or yearly schedules.

A downside is that you can't reuse your knowledge on e.g. crontab. But perhaps that's okay, as we don't have a industry standard for representation a periodic range? (Crontab is for representing periodic and discrete points in time, right?

**Comment by mumoshu** [comment]
Implementation-wise, this should work without the controller actually modifying the `HRA.Spec.Replicas` value. If it did so, it makes GitOps a bit harder. All the overrides should happen within the controller reconcile loop and the determined "final" replicas being used should be only visible through HRA.Status, not HRA.Spec.

**Comment by callum-tait-pbx** [comment]
> A downside is that you can't reuse your knowledge on e.g. crontab. But perhaps that's okay, as we don't have a industry standard for representation a periodic range? (Crontab is for representing periodic and discrete points in time, right?
 
I don't think it's a problem really, I just used cron style in the feature request because it's just a standard scheduling format people know. In reality I don't think we need the level of granularity that format provides. The 2 common schedules I see the end user configuring are:

- Scale down to 0 at weekends
- Scale down to 0 outside core business hours on week days e.g. 23:00 - 05:00 Mon - Friday (in the case of Friday that would bleed into Saturday which would then override and so the replica count wouldn't scale up again until Monday)

```yaml
  - weekly:
      from: {"Weekday": "Saturday", "Time", "0:00"}
      to: {"Weekday": "Monday", "Time", "0:00"}
```

This format would work however you would end up with a somewhat long list as you would need a unique entry for every week day (Mon - Tue, Tue - Wed etc etc). That's not the end of the world but it's not very concise. For people running many runner types you may end up with a fairly large document, not the end of the world but something to be aware of when it comes to implementation.

> All the overrides should happen within the controller reconcile loop and the determined "final" replicas being used should be only visible through HRA.Status, not HRA.Spec.

Definitely, it should also be the first thing that is assessed so we don't make superfluous API calls. If we are on a scale replicas to 0 schedule there is no reason to call the API.

**Comment by callum-tait-pbx** [comment]
@mumoshu please add the `enhancement` label to this issue 🙏

**Comment by mumoshu** [comment]
> That's not the end of the world but it's not very concise. For people running many runner types you may end up with a fairly large document, if they are doing a scale down on weekends and weekdays schedule then they would need to define 18 lines scheduling code on all RunnerDeployments that get provisioned on the node you wish to scale down. It's not the end of the world but perhaps a format that allows for a more concise definition would be better?

@callum-tait-pbx Thanks for the feedback!

I spent some time researching this, and it turned out that the only well-known standardized format for representing recurring schedules is `RRULE` defined in [RFC 5545](https://tools.ietf.org/html/rfc5545).

I don't particularly like the spec, but it is seems to be used widely, like in [Google Calendar API](https://developers.google.com/calendar/recurringevents).

It seems to work by providing the stard/end of the first occurrence, and RRULE defines how often and how many times it is repeated.

If we model the API similar to Google Calendar's, it would look like:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  scheduledOverrides:
  # Override minReplicas to 0 only between 0am sat to 0am mon
  # Note that I've explicitly used the term `range` because this isn't how you usually use crontab expression...
  - startTimestamp: "2021-05-03T00:00:00+0900"
    endTimestamp: "2021-05-08T00:00:00+0900"
    # "The UNTIL rule part defines a DATE or DATE-TIME value that bounds
    # the recurrence rule in an inclusive manner.  If the value
    # specified by UNTIL is synchronized with the specified recurrence,
    # this DATE or DATE-TIME becomes the last instance of the
    # recurrence." from 3.3.10.  Recurrence Rule, RFC 5545
    recurrence: "RRULE:FREQ=WEEKLY;UNTIL=20220502T150000Z"
    minReplicas: 0
  minReplicas: 1
```

But I don't really like `UNTIL` forced to be UTC, while it will be possible to use our own timezones when necessary for start/endTimestamp.

So I'd rather model it like:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  scheduledOverrides:
  # Override minReplicas to 0 only between 0am sat to 0am mon
  # Note that I've explicitly used the term `range` because this isn't how you usually use crontab expression...
  - startTimestamp: "2021-05-03T00:00:00+0900"
    endTimestamp: "2021-05-07T00:00:00+0900"
    recurrenceRule:
      freq: Weekly
      until: "2022-05-03T00:00:00+0900"
    minReplicas: 0
  minReplicas: 1
```

This allows us to borrow definitions of the terms `recurrenceRule` (RRULE is abbrev of that), `freq` (FREQ in RRULE), and `until` (UNTIL), while still allowing us to naturally use RFC 3339 even for `until`.

**Comment by mumoshu** [comment]
A few more things I considered:

- You can have two or more items in `scheduledOverrides`
- If there were two or more recurring overrides active at a specific time, the biggest `minReplicas` among active overrides would be chosen.
- If there were both onetime and recurring overrides at a specific time, the onetime one's `minReplicas` would be chosen.

**Comment by mumoshu** [comment]
#515 is the initial implementation of ScheduledOverrides.

A few API differences from what I planned- as `freq` and `until` were not exactly FREQ and UNTIL defined in RFC 5545, I've chosen similar but more concise words for our use, `frequency` and `untilTime` respectively.

Planned:

```
    recurrenceRule:
      freq: Weekly
      until: "2022-05-01T00:00:00+09:00"
```

What's in #515:

```
    recurrenceRule:
      frequency: Weekly
      untilTime: "2022-05-01T00:00:00+09:00"
```

**Comment by mumoshu** [comment]
Tried my best writing some doc :)

https://github.com/actions-runner-controller/actions-runner-controller#scheduled-overrides

**Comment by callum-tait-pbx** [comment]
@mumoshu amazing prompt work on this feature request, I very much appreciate it, it looks very impressive!!! I assume you don't expect any CRD changes to the feature, just potential app code changes to the controller for potential bugs?

The one thing I want to clarify to be explicit is in the case of a recurring rule (as those are the schedules I will be using in my environment exclusively) the `yyyy-mm-dd` part of the datetime is simply the `yyyy-mm-dd` I want the rule to take effect. After that date only the `hh:mm+Timezone` are used to determine when the schedule should be applied again? So if I want to scale down to 0 on weekends I need to set it to date of the first saturday of the week in question?

Does the scheduling handle the fact that not all months have the same number of days in them and thus same number of Saturdays? When we say frequency:

```
Weekly
Monthly
Yearly
```

Does that mean weekly in respect to the calander or does tha mean every 7 days regardless of what day that ends up being?
When we say monthly does that mean in respect to the calander month or does that mean every 30 days?
When we say yearly does that mean in respect to leap years or does that mean every 365 days?

Again thank you very much for your work on this feature, it's a great new addition and I am super excited for deploying it into my environment! 🙇

**Comment by mumoshu** [comment]
@callum-tait-pbx Hey! Thanks for checking.

> it looks very impressive!!! I assume you don't expect any further CRD changes to the feature in relation to this feature, just potential app code changes to the controller to fix any potential bugs?

I'm considering extending HRA status to include active and upcoming scheduled override(s) so that you can review if you've configured it correctly. But I have no plan to change HRA spec for now.

> Does the scheduling handle the fact that not all months have the same number of days in them and thus same number of Saturdays?

Yes. It's even covered in unit tests.

> Does that mean weekly in respect to the calander or does tha mean every 7 days regardless of what day that ends up being?

Calendar. 

> When we say monthly does that mean in respect to the calander month or does that mean every 30 days?

Calendar.

> When we say yearly does that mean in respect to leap years or does that mean every 365 days?

It respects leap years.

> Scale to 0 all day Saturday through Sunday for all Saturdays and Sundays every year
> Scale to 0 for non-core business hours Monday through Friday for all Mondays through Fridays every year (something like 23:00 -> 05:00 the next day so technically it bleeds into Saturday but that is fine as I would also have the weekend schedule)

Sounds good and it should just work. The controller uses the first "active" schedule override so you must place e.g. one-time schedule earlier, like I've written in this example:

https://github.com/actions-runner-controller/actions-runner-controller/blob/master/acceptance/testdata/org.hra.yaml#L15-L24

But in your setup either is for setting the replicas to 0, so the ordering doesn't matter. Just have to items under `HRA.Spec.ScheduledOverrides` and it should work.

**Comment by callum-tait-pbx** [comment]
> As we don't have a Web UI, I'm not sure what's the best way.

Would perhaps introducing an additional `additionalPrinterColumns` attribute e.g. `schedules` to the HRA CRD be the way to go I wonder? Many people interact with their k8s clusters (including me!) using Lens. Lens is just a graphical interface to the kubectl basically but it supports the full range of types including CRDs and their `additionalPrinterColumns`, it would be nice if all the information was avaliable in Lens so you don't need to switch between applications.

We already use the `additionalPrinterColumns` feature to provide additional relevant information for our custom types, perhaps this then is the logical place? It might be a bit verbose for what that feature is really designed to be used for though? I'm not super sure so feel free push back but that feels like the natural place to me.

It's a bit of a small scale solution but is perhaps a good starting point and would be enough for smaller setups.

> Would logging a few upcoming scheduled overrides in the controller log be enough

I think this would certainly be useful as many people rely on logs for much of their visibility. Logging when a schedule has been met resulting in scaling activity or is upcoming would help someone work out why their replicas gone up or down as well as confirming the scheduling is working.

> Do you want a dedicated CLI application to print e.g. a ascii art calendar or a schedule list showing upcoming overrides?

I'd be interested what the community thinks about this, perhaps raised as a new issue as a enhancement. I'm just trying to imagine how others may use the scheduling feature and I can see how with a large enough setup something to visualise or at least better present the schedules. Would this app target individual HRAs? I think this is key as I a doubt many people will have more than 2 - 4 schedules per HRA so it is perhaps overkill?

**Comment by mumoshu** [comment]
@callum-tait-pbx Thanks for the feedback!

I considered `additionalPrinterColumns`. However, it turned out we can't print complex fields with it. https://github.com/kubernetes/kubernetes/issues/67268

Probably we can just show a finite set of active/upcoming override sheculdes by carefully designing our `HRA.Status` fields so that it can map 1-1 to the respective printer columns.

For example, I might imagine that it would look like the below:

```
spec:
  sheculedOverrides:
  - name: scaleTo0OnWeekends
status:
  scheduledOverrides:
    active:
      summary: "scaleTo0OnWeekends: minReplicas=0, startTime=<some timestamp>, endTime=<some timestamp>"
    upcoming:
      summary: "scaleTo0OnWeekends: minReplicas=0, startTime=<some timestamp>, endTime=<some timestamp>"
```
