### ISSUE TITLE
GitHub Organisation move results in 404 when referencing existing Helm repository

### ISSUE THREAD

**Issue by donovanmuller** [actions-runner-controller/actions-runner-controller#497]
We use ArgoCD to deploy the `actions-runner-controller` and we reference the Helm chart as follows in a ArgoCD `Application`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
spec:
  destination:
    namespace: actions-runner-system
    server: https://kubernetes.default.svc
  source:
    chart: actions-runner-controller
    repoURL: https://summerwind.github.io/actions-runner-controller
    targetRevision: 0.11.0
...
```

with the GitHub Organisation move from https://github.com/summerwind/actions-runner-controller to https://github.com/actions-runner-controller/actions-runner-controller, this now means that the Helm chart repo referenced above results in a `404`, as the GitHub pages link does not redirect:

![Screenshot 2021-04-30 at 21 18 00](https://user-images.githubusercontent.com/1175891/116746447-c95b7900-a9fc-11eb-85b8-c5c45f36cda9.png)

Creating this issue for anyone else hitting this issue. To fix, use the new GitHub pages doman of https://actions-runner-controller.github.io/actions-runner-controller
