### ISSUE TITLE
docker buildx not working with default settings

### ISSUE THREAD

**Issue by ToonvanStrijp** [actions-runner-controller/actions-runner-controller#518]
I'm using the `docker/setup-buildx-action@v1` step to setup buildx but for some reason this fails. I'm using the default runner and settings. What might be the issue here?

![image](https://user-images.githubusercontent.com/11893063/116948308-53b30f80-ac7f-11eb-8797-3f9920c44238.png)

**Comment by callum-tait-pbx** [comment]
https://github.com/docker/setup-buildx-action/issues/16 give it a context

**Comment by ToonvanStrijp** [comment]
@callum-tait-pbx just giving it a context didn't work for me. What ended up working was adding these steps:
```yaml
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
```
