### ISSUE TITLE
Split up helm/chart-releaser-action logic

### ISSUE THREAD

**Issue by callum-tait-pbx** [actions-runner-controller/actions-runner-controller#519]
I think we need to move away from using the `helm/chart-releaser-action` action. 

We need to doing the logic ourselves so we can better provide things like release notes for the Helm chart releases allowing us to include things like how to successfully upgrade, changes since last release, general information etc

```yaml
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

@mumoshu please add a label, we don't have a `ci` label currently for stale. I don't know if it's worth having a specific label for `ci` work or if `chore` will be fine. I'll let you decide. I'll start looking at this this week, if you think it's not the direction to go please let me know.
