### ISSUE TITLE
webhook autoscaler doesn't recognize organization target

### ISSUE THREAD

**Issue by yfried** [actions-runner-controller/actions-runner-controller#534]
I keep getting this in logs:
```
github-webhook-server 2021-05-09T11:48:28.986Z	INFO	controllers.Runner	Scale target not found. If this is unexpected, ensure that there is exactly one repository-wide or organizational runner deployment that matches this webhook event	{"event": "check_run", "hookID": "296414796", "delivery": "787a18e0-b0bc-11eb-8d24-0ff6126380d2", "checkRun.status": "completed", "action": "completed"}
```

Looks like it can't pull the org name or type from the event payload (But I might be misunderstanding the code)

This is my config:
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: kubernetes-1cores-2048mi-summerwind-autoscaler
spec:
  scaleTargetRef:
    name: kubernetes-1cores-2048mi-summerwind
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
    amount: 3
    duration: "5m"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: kubernetes-1cores-2048mi-summerwind
spec:
  template:
    spec:
      organization: Myorg-Private
      labels:
        - kubernetes-1cores-2048mi-summerwind
      ephemeral: true
      env:
        - name: RUNNER_DEBUG
          value: "true"
        - name: ACTIONS_RUNNER_INPUT_LABELS
          value: kubernetes-1cores-2048mi-summerwind
      image: my-custom-image:v1
      resources:
        requests:
          cpu: "1"
          memory: "2048Mi"
        limits:
          cpu: "1"
          memory: "2048Mi"
      dockerEnabled: false

```

I'm deploying the controller using helm chart from [my own branch](https://github.com/yfried/actions-runner-controller/tree/remove_auth_additions/charts) which shouldn't matter, but just in case...

Here's my values file:
```yaml
authSecret:
  create: false
  name: controller-manager
createDummySecret: false
githubWebhookServer:
  enabled: true
  imagePullSecrets: []
  ingress:
    enabled: true
    hosts:
      - host: summerwind-webhook-listener.myorg.com
        paths:
                    - backend:
                        serviceName: summerwind-actions-runner-controller-webhook
                        servicePort: http 
    tls:
      - hosts:
          - summerwind-webhook-listener.myorg.com
        secretName: myorg.com
  nameOverride: summerwind-webhook-listener
  replicaCount: 1
  secret:
    create: true
    name: github-webhook-server
metrics:
  proxy:
    enabled: false
  serviceMonitor: true
```

**Comment by mumoshu** [comment]
@yfried Could you share us the webhook payload of the event whose delivery ID is `"787a18e0-b0bc-11eb-8d24-0ff6126380d2"`? Without seeing that, I can't see what's happening. The webhook-based autoscaler should just work with organizational runners.

**Comment by mumoshu** [comment]
@yfried This the relevant code in the controller. You could probably try debugging it and see if it's really working as intended on your webhook payload https://github.com/actions-runner-controller/actions-runner-controller/blob/082245c5db64e023cd79604d9b158f336770e3fe/controllers/horizontal_runner_autoscaler_webhook.go#L170-L184

**Comment by mumoshu** [comment]
@yfried Thanks! The webhook payload seems fine.

Theoretically speaking, the only chance seems to be that you have two or more HorizontalRunnerAutoscaler that targets RunnerDeplyoment for the organization `Myorg-Private`.

Could you verify that by running `kubectl -n $YOUR_HRA_NS get horizontalrunnerautoscaler`?

**Comment by yfried** [comment]
No.
I had only 1.
Especially because of this caveat.

**Comment by mumoshu** [comment]
@yfried Thanks. Can you see this message in your log? https://github.com/actions-runner-controller/actions-runner-controller/blob/082245c5db64e023cd79604d9b158f336770e3fe/controllers/horizontal_runner_autoscaler_webhook.go#L377

What's include the `organization` field? Empty? Or `Myorg-Private`?

**Comment by yfried** [comment]
No, this message isn't in my logs, which is why I'm guessing it doesn't know to look for org

**Comment by yfried** [comment]
@mumoshu sent you a private message on k8s slack

**Comment by mumoshu** [comment]
@awoimbee Could you elaborate? You have have one HRA and one RunnerDeployment per a github organization and that should just work.

**Comment by awoimbee** [comment]
@mumoshu 
Let's say:
I want multiple kinds of runners (one with a GPU, one with 16GB of ram, ...) that I select with labels.
I want all my runner to be organization wide.
I want scaling to 0 (I don't want a runner with 24GB of ram and a GPU to sit idle)

-> I have to create multiple organization wide RunnerDeployment and also multiple HRA.

It seems like the webhook scaling doesn't handle having multiple organization wide HRA (yet)

Is there a plan to handle this use-case ?
(Thanks for the awesome work btw)

**Comment by mumoshu** [comment]
@awoimbee How can you differentiate runners? Basically, webhook event payloads do not contain information about which runner(with certain labels, groups, orgs, repositories, etc) the webhook event is going to trigger a workflow job run on.

If you have unique enough `job` names per org/repo/labels/groups/etc for your workflows, for scaling based on check run events, you can set `chckRun.Names` on HRA so that the HRA only reacts to check run with those names.

**Comment by mumoshu** [comment]
// So depending on your requirement, you'd need to raise feature requests to GitHub, not us.

**Comment by mumoshu** [comment]
BTW, to be clear, although this issue says `webhook autoscaler doesn't recognize organization target`, I've successfully tested it to work on my environment.

So I'm still believing this would have been some user error, even though there might be some documentation or operational enhancements we need to make.

**Comment by fabiano-amaral** [comment]
I found the problem on our setup

This is issue is caused by a HRA without minReplica and maxReplica.

**Comment by mumoshu** [comment]
@fabiano-amaral Thanks for the info! Could you clarify a bit more? I had no clue how minReplicas and maxReplicas of a HRA affects it, because actions-runner-controller doesn't use those fields for filtering the right HRA for a webhook event.

**Comment by fabiano-amaral** [comment]
> @fabiano-amaral Thanks for the info! Could you clarify a bit more? I had no clue how minReplicas and maxReplicas of a HRA affects it, because actions-runner-controller doesn't use those fields for filtering the right HRA for a webhook event.

Yes, don't use and i agree totally with u, but the only way that worked for us is adding this configs to HRA.

Min and

**Comment by mumoshu** [comment]
@awoimbee Hey! We don't yet have out-of-box support for handling multiple sets of organizational runners with a single HRA that you asked.

But we do now have `workflow_job` webhook based scale that doesn't require manual mapping on check run names

https://github.com/actions-runner-controller/actions-runner-controller#example-1-scale-on-each-workflow_job-event

With that it should be pretty easy to set up multiple HRA+RunnerDeployment pairs.

Does it solve your original issue? Or were you talking about anything else?

**Comment by mumoshu** [comment]
@fabiano-amaral Thanks a lot for the info! I have not reproduced your issue yet, but I'd definitely keep your information in my mind and report back if there's any update 👍

**Comment by UrosCvijan** [comment]
Hi @mumoshu did you find any conlusion on this, cause I am having the same thing. Started testing autoscaling with webhook on github enterprise, get the same message, don't have in the log finding organization runner.. 


`2022-07-26T10:52:06Z    DEBUG   controllers.webhookbasedautoscaler      Found 0 HRAs by key     {"key": "engineering/ReleaseTesting"}
2022-07-26T10:52:06Z    DEBUG   controllers.webhookbasedautoscaler      Found some runner groups are managed by ARC     {"event": "check_run", "hookID": "326", "delivery": "fd99f650-0cd0-11ed-8638-58a055482577", "groups": "RunnerGroup{Scope:Organization, Kind:Custom, Name:prod-scaling}"}
2022-07-26T10:52:06Z    DEBUG   controllers.webhookbasedautoscaler      groups  {"event": "check_run", "hookID": "326", "delivery": "fd99f650-0cd0-11ed-8638-58a055482577", "groups": "RunnerGroup{Scope:Organization, Kind:Custom, Name:prod-scaling}"}
2022-07-26T10:52:06Z    DEBUG   controllers.webhookbasedautoscaler      Found 1 HRAs by key     {"key": "engineering/group/prod-scaling"}
2022-07-26T10:52:06Z    DEBUG   controllers.webhookbasedautoscaler      no repository/organizational/enterprise runner found    {"event": "check_run", "hookID": "326", "delivery": "fd99f650-0cd0-11ed-8638-58a055482577", "repository": "engineering/ReleaseTesting", "organization": "engineering", "enterprise": "xxxxxxxx"}
2022-07-26T10:52:06Z    DEBUG   controllers.webhookbasedautoscaler      Scale target not found. If this is unexpected, ensure that there is exactly one repository-wide or organizational runner deployment that matches this webhook event  {"event": "check_run", "hookID": "326", "delivery": "fd99f650-0cd0-11ed-8638-58a055482577", "checkRun.status": "completed", "action": "completed"}`


`apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: engineering-runner-prod
  namespace: actions-runner-engineering
spec:
  template:
    spec:
      organization: engineering
      # serviceAccountName: actions-runner
      labels:
        - scale
        - prod
      group: prod-scaling
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: engineering-runner-prod-autoscaler
  namespace: actions-runner-engineering
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    name: engineering-runner-prod
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"`

So I tried the most simple approach from the docs. Now runner is in runner group, has specific tags, does that have to do anything with it? 

As the idea is for us to have in one org multiple runner groups per team basically, so we can divide permissions, so i have multiple runner controllers and that all works fine and nice. But now i wanted to test out scaling to limit the number of runners just waiting idle. I get the above.

**Comment by toast-gear** [comment]
Scale target not found. If this is unexpected, ensure that there is exactly one repository-wide or organizational runner deployment that **matches this webhook event**  {"event": "check_run"

```yaml
 scaleUpTriggers:
    githubEvent:
    workflowJob: {} <---- your configured event
    duration: "30m"
```

**Comment by UrosCvijan** [comment]
Hmmm, 
I understood from this example that I just need to leave it empty there:

https://github.com/actions-runner-controller/actions-runner-controller#example-1-scale-on-each-workflow_job-event

And he will pick up anything that comes in

**Comment by toast-gear** [comment]
> And he will pick up anything that comes in

It will pick up the configured event i.e. the child key of the `githubEvent:` key e.g.:

Look for the workflow_job event:
```yaml
githubEvent:
      workflowJob: {}
```

Look for the check_run event:
```yaml
githubEvent:
      checkRun: 
        ...
```

Look for the pull_request event:
```yaml
githubEvent:
      pullRequest 
        ...
```

We are removing all event type other than workflow_job so you should only send the `workflow_job` event and configure for that trigger (which you've done already), see https://github.com/actions-runner-controller/actions-runner-controller/issues/1607 for the why

**Comment by UrosCvijan** [comment]
So did i set it up correctly for the workflow_job event? I just took the example from the docs and try to replicate but for some reason it does not work. Is there something that I need to change for HRA to do the scaling of runners?

**Comment by toast-gear** [comment]
Your HRA looks correct, the controller logs suggest it's receiving `check_run` events: 

 2022-07-26T10:52:06Z DEBUG controllers.webhookbasedautoscaler Scale target not found. If this is unexpected, ensure that there is exactly one repository-wide or organizational runner deployment that matches this webhook event {"event": "check_run", "hookID": "326", "delivery": "fd99f650-0cd0-11ed-8638-58a055482577", "checkRun.status": "completed", "action": "completed"}

See the event key value:
```json
{"event": "check_run", "hookID": "326", "delivery": "fd99f650-0cd0-11ed-8638-58a055482577", "checkRun.status": "completed", "action": "completed"}
```

This is a misalignment between your configured webhook on github.com and your HRA, you need to take a look at your webhooks configuration on github.com.

**Comment by UrosCvijan** [comment]
Ok, you were correct, i tried check_run event and it worked so went back to the webhook, didn't include workflow jobs event to be picked up. But now I have this other problem or that is behavior that is normal?

Basically as soon as the jobs finished all runners were killed (pods), and all runners are now in offline mode.  I understood that they should stay online for the scaleDownDelaySecondsAfterScaleOut: 300 amount of time and then they get removed one by one and still they should be removed from my list of runners. Or I misunderstood that?

**Comment by toast-gear** [comment]
> Ok, you were correct, i tried check_run event and it worked so went back to the webhook, didn't include workflow jobs event to be picked up. But now I have this other problem or that is behavior that is normal?

Use the `workflow_job` webhook event only, all other webhook events are deprecated and are going to get removed soon from ARC entirely. We are going to update the docs to reflect this so people stop using them soon.

> Basically as soon as the jobs finished all runners were killed (pods), and all runners are now in offline mode. I understood that they should stay online for the scaleDownDelaySecondsAfterScaleOut: 300 amount of time and then they get removed one by one and still they should be removed from my list of runners. Or I misunderstood that?

Sounds odd but I would first move over to the `workflow_job` event. If you are still having odd behaviour raise a new issue with the full details of deployment, yaml, logs etc

**Comment by UrosCvijan** [comment]
Yeah, yeah, i moved to workflow_job event and still I have 5 runners that are in offline mode.. I will wait some more to see, but they got removed as soon as the jobs completed and are in offline mode.. I will run again the same test workflow to see if It will create new 5 runners and then leave them offline as well after its finished.  If it does i will go with new issue with all the details..

**Comment by UrosCvijan** [comment]
There was some weird behavior yesterday, so i will delete everything today and if i find some time bring all from zero so i have a clean slate and then can tell all the steps. But yesterday for example, after all runners were killed (as soon as they finished their jobs) they were offline, and still are, but like 5 minutes later new 4 runners were spun up and there was no action called, no webhook, nothing. And then after some time, i didn't see when, they were removed and those were not left in offline state. 
So i will see to bring it all from zero and see how it behaves so i can tell you all the steps that i did if it happens again.

**Comment by mumoshu** [comment]
> they were offline, and still are

ARC tries its best to call the "Remove Runner" GitHub Actions API on every runner being shut down so that there will (ideally) be no runners hang "offline". If it failed to do so or GitHub Actions failed to handle the API call at all, you might end up with dangling "offline" runners that you have to clean up manually. I guess, though, it's very rare 🤔 

> 5 minutes later new 4 runners were spun up and there was no action called

What were the desired replicas of your RunnerDeploymeyment at that time? Also- did the desired replicas went down to 4 from a larger value when it brought up the new 4 runners for no use?
A possible scenario would be that your loadbalancer, network, or ARC's github webhook server exposed to the Internet somehow went wild and it was unable to fully receive or handle all the webhook events sent by GitHub around that time.
If it did receive `workflow_job` events of `status=queued` 5 times and then received only 1 out of 5 `workflow_job` events of status `completed`, ARC has no way to know that it needed to scale the desired replicas down from 4 to 0 so it will end up creating 4 runners (eventually redundant). As you observed, ARC will eventually fix the skew so in that sense ARC worked as designed.

**Comment by UrosCvijan** [comment]
Ok, sorry about me not being back on this, I was put to do other things :) So first thing I should mention that I am doing all of this on cluster which is older version 1.20.11. 
I think I found out why the runners were left offline (I had my own image that was created from your image, where we added some packages) so now I am using the regular latest actions-runner image and I don't have runners staying offline anymore. But they still are removed as soon as the jobs are done. 

```
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: engineering-runner-prod-autoscaler
  namespace: actions-runner-engineering
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    name: engineering-runner-prod
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"
```
Did I understood correctly, they should stay for as long as scaleDownDelaySecondsAfterScaleOut is set and then scale them 1 by 1? Or because i am using workflowJob github event, he HRA scales it down cause it got event that job is completed? 

But first question of them all, should we spend time on this as the version of the cluster is 1.20.11?  If not, I understand completely and will look at it when we upgrade, and come back to you, but If this is not supposed to be happening even in this version, then we can take a look at it together. I can share screen if it would make things faster.
