### ISSUE TITLE
autoscaler does not seem to scale to zero

### ISSUE THREAD

**Issue by amircodota** [actions-runner-controller/actions-runner-controller#550]
Hi

I've recently setup a `RunnerDeployment` with a `HorizontalRunnerAutoscaler`.
On the `HorizontalRunnerAutoscaler`, I've set 

```
  minReplicas: 0
  maxReplicas: 45
``` 

The autoscaling is based on `TotalNumberOfQueuedAndInProgressWorkflowRuns`, and I've setup a github webhook on top.

Everything seems to be working, except for one thing - the deployment is never scaled down to zero. There is always at least one runner.

Looking at the log, I see this

`2021-05-17T12:25:32.112Z	DEBUG	actions-runner-controller.horizontalrunnerautoscaler	Calculated desired replicas of 1	{"horizontalrunnerautoscaler": "default/acpl-runners-autoscaler", "suggested": 0, "reserved": 0, "min": 1, "cached": 0, "max": 45}`

It is unclear to me why the `min` value is set to 1. I do not have `ScheduledOverrides`, but maybe it is something around there?

Thanks
Amir

**Comment by toast-gear** [comment]
Controller version deployed?
Method of deployment?
Could we see a full copy of your `RunnerDeployment` and `HRA` combo? Please redact anything sensitive

**Comment by amircodota** [comment]
versions: 
`manager: summerwind/actions-runner-controller:v0.18.2, kube-rbac-proxy: quay.io/brancz/kube-rbac-proxy:v0.8.0`

Deployed via helm: 
`helm upgrade -n actions-runner-system actions-runner-controller actions-runner-controller/actions-runner-controller --set "githubWebhookServer.enabled=true" --set "githubWebhookServer.service.type=NodePort" --set "syncPeriod=1m"`

YAML:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: acpl-runners
spec:
  template:
    spec:
      image: gcr.io/proud-maker-166101/tabnine-actions-runner:latest
      repository: codota/acpl-paid
      resources:
        limits:
          cpu: 15
          memory: 13Gi
        requests:
          cpu: 15
          memory: 12Gi
      labels:
        - high-cpu-runner
      tolerations:
      - effect: NoSchedule
        key: only-runners
        operator: Equal
        value: "true"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: acpl-runners-autoscaler
spec:
  scaleTargetRef:
    name: acpl-runners
  minReplicas: 0
  maxReplicas: 45
  scaleDownDelaySecondsAfterScaleOut: 60
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
    amount: 1
    duration: "1m"
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - codota/acpl-paid
~                       
```
