### ISSUE TITLE
HorizontalRunnerAutoScaler does not scale to 0

### ISSUE THREAD

**Issue by rad-ed** [actions-runner-controller/actions-runner-controller#558]
I am unable to produce replica count of 0 while using a horizontal auto scaler, despite following the requirements in the documentation.

Here is an excerpt from the manifest of my HorizontalRunnerAutoScaler

```
maxReplicas: 5
metrics:
  - ScaleDownAdjustment: '1'
    ScaleUpAdjustment: '1'
    scaleDownThreshold: '0.3'
    scaleUpThreshold: '0.75'
    type: PercentageRunnersBusy
minReplicas: 0
scaleTargetRef:
  name: foobar-deployment
scaleUpTriggers:
  - amount: 1
    duration: 1m
    githubEvent:
      checkRun:
        status: queued
        types:
          - created
```
To reproduce this error, create a HorizontalRunnerAutoScaler with the PercentageRunnersBusy metric and GitHub Webhook scaling metric.

However, I have reproduced this bug with just a Github Webhook, or any other configuration- the HorizontalRunnerAutoScaler has never scaled down to 0 nodes in my observation.

My runner still scales normally and responds to the webhook being called, albeit with significant lag before scaling back down from the webhook.

**Environment**
 - Controller Version: 5309b1c02c3dd23603ca1699cd209d662312c0f0
 - Deployment Method: Helm
