### ISSUE TITLE
actions-runner-dind fails to setup MTU on docker0 interface

### ISSUE THREAD

**Issue by Vladyslav-Miletskyi** [actions-runner-controller/actions-runner-controller#588]
**Describe the bug**
actions-runner-dind fails to setup MTU on docker0 interface during the startup process due to the missing package net-tools

**To Reproduce**
1. Create next object
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runner-deployment
spec:
  template:
    spec:

      dockerdWithinRunnerContainer: true
      dockerEnabled: false
      dockerMTU: 1450

      image: summerwind/actions-runner-dind:v2.278.0-ubuntu-20.04
```

2. Check pod's logs

```
[Mon May 31 11:01:17 UTC 2021] [INFO] [/usr/local/bin/startup.sh] Using /etc/docker/daemon.json with the following content
{
  "mtu": 1450
}
[Mon May 31 11:01:17 UTC 2021] [INFO] [/usr/local/bin/startup.sh] Using /etc/supervisor/conf.d/dockerd.conf with the following content
[program:dockerd]
command=/usr/local/bin/dockerd
autostart=true
autorestart=true
stderr_logfile=/var/log/dockerd.err.log
stdout_logfile=/var/log/dockerd.out.log
environment=DOCKERD_ROOTLESS_ROOTLESSKIT_MTU=1450
[Mon May 31 11:01:17 UTC 2021] [INFO] [/usr/local/bin/startup.sh] Starting supervisor
[Mon May 31 11:01:17 UTC 2021] [INFO] [/usr/local/bin/startup.sh] Waiting for processes to be running
[Mon May 31 11:01:17 UTC 2021] [INFO] [/usr/local/bin/startup.sh] Process dockerd is not running yet. Retrying in 1 seconds
[Mon May 31 11:01:17 UTC 2021] [INFO] [/usr/local/bin/startup.sh] Waited 0 seconds of 30 seconds
[Mon May 31 11:01:18 UTC 2021] [INFO] [/usr/local/bin/startup.sh] Process dockerd is not running yet. Retrying in 1 seconds
[Mon May 31 11:01:18 UTC 2021] [INFO] [/usr/local/bin/startup.sh] Waited 1 seconds of 30 seconds
[Mon May 31 11:01:19 UTC 2021] [INFO] [/usr/local/bin/startup.sh] dockerd is running
/usr/local/bin/startup.sh: line 63: ifconfig: command not found
```

3. Check mtu values via ip a (ifconfig is not available)

```bash
ip a
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:32:1a:c1:ce brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```

**Expected behavior**
No error message in logs and MTU is set to the expected value (1450, in this example)

**Environment (please complete the following information):**
 - Controller Version 2.278.0
 - Deployment Method Helm
 - Helm Chart Version 0.11.0
 - Docker Image summerwind/actions-runner-dind:v2.278.0-ubuntu-20.04
