### ISSUE TITLE
QUESTION: What is terminating the DinD container?

### ISSUE THREAD

**Issue by jwalters-gpsw** [actions-runner-controller/actions-runner-controller#616]
About 5% of the time my workflows are failing because the workspace is "dirty" (contain the contents of a prior checkout which causes an `untar` to fail). Because it's inconsistent when it happens (sometimes the job succeeds, sometimes it doesn't) I'm guessing it must be a timing issue with the restarts of the pod's containers. I thought I would modify the runner container wait on the DinD container restart but couldn't figure out what was triggering the DinD container to restart.

Something in runsvc.sh?

Log of the DinD container shutdown below.

```
runner
Runner listener exited with error code 0
runner
Runner listener exit with 0 return code, stop the service, no retry needed.
docker
time="2021-06-08T22:14:39.462407666Z" level=info msg="Processing signal 'terminated'"
docker
time="2021-06-08T22:14:39.463396975Z" level=info msg="Daemon shutdown complete"
docker
time="2021-06-08T22:14:39.463454993Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=moby
docker
time="2021-06-08T22:14:39.463507528Z" level=info msg="stopping healthcheck following graceful shutdown" module=libcontainerd
docker
time="2021-06-08T22:14:39.463605980Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
docker
rpc error: code = Unknown desc = Error: No such container: 10da79bf7edf42ac2629bea2a8dd9b4e603357090b05f62c29ac5628e53a308e
```

**Comment by jwalters-gpsw** [comment]
Not doing anything special with the controller Helm install or the RunnerDeployment. No changes to the controller install. It happens a small percentage of the time. I have also tried to move the runner to our private docker repo (to avoid rate limit issue) and it still occasionally happens. Here is the RunnerDeployment:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: v0.0.1-runnerdeployment
spec:
  replicas: 6
  template:
    spec:
      group: OrgGroup
      labels:
      - stable
      - v0.0.1
      organization: xxx
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "600m"
          memory: "300Mi"

```
