### ISSUE TITLE
Question: What is the proper way of enabling webhooks?

### ISSUE THREAD

**Issue by frbk** [actions-runner-controller/actions-runner-controller#636]
I have been trying to enable webhook server but having issues with secrets.
What is this secret `github_webhook_secret_token`? Can I re-use secrets used in manager?(This one `controller-manager`). I have tried to create that secret by adding my PAT but get this error:
```
Error: Client creation failed. authentication failed: using private key of size 53 (/etc/actions-runner-controller/github_app_private_key...): could not parse private key: Invalid Key: Key must be PEM encoded PKCS1 or PKCS8 private key
```
Created secret with this:
```
kubectl create secret generic github-webhook-server -n github \
--from-literal=github_webhook_secret_token=<my pat token>
```
Here is my webhook config:
```
githubWebhookServer:
    enabled: true
    replicaCount: 1
    secret:
      create: false
      name: "github-webhook-server"
      ### GitHub Webhook Configuration
      # github_webhook_secret_token: ""
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""
    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""
```

**Comment by mumoshu** [comment]
> Can I re-use secrets used in manager?(This one controller-manager). I have tried to create that secret by adding my PAT but get this error:

Nope. I'd suggest reading https://docs.github.com/en/developers/webhooks-and-events/webhooks/creating-webhooks#secret - you usually provide a webhook token you've configured on GitHub to actions-runner-controller's github webhook server for payload verification.

If you don't need payload verification you can just omit it.

**Comment by frbk** [comment]
Thanks for the suggestions. Was able to get it to work after going over the docs. Also, here is an example of working ingress for reference:
```
ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # nginx.ingress.kubernetes.io/secure-backends: "true"
      hosts:
        - host: url.com
          paths:
          - path: /actions
      tls:
        - secretName: actions
          hosts:
            - url.com
```
