### ISSUE TITLE
Help wanted running Kind

### ISSUE THREAD

**Issue by rverma-nsl** [actions-runner-controller/actions-runner-controller#640]
We are trying to run kind within our self-hosted runners 
```
- name: Setup Kubernetes        
  uses: helm/kind-action@main      
```
https://github.com/nslhb/services.nslhub.com/blob/arm64-kind/.github/workflows/e2e.yaml

But its failing  with exception
```
Command Output: docker: Error response from daemon: failed to copy xattrs: failed to set xattr "security.selinux" on /var/lib/docker/volumes/d0b1f6540aef735a6be4f69ffc2951804b1a3f4f7660522194b32f17c56061e5/_data: permission denied.
```
https://github.com/nslhb/services.nslhub.com/runs/2870656628?check_suite_focus=true

The runners are running on eks 1.20 which have containerd runtime. Runners are using below config
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: self-hosted
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1000
      ephemeral: false
      dockerEnabled: false
      dockerdWithinRunnerContainer: true
      image: summerwind/actions-runner-dind
      serviceAccountName: ci
```
Tried with docker Enabled true and dind image too, but no success.
