### ISSUE TITLE
Autoscale PercentageRunnersBusy based on Deployment

### ISSUE THREAD

**Issue by FalconerTC** [actions-runner-controller/actions-runner-controller#672]
**Describe the bug**
I'm running three `RunnerDeployments` in my cluster, all in the namespace `actions-runners`. Each deployment has a separate `HorizontalRunnerAutoscaler` using `PercentageRunnersBusy` as the metric. I noticed recently that all thee deployments seem to be autoscaling together

```
❯ kubectl get HorizontalRunnerAutoscaler
NAME                       MIN   MAX   DESIRED
deployment1-autoscaler   1     12    4
deployment2-autoscaler   2     12    4
deployment3-autoscaler   2     12    4
...
❯ kubectl get HorizontalRunnerAutoscaler
NAME                       MIN   MAX   DESIRED
deployment1-autoscaler   1     12    2
deployment2-autoscaler   2     12    2
deployment3-autoscaler   2     12    2
```

After checking out the docs, it seems this is because `PercentageRunnersBusy` is based on the namespace, not the status of the `scaleTargetRef`

>The HorizontalRunnerAutoscaler will poll GitHub based on the configuration sync period for the number of busy runners which live in the RunnerDeployment's namespace and scale based on the settings

Any way to use `PercentageRunnersBusy` with multiple runners in the same namespace? Or should I use a different metric?

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**Comment by toast-gear** [comment]
For clarities sake could you post your RunnerDeployment specs too so it's clear how you are currently using the metric? Cheers

**Comment by FalconerTC** [comment]
Sure

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  labels:
    app: github-actions-runners
  name: deployment1
  namespace: actions-runners
spec:
  replicas: 4
  selector:
    matchLabels:
      app: github-actions-runners
      app.kubernetes.io/managed-by: Helm
  template:
    spec:
      image: <runner-image>
      imagePullSecrets:
      - name: image-pull-secret
      labels:
      - gke
      - deployment1
      - default
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
      organization: <org>
      resources:
        limits:
          memory: 4Gi
        requests:
          cpu: 850m
          memory: 2Gi
      serviceAccountName: runners1
      tolerations:
      - effect: NoSchedule
        key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 10
```

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: deployment1-autoscaler
  namespace: actions-runners
spec:
  maxReplicas: 12
  metrics:
  - ScaleDownAdjustment: "1"
    ScaleUpAdjustment: "2"
    scaleDownThreshold: "0.3"
    scaleUpThreshold: "0.75"
    type: PercentageRunnersBusy
  minReplicas: 2
  scaleTargetRef:
    name: deployment1
```

**Comment by toast-gear** [comment]
Cheers for providing them

2 things:

1. Don't specify the `replicas:` attribute if your `RunnerDeployment` kinds are backed by an `HRA`, it causes various issues. We do say in the docs to not include it in your spec: `Important!!! We no longer include the attribute replicas in our RunnerDeployment if we are configuring autoscaling!`

2. The `PercentageRunnersBusy` metric is pull based, what this means at every sync period (default is 10 mins) the controller will go and calculate the capacity reservations and will scale the runners up or down based on the thresholds you've set. If all of your runner deployments are using the `PercentageRunnersBusy` metric then they will all calculate the required runner count at the same time and scale the referenced scale target within the constraints of the metric and replica count configuration. 

This will be the case regardless of which metric you use as they are both pull based i.e. the desired count is calculated every sync period.

Could you clarify what you mean exactly by:
```
not the status of the scaleTargetRef
```

**Comment by mumoshu** [comment]
```
  selector:
    matchLabels:
      app: github-actions-runners
      app.kubernetes.io/managed-by: Helm
```

@FalconerTC Shouldn't it have a unique set of labels per RunnerDeployment? Like `your.domain/runner-deployment-name: deployment1`, where `deployment1` can be `deployment2` or `deployment3` depending on the RunnerDeployment, so that you can differentiate runners between runner deployments.
