### ISSUE TITLE
How to use Docker containers from a private registry without a full trust chain

### ISSUE THREAD

**Issue by rajbos** [actions-runner-controller/actions-runner-controller#701]
We are pulling docker containers from a private (Artifactory) registry that doesn't have a full trust chain on its SSL certificates
Running the workflow gives us errors with this setup as the DinD setup doesn't know about the 
``` 
  /usr/local/bin/docker pull registry.artifactory.*****.com/node:lts
  Error response from daemon: Get https://registry.artifactory.******.com/v2/: x509: certificate signed by unknown authority
``` 
Our k8s setup (Rancher) has been setup so it can work with the registry, but the DinD setup has no idea yet.

Any guidance on how to pass things into a runner so that it either ignores the cert for this url (we could bake it into our own DinD container by creating the settings in `/etc/docker/daemon.json` for insecure registries or pass in the internal crt's for it?

**Comment by sledigabel** [comment]
a relatively easy way through would be to build your own DinD sidecar with the remote certificates built in the PKI?
I've not tested it but I don't see why that wouldn't work.

**Comment by rajbos** [comment]
> a relatively easy way through would be to build your own DinD sidecar with the remote certificates built in the PKI?
> I've not tested it but I don't see why that wouldn't work.

I was thinking that too, but hoped I could do something like passing some extra settings through k8s. Currently looking where I can tell the deployment to use our own DinD image, can't seem to find it. How do I pass in that information so that it get's picked up [here](https://github.com/actions-runner-controller/actions-runner-controller/blob/14564c7b8e0ad7adadcb18a41a15f831b580f931/main.go#L91) ? In the yaml file the runner image is passed in through `image`.

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: custom-runner
spec:
  repository: actions-runner-controller/actions-runner-controller
  image: YOUR_CUSTOM_DOCKER_IMAGE

```

**Comment by mumoshu** [comment]
@rajbos Hey! Our Runner API does not support setting a custom dockerd image yet

https://github.com/actions-runner-controller/actions-runner-controller/blob/29260549fa5f5d970cd3ccc73d76bdcfdcf0fb9d/api/v1alpha1/runner_types.go#L62-L69

You could try our new experimental RunnerSet API- you can override it via `image` field of a `container` whose name is `docker`- or try adding it to the Runner API.

**Comment by mumoshu** [comment]
@rajbos You can also specify it via controller's `--docker-image` flag.

**Comment by rajbos** [comment]
> @rajbos You can also specify it via controller's `--docker-image` flag.
That is for the runner image and not for the DinD image, right?

**Comment by mumoshu** [comment]
Nope. `--runner-image` is for runner image` and `--docker-image` is for what it says.

**Comment by toast-gear** [comment]
https://github.com/actions-runner-controller/actions-runner-controller/blob/14564c7b8e0ad7adadcb18a41a15f831b580f931/main.go#L91

See here for the description of each argument @rajbos

**Comment by rajbos** [comment]
Just to check: 
1. the --docker-image flag will only work with the RunnerSet API? 
2. And the RunnerSet currently supports statefull runners?
3. There is no way to get it into either a Runner or RunnerDeployment kind? Or I'd have to fork things and make the adjustments to pass in the DinD container?

I'm currently testing with a single runner:
``` yaml
# runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: gh-runner
spec:
  repository: robbos/testing-grounds
  image: xxxx.artifactory-xxxx.com/actions-runner
```

**Comment by mumoshu** [comment]
@rajbos 

> 1

No. It supports RunnerDeplyoment and Runner, too.

https://github.com/actions-runner-controller/actions-runner-controller/blob/c424d1afee693d0f2297df53d663f8a8137b9e51/controllers/runner_controller.go#L825

> 2

Yes

> 3

No. It should work, but if it doesn't work for you and you could somehow fix your issue, a  pull request would be welcomed!

**Comment by rajbos** [comment]
I've seen that, but it is not loaded from the spec it seems, like the runner image is:
https://github.com/actions-runner-controller/actions-runner-controller/blob/c424d1afee693d0f2297df53d663f8a8137b9e51/controllers/runner_controller.go#L574

Hence I expect that this will not work (but will test it out tomorrow to make sure)
``` yaml
# runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: gh-runner
spec:
  repository: robbos/testing-grounds
  image: xxxx.artifactory-xxxx.com/actions-runner
 dockerimage: xxxx.artifactory-xxxx.com/actions-dind
```

**Comment by rajbos** [comment]
I've tested things out. but it is still only downloading the normal dind image from docker hub :-(

Tested with this setup:
``` yaml
# runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: gh-runner
spec:
  repository: robbos/testing-grounds
  image: xxxx.artifactory-xxxx.com/actions-runner
  dockerimage: xxxx.artifactory-xxxx.com/actions-dind
```

And with this:
``` yaml
# runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: gh-runner
spec:
  repository: robbos/testing-grounds
  image: xxxx.artifactory-xxxx.com/actions-runner
  dockerimage: xxxx.artifactory-xxxx.com/actions-dind

  template:
    spec:
      containers:
      - name: docker
        image: xxxxx.artifactory-xxxxl.com/actions-runner-dind
```

**Comment by sledigabel** [comment]
I believe the dockerImage is a parameter of the controller itself.
I override it with helm when I run the controller:

```yaml
image:
  dindSidecarRepositoryAndTag: "xxxx.artifactory-xxxx.com/docker:20.10.7:dind"
```

**Comment by rajbos** [comment]
Hmm, that is interesting. I've deployed the controller with kubectl from here: [https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.18.2/actions-runner-controller.yaml](https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.18.2/actions-runner-controller.yaml). 

Can't find the property there to overwrite? Any help?

**Comment by sledigabel** [comment]
Certainly :-)

Line 7936 is the Deployment declaration, you can add a `--docker-image` to that:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager
  namespace: actions-runner-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --sync-period=10m
        - --docker-image=xxxx.artifactory-xxxx.com/docker:20.10.7:dind

```
