### ISSUE TITLE
action-runner has crashed loop with latest version.

### ISSUE THREAD

**Issue by h-r-k-matsumoto** [actions-runner-controller/actions-runner-controller#722]
**Describe the bug**
Suddenly runner pod has crashed loop after 2021-08-11.
I think `summerwind/actions-runner:latest` is not built correctly.

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

First o all , `summerwind/actions-runner:latest` cannot be started.

```bash
$ docker images |findstr  summerwind/actions-runner
summerwind/actions-runner                                                     latest         42c0cefce236   3 hours ago     788MB
$ docker run -it --rm summerwind/actions-runner:latest
standard_init_linux.go:228: exec user process caused: exec format error
$
```

I think `dump-init` doesnot install correctly.
```bash
$ docker run -it --rm --entrypoint '' summerwind/actions-runner:latest /bin/sh
$ cat  /usr/local/bin/dumb-init
Not Found$
```

**Expected behavior**
It can be started normally.

**Screenshots**
Nothing.

**Environment (please complete the following information):**
 - Controller Version: 0.18.2
 - Deployment Method: Kustomize 

**Additional context**
Nothing

**Comment by h-r-k-matsumoto** [comment]
There is the code below.
https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Dockerfile#L51
```bash
    && curl -L -o /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/dumb-init_${DUMB_INIT_VERSION}_${ARCH} \
```
This is run as follows:

```bash
  && curl -L -o /usr/local/bin/dumb-init  https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_amd64
```

However `dumb-init_1.2.5_amd64` file is not exists in [Yelp/dumb-init/releases/tag/v1.2.5](https://github.com/Yelp/dumb-init/releases/tag/v1.2.5)

**Comment by h-r-k-matsumoto** [comment]
A Condition with downloading dumb-init is wrong.
https://github.com/Yelp/dumb-init/releases/tag/v1.2.3
> x86_64 (previously amd64)
> aarch64 (previously arm64)
> ppc64le (previously ppc64el)

if amd64, $ARCH should be set `x86_64` .

**Comment by berabot** [comment]
I'm seeing mine has crashed as well. Is there an interim workaround to get it running again before the PR is merged?

**Comment by AndreaSoldino-TomTom** [comment]
I reverted back to an older image, e.g.
```yaml
# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: serviceplatform
  namespace: runners
spec:
  replicas: 1
  template:
    spec:
      organization: redacted
      image: summerwind/actions-runner:v2.279.0-ubuntu-20.04-743e6d6
```
You can find a full list of images on docker hub
