### ISSUE TITLE
Unable to get AutoScaling work

### ISSUE THREAD

**Issue by vikas027** [actions-runner-controller/actions-runner-controller#726]
**Describe the bug**
I am new to the controller and have set up the hosted runners with custom images and IRSA on my EKS account, all works fine so far :). But I am not sure if I understanding how autoscaling works or probably have not set it up correctly.

I have created a `HorizontalRunnerAutoscaler` and pushed a few commits to a git repository to make sure a few jobs are queued. I was expecting the HRA to trigger autoscaling but it didn't work. Not sure what I missing here :( 

**Checks**

- [x] My actions-runner-controller version (v0.12.7) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
As per the documentation:
- created a GitHub Organization application
- enable `githubWebhookServer` in the helm chart
- Create a `RunnerDeployment` (without replicas) and a `HorizontalRunnerAutoscaler` with a replica count
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
spec:
  template:
    spec:
      serviceAccountName: github-actions-runner
      organization: my-org
      ephemeral: true
      image: 1111111111.dkr.ecr.us-east-1.amazonaws.com/github-actions-runner:latest
      dockerEnabled: false

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: runner-deployment
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.3'
    scaleUpAdjustment: 2
    scaleDownAdjustment: 1
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
    amount: 1
    duration: "5m"
```
- expose the service `actions-runner-controller-github-webhook-server` externally https://github-runner-webhook.<my_domain>
- add the webhook in the repository (e.g. https://github-runner-webhook.<my_domain>/actions/) and make sure it is green

**Expected behaviour**
I was expecting that controller will watch the jobs queue in the repository and scale-up automatically.

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version: 0.19.0
 - Deployment Method: Helm
 - Helm Chart Version: 0.12.7

**Additional context**
- All deliveries in the git repos are green.
