### ISSUE TITLE
Ability to increase the number of pods based on the number of job queue

### ISSUE THREAD

**Issue by nyagnik** [actions-runner-controller/actions-runner-controller#760]
I have following configurations for actions runner controller.
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: actions-runner-autoscaler
  namespace: default
spec:
  maxReplicas: 20
  metrics:
  - scaleDownFactor: "0.5"
    scaleDownThreshold: "0.2"
    scaleUpFactor: "2"
    scaleUpThreshold: "0.5"
    type: PercentageRunnersBusy
  minReplicas: 2
  scaleTargetRef:
    name: evinvesttechsandbox-eks
   ```
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: evinvesttechsandbox-eks
  namespace: default
spec:
  replicas: 8
  template:
    spec:
      dockerEnabled: false
      group: evinvesttechsandbox-eks
      image: my-private-registry.org/repo/ev-actions-runner:v1
      imagePullSecrets:
      - name: registry-cred
      labels:
      - evinvesttechsandbox-eks
      organization: My-Corp
      resources:
        limits:
          cpu: "2"
          memory: 3Gi
        requests:
          cpu: "2"
          memory: 1Gi
  ```
When I trigger multiple workflow jobs in parallel, only some of them are executed initially, very gradually (and slowly), I see the number of pods gets increased as per the queue. 

Is there a way to configure actions runner to look for the number of jobs in the queue, provision that number of set of pods, so that all of them can be executed parallely? 

For now, when I started initially, it took 3 minutes to start 2 builds (out of 13 jobs in the queue)
![Screenshot from 2021-08-24 01-10-08](https://user-images.githubusercontent.com/81315302/130512959-d7db2528-7652-4976-ace0-11b78450c6ca.png)
I see only 4 pods were initialized
```bash
➜  ~ kubectl get pod
NAME                                  READY   STATUS    RESTARTS   AGE
evinvesttechsandbox-eks-mmzg2-2hkrl   0/1     Pending   0          20s
evinvesttechsandbox-eks-mmzg2-8bg4t   0/1     Pending   0          20s
evinvesttechsandbox-eks-mmzg2-jq8d2   1/1     Running   0          153m
evinvesttechsandbox-eks-mmzg2-mbz4p   1/1     Running   0          153m
```
After few mins, I can see the number of pods growing as per the number of jobs, one by one gradually.
May I know if we can optimize and start the set of pods at the same time, without having to wait?
