### ISSUE TITLE
Organization RunnerDeployment with webhook-based autoscaling only for certain repositories

### ISSUE THREAD

**Issue by Tarasovych** [actions-runner-controller/actions-runner-controller#765]
**Describe the solution you'd like**
I'd like to use an autoscaling for organization-based RunnerDeployment which will be limited for certain organization repositories.
Example:
1) organization `foo`
2) repositories
    - `foo/bar`
    - `foo/baz`
    - `foo/example-repo`
```yaml
kind: RunnerDeployment
metadata:
   name: myrunners
spec:
  organization: foo
---
kind: HorizontalRunnerAutoscaler
spec:
  scaleTargetRef:
    name: myrunners
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
    amount: 1
    duration: "5m"
```
The deployment above will scale based on `check_run` events for all organization repositories (reference: https://github.com/actions-runner-controller/actions-runner-controller/blob/master/controllers/horizontal_runner_autoscaler_webhook.go#L403).
I'd like to configure `HorizontalRunnerAutoscaler` so only certain repository list could trigger autoscaling, e. g.
```yaml
kind: HorizontalRunnerAutoscaler
spec:
  scaleTargetRef:
    name: myrunners
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
    amount: 1
    duration: "5m"
    repositories: ["baz", "bar"] # <---
```

**Describe alternatives you've considered**
Create `RunnerDeployment` separately for each repository
