### ISSUE TITLE
Unable to autoscale runners to 0 

### ISSUE THREAD

**Issue by nicon89** [actions-runner-controller/actions-runner-controller#769]
**Describe the bug**
I'm trying to configure autoscaling of runners to 0 using HorizontalRunnerAutoscaler with metrics:
```
  metrics:
  - scaleDownAdjustment: 1
    scaleDownThreshold: "0.3"
    scaleUpAdjustment: 2
    scaleUpThreshold: "0.75"
    type: PercentageRunnersBusy
  - repositoryNames:
    - xxx/yyy
    type: TotalNumberOfQueuedAndInProgressWorkflowRuns
```

According to README:

> A correctly configured TotalNumberOfQueuedAndInProgressWorkflowRuns can return non-zero desired replicas even when there are no runners other than registration-only runners, hence the PercentageRunnersBusy + TotalNumberOfQueuedAndInProgressWorkflowRuns configuration makes scaling from zero possible.

Can you please share example running configuration to scale to/from 0?

**Checks**

- [x] My actions-runner-controller version (v0.19.0) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**Expected behavior**
Scale to 0 when there are no queued and in progress jobs.

**Environment (please complete the following information):**
 - Controller Version [0.19.0]
 - Deployment Method [Kustomize ]

**Additional context**
Thanks in advance :)

**Comment by nicon89** [comment]
@mumoshu: sync-interval is set to 60 seconds and unfortunately it still doesn't scale down:
```
2021-08-31T10:16:23.623Z        DEBUG   actions-runner-controller.horizontalrunnerautoscaler    Calculated desired replicas of 3        {"horizontalrunnerautoscaler": "actions-runner-system/runner-autoscaler", "suggested": 21, "reserved": 0, "min": 0, "max": 3}
2021-08-31T10:16:23.636Z        DEBUG   actions-runner-controller.horizontalrunnerautoscaler    Calculated desired replicas of 4        {"horizontalrunnerautoscaler": "actions-runner-system/runner-kaniko-autoscaler", "suggested": 21, 
"reserved": 0, "min": 0, "cached": 21, "max": 4}
2021-08-31T10:16:23.636Z        DEBUG   actions-runner-controller.horizontalrunnerautoscaler    Calculated desired replicas of 3        {"horizontalrunnerautoscaler": "actions-runner-system/runner-autoscaler", "suggested": 21, "reserved": 0, "min": 0, "cached": 21, "max": 3}
```

All jobs finished half hour ago and runners are showing as idle.
scaleDownDelaySecondsAfterScaleOut is set to 60.

What else can I check?

**Comment by nicon89** [comment]
In lgos I can see:
```
2021-08-31T13:13:31.069Z        ERROR   controller-runtime.controller   Reconciler error        {"controller": "horizontalrunnerautoscaler-controller", "request": "actions-runner-system/runner-kaniko-autoscaler", "error": "invalid HRA Spec: Metrics[0] of TotalNumberOfQueuedAndInProgressWorkflowRuns cannot be combined with Metrics[1] of PercentageRunnersBusy: The only allowed combination is 0=PercentageRunnersBusy and 1=TotalNumberOfQueuedAndInProgressWorkflowRuns"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
```
Configuration:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-kaniko-autoscaler
spec:
  scaleTargetRef:
    name: runner-kaniko
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 0
  maxReplicas: 4
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - xxx/yyy
  - type: PercentageRunnersBusy
```

**Comment by nicon89** [comment]
I changed order of metrics in HRA like this:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-kaniko-autoscaler
spec:
  scaleTargetRef:
    name: runner-kaniko
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 0
  maxReplicas: 4
  metrics:
  - type: PercentageRunnersBusy
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - xxx/yyy

```
 and it's a bit better now:
```
2021-08-31T13:21:46.221Z        DEBUG   actions-runner-controller.horizontalrunnerautoscaler    Calculated desired replicas of 2        {"horizontalrunnerautoscaler": "actions-runner-system/runner-kaniko-autoscaler", "suggested": 2, "reserved": 0, "min": 0, "cached": 2, "max": 4}
2021-08-31T13:21:46.221Z        DEBUG   controller-runtime.controller   Successfully Reconciled {"controller": "horizontalrunnerautoscaler-controller", "request": "actions-runner-system/runner-kaniko-autoscaler"}
2021-08-31T13:21:46.221Z        DEBUG   actions-runner-controller.horizontalrunnerautoscaler    Calculated desired replicas of 3        {"horizontalrunnerautoscaler": "actions-runner-system/runner-autoscaler", "suggested": 3, "reserved": 0, "min": 0, "cached": 3, "max": 3}
```
(it scaled from 5 to 3 in one case and from 5 to 2 in other case).
I'm not sure though why it's not scaling to 0, though. There's no jobs running/queued.

**Comment by nicon89** [comment]
It finally scaled down all containers to 0, but it took around hour for some reason.

**Comment by mumoshu** [comment]
Ah, so the error message seems to be pointing it out.

Please try:

```
  metrics:
  - type: PercentageRunnersBusy
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - xxx/yyy
```

Apparently `PercentageRunnersBusy` needs to be in the first place.

**Comment by mumoshu** [comment]
@nicon89 Could you check log messages containing `Suggested desired replicas of`? Those are for logging suggested numbers without caching.

**Comment by nicon89** [comment]
I think it works now correctly - I was confusing syncInterval with scaleDownDelaySecondsAfterScaleOut.
It scales down to 0 now in around 10 minutes after finishing all jobs.
One thing that I don't understand is why it creates a new runner after finishing all jobs - this runner usually stands for few minutes and then stops.

**Comment by nicon89** [comment]
@mumoshu one more question:
is there a way to control which runners will be started depending on the label of a new job created?
I have a situation where I have 2 HRA (one for docker builds and one for kaniko builds) installed in 2 different clouds (Azure and Google Cloud). That gives me in total 4 HRA.
All of these are labeled per branch - some jobs should be run in Azure and some in Google Cloud. Some should be run with dind and some with Kaniko executor.
When I push changes to a branch that have a workflow for GKE (labeled as "k8s-gke") it starts 4 runners (2 runners in Azure and 2 runners in GKE).
One runner is picking up the job and other 3 are wasting resources for a time of a build.

**Comment by mumoshu** [comment]
> When I push changes to a branch that have a workflow for GKE (labeled as "k8s-gke") it starts 4 runners (2 runners in Azure and 2 runners in GKE).

That's indeed odd!

Does your repo concurrently trigger other workflow runs for managed runners? If so that might be the issue.

`TotalNumberOfQueuedAndInProgressWorkflowRuns` by its definition gets messed up if you have e.g. one workflow for self-hosted and another for managed runners. GitHub API doesn't allow us to differentiate which workflow run triggers which runner(managed vs self-hosted). If the workflow run gets pending while waiting for a managed runner(again, not self-hosted one manager by actions-runner-controller) it adds up 1 desired replica. It isn't correct, but we have no way to avoid that until GitHub enhances the API.

**Comment by mumoshu** [comment]
> One thing that I don't understand is why it creates a new runner after finishing all jobs - this runner usually stands for few minutes and then stops.

@nicon89 If it stands for a few minutes then it might be just that RunnerDeployment's desired replicas isn't as low to terminate the runner 🤔

**Comment by nicon89** [comment]
> Does your repo concurrently trigger other workflow runs for managed runners? If so that might be the issue.
I have two workflows inside, one for building images using docker and one for building images using kaniko. Both are self-hosted.

Here's HRA config for both:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-autoscaler
spec:
  scaleTargetRef:
    name: runner
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 0
  maxReplicas: 3
  metrics:
  - type: PercentageRunnersBusy
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - xxx/yyy
```

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-kaniko-autoscaler
spec:
  scaleTargetRef:
    name: runner-kaniko
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 0
  maxReplicas: 4
  metrics:
  - type: PercentageRunnersBusy
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - xxx/yyy
```
