### ISSUE TITLE
webhook server: "cache contained <nil>, which is not an Object" when handling check_run event

### ISSUE THREAD

**Issue by invakid404** [actions-runner-controller/actions-runner-controller#776]
**Describe the bug**
When receiving a check_run event, the webhook server throws an error, which states the following:
```
ERROR controllers.Runner handling check_run event {"event": "check_run", "hookID": "xxxxxxxxx", "delivery": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "checkRun.status": "completed", "action": "completed", "error": "cache contained <nil>, which is not an Object"}
```

**Checks**

- [x] My actions-runner-controller version (v0.19.0) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Follow the install guide
2. Configure the Helm chart to start the Webhook server, expose it
3. Create a webhook in GitHub to listen for `check_run` events
4. Run a workflow to trigger an event
5. Observe the error in the Webhook server's logs

**Expected behavior**
I've configured a HorizontalRunnerAutoscaler to scale on a `check_run` event, so the expected behavior is for a new runner to be spun up.

**Environment (please complete the following information):**
 - Controller Version: 0.19.0
 - Deployment Method: Helm
 - Helm Chart Version: 0.12.7

**Additional context**
I've authenticated via an app with the following permissions:
```
Actions (read)
Checks (read)
Metadata (read)
Self-hosted runners (read / write)
```

This is the runner configuration I'm using:
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: senteca-runner
spec:
  template:
    spec:
      organization: senteca
      dockerdWithinRunnerContainer: true
      env:
        - name: STARTUP_DELAY_IN_SECONDS
          value: "10"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: senteca-runner-autoscaler
spec:
  scaleTargetRef:
    name: senteca-runner
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 0
  maxReplicas: 5
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
    amount: 1
    duration: "5m"
```

This is how my GitHub webhook looks like:
![image](https://user-images.githubusercontent.com/38114607/131342081-916b7603-c8cf-47be-9197-8b5a44886467.png)

Any hints as to what may be wrong on my end are welcome. Thanks in advance :^)
