### ISSUE TITLE
flag provided but not defined: --watch-namespace

### ISSUE THREAD

**Issue by rxa313** [actions-runner-controller/actions-runner-controller#782]
When installing via helm, I have the `singleNamespace: true` and `watchNamespace: "gitactions-xxx"` populated. I check in rancher the status of the manager and I'm seeing the error that the flag is provided but not defined.

I'm running v0.12.0 of the runner controller.

I checked the source code of the v0.12.0 and I can see the --watch-namespace feature, it's just not working as expected when installing. To be sure, I cleared all of my namespaces, crds, and all our of rancher and tried to do a clean install of the controller.

 - Controller Version: v0.12.0
 - Deployment Method: Helm

the watchNamespace feature is very important in running multiple organizations with different installation ID's. There is no documentation on how to get this working properly..

**Comment by mumoshu** [comment]
@rxa313 Hey! The controller version v0.12.0 is way too outdated that it doesn't support `--watch-namespace`

https://github.com/actions-runner-controller/actions-runner-controller/blob/v0.12.0/main.go#L73-L82

Could you try e.g. v0.19.0 which does support it?

https://github.com/actions-runner-controller/actions-runner-controller/blob/c424d1afee693d0f2297df53d663f8a8137b9e51/main.go#L98

**Comment by rxa313** [comment]
Hi @mumoshu , upgrading to version v0.19.0 did indeed fix that issue. 

I did reply to this discussion here [#505](https://github.com/actions-runner-controller/actions-runner-controller/discussions/505#discussioncomment-1255499)

How can I deploy the controller to multiple namespaces in one cluster? I believe that is how it's supposed to work when running multiple orgs? I just see an error that the ClusterRole is already assigned to a namespace (actions-runner-system)

Thanks for your help.

**Comment by mumoshu** [comment]
@rxa313 Could you share the exact error message you've seen?

Generally speaking, I think each installation of actions-runner-controller needs to have a dedicated serviceaccount in its namespace (say, actions-runner-system-foo and actions-runner-system-bar) and each serviceaccount needs to have a corresponding RoleBinding to bind the ClusterRole to each serviceaccount.

If running `helm install -n actions-runner-system-foo --set watchNamespace=foo ...` and `helm install -n actions-runner-system-bar --set watchNamespace-bar ...` doesn't work, maybe our chart is not supporting the use-case correctly?

If you could share exact errors you've seen and exact commands you've run, probably I can provide a better guidance (or idea)

**Comment by toast-gear** [comment]
@rxa313 A lot of the resource names get set based on the `fullnameOverride` values property (and `githubWebhookServer.fullnameOverride` property for the webhook server), I don't think there is a technical reason why multiple controllers can't live in the same namespace as long as the resources in the chart have unique names. Try setting this property (or both if you are using the webhook server) so that each install uses a unique prefix for resources.

**Comment by rxa313** [comment]
@toast-gear @mumoshu Thanks you for the insight and the suggestions. I'm going to try today to deploy the controller to two unique namespaces. I'll update you guys with my results.

**Comment by rxa313** [comment]
@toast-gear @mumoshu just wanted to update you both again. I was able to install the controller to a namespace `actions-runner-system-corp` which went fine and as expected. However when I try to install to a new namespace: `actions-runner-system-tag` I see the ClusterRole error i mentioned before.

Command executed: 
`helm install --namespace actions-runner-system-tag --wait actions-runner-controller actions-runner-controller/actions-runner-controller --set watchNamespace=dev-gitactions-tag -f values-np-tag.yml`

Error message: 
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "actions-runner-controller-proxy" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "actions-runner-system-tag": current value is "actions-runner-system-corp"`

**Comment by toast-gear** [comment]
Cheers for the update, you will be getting that error because there are cluster level roles, as a result namespace scoping won't help. The proxy role name is created by the helper class https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/templates/_helpers.tpl#L76

Provide a unique name for your install as described here https://github.com/actions-runner-controller/actions-runner-controller/issues/782#issuecomment-912766268

**Comment by rxa313** [comment]
> Cheers for the update, you will be getting that error because there are cluster level roles, as a result namespace scoping won't help. The proxy role name is created by the helper class https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/templates/_helpers.tpl#L76
> 
> Provide a unique name for your install as described here [#782 (comment)](https://github.com/actions-runner-controller/actions-runner-controller/issues/782#issuecomment-912766268)

@toast-gear https://github.com/actions-runner-controller/actions-runner-controller/issues/782#issuecomment-914250265

I tried your method for installing two controllers to the same namespace and they appear to overwrite each other.

**Comment by rxa313** [comment]
@toast-gear sorry for all the comments lol. But I was able to get the controller up in two separate namespaces by updating the `nameOverride` and the `fullnameOverride` for the helm deployment. (deployed without using webhook server btw).

I now have two namespaces both with their own actions-runner-controller in them, so thank you very much for help on that, @mumoshu as well.

 I'm still not sure why deploying multiple controllers to a single namespace didn't end up working.

**Comment by toast-gear** [comment]
> I'm still not sure why deploying multiple controllers to a single namespace didn't end up working.

yes that seems odd to me, were there specific resources that were getting overwritten?

**Comment by rxa313** [comment]
Could have been the `controller-manager` getting overwritten in the same namespace. I have two values.yml files with different configurations for GitHub Apps, so maybe applying one for one controller and the other with `auth secret: true` had the `controller-manager` overwriting when I installed the second values.yml file

**Comment by toast-gear** [comment]
are you able to try with `authSecret.name` set to something unique for each install?

**Comment by rxa313** [comment]
> Are you able to try with `authSecret.name` set to something unique for each install? I'd love to understand what the issue is and make sure the docs reflect reality

I tried this:
`authSecret:
    create: true
    name: controller-manager-tag`
  
  and then deployed to my namespace and it still overwrote the actions-runner-controller I had in there. Once the second controller was ready it removed the one I had initially.

**Comment by mumoshu** [comment]
@rxa313 Didn't you provided the same release name to multiple installations of the helm chart? You do need a different release, otherwise Helm can overwrite things.

In other words, Helm is designed to be unable to overwrite anything that isn't managed by the release. So, if you configured everything correctly, what you said can't happen(I think).

**Comment by rxa313** [comment]
@mumoshu help me understand what you mean by release name? When I tried to apply a new values.yml file to my namespace with a controller already present, I changed the` authSecret name`, `nameOverride`, and `fullnameOverride` properties. 

Was there something else I should change in my helm chart in order to keep both controllers in the same namespace?

**Comment by toast-gear** [comment]
https://helm.sh/docs/intro/using_helm/

```
A Release is an instance of a chart running in a Kubernetes cluster. One chart can often be installed many times into the same cluster. And each time it is installed, a new release is created. Consider a MySQL chart. If you want two databases running in your cluster, you can install that chart twice. Each one will have its own release, which will in turn have its own release name.
```

A `release` is a Helm concept, so for example:

`$ helm install happy-panda bitnami/wordpress`

This will install the `bitnami/wordpress` chart with the default values propeties and that install will be called `happy-panda`. I don't know off the top of my head. When you did your 2 installs did you provide a unique release name per install?

```
helm install actions-runner-controller-foo actions-runner-controller/actions-runner-controller -f values-foo.yaml
helm install actions-runner-controller-bar actions-runner-controller/actions-runner-controller -f values-bar.yaml
```

**Comment by rxa313** [comment]
When I executed my installs I did:
`helm upgrade --install --namespace actions-runner-system-foo --create-namespace              --wait actions-runner-controller actions-runner-controller/actions-runner-controller -f values.yml`

and

`helm upgrade --install --namespace actions-runner-system-bar --create-namespace              --wait actions-runner-controller actions-runner-controller/actions-runner-controller -f values-tag.yml`

**Comment by rxa313** [comment]
oops I misclicked the close button :D

**Comment by mumoshu** [comment]
In your commands, `actions-runner-controller` is the release name and `actions-runner-controller/actions-runner-controller` is the chart name.

When you run the two commands in sequence, the first command installs the chart with the values.yml as a release named `actions-runner-controller`.

The second command updates the same release with `values-tag.yml`, which basically explains your situation.

**Comment by rxa313** [comment]
@mumoshu ah, thank you for the explanation. I'll try to reinstall everything and change the release name like you and @toast-gear mentioned. From your explanation and my understanding, if I execute: 

`helm upgrade --install --namespace actions-runner-system-foo --create-namespace --wait actions-runner-controller-one actions-runner-controller/actions-runner-controller -f values.yml`

and then 

`helm upgrade --install --namespace actions-runner-system-foo --create-namespace --wait actions-runner-controller-two actions-runner-controller/actions-runner-controller -f values-tag.yml` this will stop them from overwriting?

I also just want to note that in my `values.yml` I did edit the `fullnameOverride` and `nameOverride` so that when I have the controllers running in their respective namespaces one namespace has a controller: `someName-actions-runner-controller` and then the other namespace has a controller `anotherName-actions-runner-controller` is this not the same as changing it in the helm installation command?

**Comment by mumoshu** [comment]
> is this not the same as changing it in the helm installation command?

If you are asking about the standard usage of Helm, you'd better try it yourself, as we aren't expertized in Helm than the Helm authors.

But yes, it should mostly be the same, as a standard helm chart usually uses the release name as the part of every resource name.

**Comment by rxa313** [comment]
@mumoshu @toast-gear I wiped my entire cluster of anything attached to my namespaces to ensure I started fresh. I then took the exact commands @toast-gear provided:

`helm install actions-runner-controller-foo actions-runner-controller/actions-runner-controller -f values-foo.yaml -n actions-runner-system
helm install actions-runner-controller-bar actions-runner-controller/actions-runner-controller -f values-bar.yaml -n actions-runner-system
`
And I was able to spin up two controllers in one instance without them overriding each other. Maybe I wasn't understanding correctly, but everything needs to be unique for these to work. I apologize, I'm very new with helm installations and kubernetes/rancher, so thank you for your patience.

It's important to note that when installing these controllers whether in the same namespace or in their own respective namespaces, you must make unique the `release name`, `authSecret`, `fullnameOverride` and `nameOverride` just to be safe and to ensure there are no conflicts, else you'll run into errors.

I have a question regarding the `serving-cert` of the controllers:

<img width="495" alt="Screen Shot 2021-09-09 at 9 04 53 AM" src="https://user-images.githubusercontent.com/74605500/132691051-59e97f6c-073b-48fd-a099-f8ef5aeebd91.png">

This value updates and switches back and forth between `actions-runner-controller-one-serving-cert` and `actions-runner-controller-two-serving-cert` is this functionality expected, or should these serving-certs be separate?
<img width="589" alt="Screen Shot 2021-09-09 at 9 07 10 AM" src="https://user-images.githubusercontent.com/74605500/132691412-b2bdcd67-0e70-4ff7-9ec3-819bbedf1880.png">


How it looks with two controllers below:
<img width="337" alt="Screen Shot 2021-09-09 at 9 06 37 AM" src="https://user-images.githubusercontent.com/74605500/132691310-4834974a-d7e1-4838-8dc0-a9e410b00e68.png">

**Comment by mumoshu** [comment]
> And I was able to spin up two controllers in one instance without them overriding each other.

Awesome! Glad to hear it finally worked for you.

> It's important to note that when installing these controllers whether in the same namespace or in their own respective namespaces, you must make unique the release name, authSecret, fullnameOverride and nameOverride just to be safe and to ensure there are no conflicts, else you'll run into errors.

Thanks for summarizing!
In an ideal world, I'd guess making the release name and authSecret name unique should be the minimal requirement. If you also need to use fullnameOverride and nameOverride even when the release name is unique, I might be missing something.

> This value updates and switches back and forth between actions-runner-controller-one-serving-cert and actions-runner-controller-two-serving-cert is this functionality expected, or should these serving-certs be separate?

This sounds like a red herring. Thanks for pointing it out. Maybe there's some hard-coded reference to `serving-cert` that needs to be unique across releases? 🤔

**Comment by mumoshu** [comment]
https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/templates/certificate.yaml#L15

https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/templates/_helpers.tpl#L108

Apparently, our chart does correctly generates a unique Certificate resource per release.

https://github.com/actions-runner-controller/actions-runner-controller/blob/a98729b08b86aac59613769a592cf71cf3523c90/charts/actions-runner-controller/templates/certificate.yaml#L24

https://github.com/actions-runner-controller/actions-runner-controller/blob/a98729b08b86aac59613769a592cf71cf3523c90/charts/actions-runner-controller/templates/deployment.yaml#L137

Probably we're unexpectedly letting cert-manager to "share" the secret named `webhook-server-cert` to flip between certs generated by Certificate resources of two releases? 🤔 

@rxa313 Could you try changing those two hard-coded `webhook-server-cert` with a call to template helper, so that it can be dynamically generated according to the release name, if possible?

Maybe we can safely reuse the helper function we use to generate the Certificate resource name dynamically.

So it might look like the below after the change in templates/certificate.yaml:

```
secretName: {{ include "actions-runner-controller.servingCertName" . }}
```

and in `templates/deployment.yaml`:

```
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "actions-runner-controller.servingCertName" . }}
```

**Comment by rxa313** [comment]
@mumoshu 

I believe you could be correct in assuming that the cert-manager is sharing the secrets. In my other rancher environment I have 3 namespaces, with their own controller and runners in them. I look at the logs from one controller to see how it's reconciling and spinning up runners as needed and I notice that somewhere the GitHub API is being shared because I can see `reconcile error` messages for GitHub API calls to incorrect organizations in the "manager". The runners are still scaling and working, just maybe not as smoothly as you've intended? I also can see in my logs that the API and org values are getting mixed up potentially because of this.

Example: 

`2021-09-10T12:29:17.436Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "horizontalrunnerautoscaler-controller", "request": "xxx-actions-runner-system/xxx-runner-autoscaler", "error": "failed to list runners: GET https://api.github.com/orgs/XXX/actions/runners?per_page=100: 404 Not Found []"}`

In the above example, the value after `/orgs/` is an organization that is in my GitHub Enterprise Server environment(github.xxx.com), when it should be my public GitHub organization.

`ERROR	actions-runner-controller.runner	Failed to get new registration token	{"runner": "xxx-rancher-runner-rrlh5-v8cx5", "error": "failed to create registration token: POST https://github.xxx.com/api/v3/orgs/xxx/actions/runners/registration-token: 404 Not Found []"}`

In the above example, my GitHub enterprise server value after `/orgs/` is pointing to the organization I have in public / enterprise cloud GitHub.

Could the `webhook-server-cert` be cause this mix up since they're potentially being shared?

I downloaded the latest `actions-runner-controller` from [HERE](https://github.com/actions-runner-controller/actions-runner-controller/releases/tag/actions-runner-controller-0.12.8) and updated those values as you instructed in the `certificate.yaml` and the `deploymeny.yaml` 
To install I tried `kubectl apply -f actions-runner-controller -n actions-runner-system`  and I got an errors:

`error validating "actions-runner-controller/Chart.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false`
`error validating "actions-runner-controller/values-np.yml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`

If I try to install those files individually using `kubectl apply -f certificate.yaml -n actions-runner-system` etc.. I get this:
`error: error parsing certificate.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"include \"actions-runner-controller.selfsignedIssuerName\" .":interface {}(nil)}`

How can I install the updates?

**Comment by toast-gear** [comment]
You need to use Helm to do the install / upgrade, don't manage Helm resources outside of Helm. You should clone the repository @ the latest chart version (don't clone HEAD as you will get unreleased and not fully tested stuff). 

1. Clone the repo and checkout the relevant Helm tag https://github.com/actions-runner-controller/actions-runner-controller/tags
2. Make the changes as described by mumoshu, namely, replacing the hardcoded `webhook-server-cert` name with the helper generated value `{{ include "actions-runner-controller.servingCertName" . }}`.
3. Do a helm install (making the previously mentioned properties unique to this install) with your chart source being the local copy you have on disk (not `actions-runner-controller/actions-runner-controller`)
4. Interrogate your cluster to see if the certificate secret is now unique

**Comment by rxa313** [comment]
Thanks @toast-gear 
@mumoshu 
<img width="1417" alt="Screen Shot 2021-09-10 at 1 50 09 PM" src="https://user-images.githubusercontent.com/74605500/132896214-04cf78ac-2dd2-4ebd-8a5a-a966a7d10655.png">

After installing using my local chart source with the updates, I checked the secrets and the random switching of the `webhook-server-cert` appears to have gone away. The above image is what I see when I look at the secrets. 

I have to do some more testing, but when I search the logs of the controller manager, I see `remote error: tls: bad certificate`

I'm going to wipe my cluster again of everything and clean install using my local chart to see if there is any fix.

**Comment by rxa313** [comment]
@mumoshu @toast-gear 

After wiping everything clean and reinstalling I was able to install using my local helm chart and the `tls: bad certificate` error is gone and I spun up a runner.

When I go to install my other helm release and I replaced the `values.yaml` file with new values as well, I'm seeing:  

```
Error: template: actions-runner-controller/templates/webhook_service.yaml:9:18: executing "actions-runner-controller/templates/webhook_service.yaml" at <.Values.service.type>: nil pointer evaluating interface {}.type
```

Perhaps further configurations need to be done?

**Comment by rofafor** [comment]
I'm able to deploy "successfully" multiple controllers into a single namespace with the mentioned chart fix. However, there are other issues explained in #807

**Comment by mumoshu** [comment]
@rxa313 Hey! Thanks for trying. Your last error seems to imply that you somehow missed setting any value for the `service` key in your `values.yaml`.

`<.Values.service.type>: nil pointer evaluating interface {}.type` basically means `service` in the expression `servicel.type` had no value.

**Comment by rxa313** [comment]
@mumoshu I copy and pasted my previous values.yml to my local configuration and the `service` key's are all set I believe.
Here's my values.yml

```
# Default values for actions-runner-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

labels: {}

replicaCount: 1

syncPeriod: 30s

# The controller tries its best not to repeat the duplicate GitHub API call
# within this duration.
# Defaults to syncPeriod - 10s.
#githubAPICacheDuration: 30s

# Only 1 authentication method can be deployed at a time
# Uncomment the configuration you are applying and fill in the details
authSecret:
  create: true
  name: controller-manager-one
  ### GitHub Apps Configuration
  github_app_id: "xx"
  github_app_installation_id: "xx"
  github_app_private_key: |
   xxxxx
  ### GitHub PAT Configuration
  # github_token: ""

image:
  repository: xxx.com/summerwind/actions-runner-controller
  tag: v0.19.0
  dindSidecarRepositoryAndTag: "xxx.com/xxx_docker:dind"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "actions-runner-one"
fullnameOverride: "actions-runner-controller-one"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 443

metrics:
  serviceMonitor: false
  port: 8443
  proxy:
    enabled: true
    image:
      repository: xxx.com/brancz/kube-rbac-proxy
      tag: v0.10.0

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Leverage a PriorityClass to ensure your pods survive resource shortages
# ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
# PriorityClass: system-cluster-critical
priorityClassName: ""

env:
  GITHUB_ENTERPRISE_URL: "https://github.xxx.com"
  # http_proxy: "proxy.com:8080"
  # https_proxy: "proxy.com:8080"
  # no_proxy: ""

scope:
  # If true, the controller will only watch custom resources in a single namespace
  singleNamespace: false
  # If `scope.singleNamespace=true`, the controller will only watch custom resources in this namespace
  # The default value is "", which means the namespace of the controller
  watchNamespace: ""

githubWebhookServer:
  enabled: false
  replicaCount: 1
  syncPeriod: 10m
  secret:
    create: true
    name: "github-webhook-server"
    ### GitHub Webhook Configuration
    #github_webhook_secret_token: ""
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  priorityClassName: ""
  service:
    type: ClusterIP
    ports:
      - port: 80
        targetPort: http
        protocol: TCP
        name: http
        #nodePort: someFixedPortForUseWithTerraformCdkCfnEtc
  ingress:
    enabled: false
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

```

**Comment by mumoshu** [comment]
@rxa313 I think that usually happens when you've shared the auth secret between two different releases.

In case `authSecret.create` being set to `true` as you've explained earlier in https://github.com/actions-runner-controller/actions-runner-controller/issues/782#issuecomment-914479143 resulted in that situation, I believe you need to give it unique name per release as suggested by @callum-tait-pbx at https://github.com/actions-runner-controller/actions-runner-controller/issues/782#issuecomment-914387258

Here's the relevant lines from the chart:

https://github.com/actions-runner-controller/actions-runner-controller/blob/a98729b08b86aac59613769a592cf71cf3523c90/charts/actions-runner-controller/templates/manager_secrets.yaml#L5

https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/templates/_helpers.tpl#L68

As you can see from above, setting `authSecret` `name` to anything non-empty results in the controller to use the secret of the exact name. If you specified the same name for the two releases, it shares the token, hence the manager logs you've seen.

**Comment by rxa313** [comment]
@mumoshu In my production rancher environment I have 3 unique namespaces and when I deployed each controller with unique releases I configured that `authSecret` `name` to be unique for each of the namespaces. In other words, in my rancher `secrets` I have three different `controller-manager-xxx` secret values (that hold `app_id`, `installation_id`, `app_private_key`  

<img width="492" alt="Screen Shot 2021-09-13 at 1 44 15 PM" src="https://user-images.githubusercontent.com/74605500/133132210-1502c558-268c-42e8-881b-d22574ab2b77.png">

Perhaps somewhere during a previous installation this is hanging somewhere in the backend that I don't see and it's being shared somewhere, but that would require me to wipe everything and start fresh.

**Comment by mumoshu** [comment]
@rxa313 I'd suggest you verify contents of all the auth secrets, verify deployment specs have references to correct auth secrets, and then `kubectl exec` into your actions-runner-controller containers and run e.g. `export` and verify envvars like `GITHUB_APP_ID` have correct values.

My theory is that you've upgraded authSecret values in-place and the actions-runner-controller's controller-manager pods aren't roll-updated yet. K8s secret change doesn't automagically restart consumer pods. Until restarting pods, K8s secret change doesn't propagate to envvars.

**Comment by rxa313** [comment]
@mumoshu 
I've checked all the auth secret contents and verified the deployment specifications. They are all pointing to the correct corresponding values. everything is matching as expected. I scaled down my pod replicas and rescaled to trigger a roll-update but I'm still seeing the same sharing between the controller managers.

I tried to `kubectl exec` into my controllers containers but receive error:
```
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```
Thanks for your patience.

**Comment by mumoshu** [comment]
@rxa313 Ah, so I missed the fact that we use distroless as the base image that makes it impossible to just `kubectl exec` into it. If you are on Kubernets 1.22 you could use `kubectl debug`.

Anyways, assuming secrets, deployments are correct and pods are up-to-date, the only situation I can imagine would be that the controller is somehow not respecting --watch-namespace.

Are you sure in your manager logs that each controller-manager is trying to reconcile RunnerDeployments and Runners that are expected to be managed by itself?

**Comment by rxa313** [comment]
@mumoshu 

In the manager logs it does successfully reconcile in the correct areas as expected, these logs just somehow aren't separate, if that makes sense. 

I'll show you a full log snippet here:

```
2021-09-13T20:02:48.325Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerreplicaset-controller", "request": "ghes-xxx-actions-runner-system/xx-xxx-it-rancher-runner-sj2vv"}
2021-09-13T20:02:48.325Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerreplicaset-controller", "request": "ghes-corp-actions-runner-system/xx-corp-it-rancher-runner-n75wp"}
2021-09-13T20:02:48.325Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerreplicaset-controller", "request": "ghec-actions-runner-system/xx-ghec-rancher-runner-2cs8n"}
2021-09-13T20:02:48.325Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerdeployment-controller", "request": "ghes-xxx-actions-runner-system/xx-xxx-it-rancher-runner"}
2021-09-13T20:02:48.325Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerdeployment-controller", "request": "ghes-corp-actions-runner-system/xx-corp-it-rancher-runner"}
2021-09-13T20:02:48.325Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerdeployment-controller", "request": "ghec-actions-runner-system/xx-ghec-rancher-runner"}
2021-09-13T20:02:53.586Z	DEBUG	actions-runner-controller.horizontalrunnerautoscaler	Calculated desired replicas of 1	{"horizontalrunnerautoscaler": "ghec-actions-runner-system/xx-ghec-runner-autoscaler", "suggested": 1, "reserved": 0, "min": 1, "cached": 1, "max": 6}
2021-09-13T20:02:53.587Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "horizontalrunnerautoscaler-controller", "request": "ghec-actions-runner-system/xx-ghec-runner-autoscaler"}
2021-09-13T20:03:05.133Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerdeployment-controller", "request": "ghec-actions-runner-system/xx-ghec-rancher-runner"}
2021-09-13T20:03:05.134Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerdeployment-controller", "request": "ghes-corp-actions-runner-system/xx-corp-it-rancher-runner"}
2021-09-13T20:03:05.134Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerdeployment-controller", "request": "ghes-xxx-actions-runner-system/xx-xxx-it-rancher-runner"}
2021-09-13T20:03:05.135Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerreplicaset-controller", "request": "ghes-xxx-actions-runner-system/xx-xxx-it-rancher-runner-sj2vv"}
2021-09-13T20:03:05.135Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerreplicaset-controller", "request": "ghes-xxx-actions-runner-system/xx-xxx-it-rancher-runner-sj2vv"}
2021-09-13T20:03:05.135Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerreplicaset-controller", "request": "ghes-corp-actions-runner-system/xx-corp-it-rancher-runner-n75wp"}
2021-09-13T20:03:05.135Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runnerreplicaset-controller", "request": "xxx-actions-runner-system/xx-ghec-rancher-runner-2cs8n"}
2021-09-13T20:03:05.178Z	ERROR	actions-runner-controller.horizontalrunnerautoscaler	Could not compute replicas	{"horizontalrunnerautoscaler": "xxx-xxx-actions-runner-system/xx-xxx-it-runner-autoscaler", "error": "failed to list runners: GET https://github.sherwin.com/api/v3/orgs/xxx-xxx-IT/actions/runners?per_page=100: 403 Resource not accessible by integration []"}
```
^ The very last line where the error is, the `/orgs/` value is not the correct org for the namespace I am looking at the `manager` logs for.

In regards to the `--watch-namespace` ... I have this set: 
```
scope:
  # If true, the controller will only watch custom resources in a single namespace
  singleNamespace: false
  # If `scope.singleNamespace=true`, the controller will only watch custom resources in this namespace
  # The default value is "", which means the namespace of the controller
  watchNamespace: ""
```
from what I understand, if `watchNamespace` is blank,  it will only watch runners in the same namespace as the controller... is my assumption wrong on this?

**Comment by toast-gear** [comment]
> ^ The very last line where the error is, the /orgs/ value is not the correct org for the namespace I am looking at the manager logs for.

This is a GitHub API error, it means your PAT / GitHub App permission configuration isn't correct

> from what I understand, if watchNamespace is blank, it will only watch runners in the same namespace as the controller... is my assumption wrong on this?

Correct, but it might be nice to explicitly set the namespace regardless as it's a bit more self-documenting for other people in your team this way

Additioanlly, I'm not sure if you've seen the latest readme but you also need to set the `leaderElectionId` if you are running controllers in the same namespace. The chart config is in HEAD only atm so you'd need to use an unreleased chart or make local changes until we do another chart release.

**Comment by rxa313** [comment]
@toast-gear , @mumoshu 

```
scope:
  # If true, the controller will only watch custom resources in a single namespace
  singleNamespace: true
  # If `scope.singleNamespace=true`, the controller will only watch custom resources in this namespace
  # The default value is "", which means the namespace of the controller
  watchNamespace: "ghec-actions-runner-system"
```

Setting `singleNamespace: true` and `watchNamespace` values fixed the issue where the controllers were watching the other namespaces in the cluster for controllers. I haven't had the time to check if this works with multiple controllers in the same namespace; for my work it's best we use different controllers in different namespaces.

Thanks for all your help and your work with this project! I'm good with closing the issue if you guys are.

**Comment by mumoshu** [comment]
> if watchNamespace is blank, it will only watch runners in the same namespace as the controller... is my assumption wrong on this?

I believe that's wrong. Have you read anything in our README that indicates that? Then we need to fix the doc.

**Comment by mumoshu** [comment]
@rxa313 I believe that's incorrect indeed. Could you try setting watchNamespace to whatever namespace you want the controller to watch?

**Comment by rxa313** [comment]
@mumoshu 

Oh yeah, I did that. I'm good now. Setting that `watchNamespace` to my namespace fixed the issue and now all of the controllers are only monitoring the runners in their namespace. This is what I did in my `values.yml`

If what it says in the `values.yml` regarding `watchNamespace` is incorrect, I think it should be fixed of course.

```
scope:
  # If true, the controller will only watch custom resources in a single namespace
  singleNamespace: true
  # If `scope.singleNamespace=true`, the controller will only watch custom resources in this namespace
  # The default value is "", which means the namespace of the controller
  watchNamespace: "ghec-actions-runner-system"
```
