### ISSUE TITLE
Workflows failing intermittently with "unable to resolve docker endpoint"

### ISSUE THREAD

**Issue by FalconerTC** [actions-runner-controller/actions-runner-controller#787]
**Describe the bug**
We often, but inconsistently, see certain workflows fail with the following error

```
Error: unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory
```

or occasionally
```
docker: Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?.
```

These workflows generally run correctly but will fail once or twice a day (perhaps 1 in 10 runs). The workflow that tends to be failing these begins with

```
name: Push

on:
  workflow_dispatch:
  push:

jobs:
  template-output:
    name: Run template-output
    runs-on: [self-hosted, default]
    strategy:
      matrix:
        environment: [ env1, env2 ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Artifactory Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASS }}
          registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
```

With the failure happening at the docker login step. 

I suspect that this is the same issue as this one reported for gitlab-runners (https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27306), being a timing problem between the `runner` container and `dind` container. I think the runner is coming up and reaching this docker step before `dind` is ready.

If it is a timing issue, do you have a recommendation on what to do for it?

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

Run with a workflow that performs docker commands almost immediately

**Environment (please complete the following information):**
 - Controller Version [0.19.0]
 - Deployment Method [Helm ]
 - Helm Chart Version [0.12.7]

**Additional context**
