### ISSUE TITLE
ERROR controller-runtime.controller - Privileged containers are not allowed spec.containers[1].securityContext.privileged

### ISSUE THREAD

**Issue by mssanjay** [actions-runner-controller/actions-runner-controller#792]
**Describe the bug**
Controller is unable to create runner pods. I see error as below

2021-09-06T22:15:37.929Z        ERROR   controller-runtime.controller   Reconciler error        {"controller": "runner-controller", "request": "gha-runner-controller/example-runner", "error": "pods \"example-runner\" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]"}

**Checks**
Manager logs shows below error

Privileged containers are not allowed spec.containers[1].securityContext.privileged

**To Reproduce**
Disable Previleged Pods in the cluster

**Expected behavior**
Runner Pod created

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version - 0.18.2
 - Deployment Method [e.g. Helm and Kustomize ] - Helm
 - Helm Chart Version [e.g. 0.11.0, if applicable] -

**Additional context**

**Comment by mumoshu** [comment]
@mssanjay Hey! Just curious but what do you want me to do? The information provided by you says that you got the error due to that you created some PSP to disallow privileged pods in your cluster. Then, there might be no way to make actions runners work.

Perhaps anyone could try to integrate rootless docker into actions-runner-controller, but I'm not going to do that myself anytime soon. If you could, I'll gladly review your work!

**Comment by mssanjay** [comment]
@mumoshu Our corporate policy does not allow Privileged pods in our cluster. Hence the policy is in place. Also, I am using the image "docker:dind-rootless" which I thought is a rootless docker. So I am not sure why this error. Thanks for the update!

**Comment by mumoshu** [comment]
@mssanjay Ah, good to know that there's now rootless version of the official dind image!

Well, actions-runner-controller mostly hardcodes `privileged: true`. But you can maybe try setting `securityContext.seLinuxOptions` to non-nil to make it `privileged: false`.

https://github.com/actions-runner-controller/actions-runner-controller/blob/14564c7b8e0ad7adadcb18a41a15f831b580f931/controllers/runner_controller.go#L805-L812

If it doesn't work, I'd suggest trying the `canary` image of actions-runner-controller that has a brand new feature called [Runner Sets](https://github.com/actions-runner-controller/actions-runner-controller#stateful-runners). Perhaps you can overwrite `privileged` setting for `docker` container with it. Something like:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: example
spec:
  ephemeral: false
  replicas: 2
  repository: mumoshu/actions-runner-controller-ci
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: example
  serviceName: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: docker
        privileged: false
```

**Comment by rajbos** [comment]
I had the same thing (preparing to add PSP that will disallow privileged containers). I suspect it will work for the dind container, but the deployment will always need a privileged container since it spins up new pods? 

Anyway, I've tried using a mimimal seLinuxOptions since that should set the `privileged` to false. Unfortunately applying this setup still runs the dind containers as privileged: 

``` yaml
# runner-deployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: xxx-gh-runner-deployment
spec:
  template:
    spec:
      organization: xxx-gh
      labels:
        - xxx-gh-org
        - k8s

      securityContext:
        seLinuxOptions:
          # level: "s0"
          # role: "system_r"
          # type: "super_t"
          # user: "system_u"
          privileged: false
``` 

I've no clue what proper values could be for the level / role / type / user, so I haven't tried that out.

Note: I'm checking the privileged status with this command, which returns **true**:
``` shell
kubectl get pod xxx-gh-runner-deployment-mzfx9-rj9rs -o json | jq -r '.spec.containers[].securityContext'
```

Note: I had to modify the official `dind:rootless` images by adding an extra folder. The image can be found [here](https://github.com/rajbos/dind-rootless-runner/pkgs/container/dind-rootless-runner) in my public package feed.
