### ISSUE TITLE
sidecarContainers is invalid

### ISSUE THREAD

**Issue by radu-stefanache** [actions-runner-controller/actions-runner-controller#795]
**Describe the bug**
I am trying to add a SidecarContainer to my RunnerDeployment according to the documentation but I am getting an error that the spec is invalid.

**To Reproduce**
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: myrunner
spec:
  template:
    spec:
      repository: myrepo
      dockerEnabled: true
      dockerdWithinRunnerContainer: false
      sidecarContainers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
      serviceAccountName: mysa
      securityContext:
        fsGroup: 1000
      labels:
        - myrepo
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: myrunner
spec:
  scaleTargetRef:
    name: myrunner
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - myrepo
  ```

**Expected behavior**
A mysql sidecar container would become available.

**Screenshots**
```
2021-09-07T15:21:39.822Z        ERROR   actions-runner-controller.runner        Failed to update runner status for Registration                             {"runner": "myrunner-fm4fk-j9ql2", "error": "Runner.actions.summerwind.dev \"myrunner-fm4fk-j9ql2\" is invalid: spec.sidecarContainers.name: Required value"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/summerwind/actions-runner-controller/controllers.(*RunnerReconciler).updateRegistrationToken
        /workspace/controllers/runner_controller.go:555
github.com/summerwind/actions-runner-controller/controllers.(*RunnerReconciler).Reconcile
        /workspace/controllers/runner_controller.go:185
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
```

**Environment (please complete the following information):**
 - Controller Version [0.19.0]
 - Deployment Method [Helm ]
 - Helm Chart Version [0.12.8]

**Additional context**
When I check the Runner CRs, I get an empty object:

```
sidecarContainers:
- {}
```
