### ISSUE TITLE
`containers` key on RunnerDeployment causes error

### ISSUE THREAD

**Issue by tyrken** [actions-runner-controller/actions-runner-controller#801]
**Describe the bug**
I was trying to use the quasi-documented `containers` key on the RunnerDeployment's template-spec to add a lifecycle postStart script, but kept getting an error about the name missing show up, when it was set in my definition (see below in **To Reproduce**):

```
... ERROR	controller-runtime.manager.controller.runner-controller	Reconciler error	{"reconciler group": "actions.summerwind.dev", "reconciler kind": "Runner", "name": "test-runners-zltbw-cmx8d", "namespace": "gha", "error": "Runner.actions.summerwind.dev \"test-runners-zltbw-cmx8d\" is invalid: spec.containers.name: Required value"}```
```

**Checks**
- [x] My actions-runner-controller version (v0.x.y) does support the feature - Tested v0.19.0 originally via helm chart
- [x] I'm using an unreleased version of the controller I built from HEAD of the default branch - Also present in canary DockerHub image & self-built master image

**To Reproduce**
1. Install v0.19.0 or master build of action-runner-controller
2. Install resource below

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-runners
  namespace: gha
spec:
  replicas: 2
  template:
    spec:
      organization: my-org
      labels:
        - test
      # Use Containers block for full control
      containers:
        - name: runner
          # Example customisation
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 50
```

**Expected behavior**
The customisations inside the `containers` key apply to the final created pods.

**Screenshots**
After a little exploration, I noticed the YAML output from the K8s masters was actually saying the same thing, note the array of a single empty object in the containers field below:

```
$ kubectl get runnerdeployment -o yaml
apiVersion: v1
items:
- apiVersion: actions.summerwind.dev/v1alpha1
  kind: RunnerDeployment
  metadata:
   # snipped
  spec:
    replicas: 2
    selector: null
    template:
      metadata: {}
      spec:
        #### NOTE EMPTY OBJECT BELOW
        containers:
        - {}
        dockerdContainerResources: {}
        image: ""
        labels:
        - test
        organization: my-org
        resources: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Environment (please complete the following information):**
 - Controller Version: 0.19.0 and master
 - Deployment Method: Helm
 - Helm Chart Version: 0.12.8
 - Kubernetes: 1.20 on EKS/AWS

**Additional context**

After some experimentation, I got this to work by manually editing the CRD definitions, copying the "containers.items.properties" field from the RunnerSet CRD to the RunnerDeployment, RunnerReplicaSet and Runner CRDs.

... but now I see that field was actually dropped on purpose by #123 due to a bug in the underlying generator.  That bug is over a year old now, and I didn't have any problems installing the doctored CRDs or the non-"fixed" RunnerReplicaSet CRD in 1.20, so can we stop deleting those (to me) vital properties?

BTW, when it was working I also noticed any image in the `containers` override was being clobbered by the default image if I didn't also/instead use the top-level image key in the main template spec.  This looks due to a minor weakness in the golang if-logic around https://github.com/actions-runner-controller/actions-runner-controller/blob/a98729b08b86aac59613769a592cf71cf3523c90/controllers/runner_controller.go#L743 which I'll look to fix in a PR later...

**Comment by mumoshu** [comment]
@tyrken Thanks for the detailed report! Ah, that makes sense. We've recently migrated to K8s CRD API v1 from v1beta1. In that process, I might have unintendedly changed details and it might have started NOT storing fields undefined in the CRD, that results in a validation error in actions-runner-controller code.

Would you mind removing that `fix118` make target and submit a pull request to regenerate the CRDs?

**Comment by yuri-1987** [comment]
@mumoshu any release date for this fix? i see this with v0.20 as well.
i just wanted to add a `label` and the controller complained about `spec.container.image` and once that was added, i had the same error as the OP
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-org-runner
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      organization: my-org
      dockerEnabled: false
      labels:
      - myorg-ubuntu20.04
```
