### ISSUE TITLE
Runner pod maybe being reused between self-hosted jobs

### ISSUE THREAD

**Issue by raids** [actions-runner-controller/actions-runner-controller#811]
**Describe the bug**
I think pods are being reused between different jobs without restarting and clearing in-memory data, such as directories and files created during the job in `/home/runner`, or a job is being scheduled to a runner which is already running another job.

We have a self-hosted job which includes a step to set up some credentials for downstream steps in the same job. These credentials are created in `/home/runner/.creds`.

Intermittently, we are seeing errors during instances of this job where the setup credentials step complains that this directory already exists:
```
Run org/configure-credentials@v0.0.5
internal/fs/utils.js:220
    throw err;
    ^

Error: EEXIST: file already exists, mkdir '/home/runner/.creds'
    at Object.mkdirSync (fs.js:823:3)
    at setCredentials (/runner/_work/_actions/org/configure-credentials/v0.0.5/build/index.js:31:8)
    at main (/runner/_work/_actions/org/configure-credentials/v0.0.5/build/index.js:83:5)
    at Object.<anonymous> (/runner/_work/_actions/org/configure-credentials/v0.0.5/build/index.js:90:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -17,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: '/home/runner/.creds'
}
```

I'm using `dockerVolumeMounts` to mount a `hostPath` as `/var/lib/docker` in the pod. These runners are responsible for building docker images. (Full RunnerDeployment yaml below under **Additional context**).

```yaml
volumes:
      - name: var-lib-docker
        hostPath:
          path: /mnt/var-lib-docker
          type: DirectoryOrCreate
      dockerVolumeMounts:
        - mountPath: /var/lib/docker
          name: var-lib-docker
```

Please let me know if I can provide any more info or if you can point me in the right direction of where I can debug this.

**Checks**

- [x ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**Expected behavior**
The directory `/home/runner/.creds` to not already exist on the runner.

**Environment (please complete the following information):**
 - Controller Version: 0.19.0
 - Deployment Method: Kustomize 

**Additional context**

RunnerDeployment template:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: REDACTED
  namespace: REDACTED
spec:
  template:
    metadata:
      labels:
        name: REDACTED
    spec:
      image: REDACTED.dkr.ecr.eu-west-1.amazonaws.com/REDACTED:latest
      imagePullPolicy: Always
      nodeSelector:
        REDACTED: "REDACTED"
      repository: REDACTED/REDACTED
      labels:
        - docker-build
      env: []
      resources:
        limits:
          cpu: "2.0"
          memory: "4Gi"
        requests:
          cpu: "1.0"
          memory: "2Gi"
      dockerdContainerResources:
        limits:
          cpu: "4.0"
          memory: "8Gi"
        requests:
          cpu: "2.0"
          memory: "4Gi"
      volumes:
      - name: var-lib-docker
        hostPath:
          path: /mnt/var-lib-docker
          type: DirectoryOrCreate
      dockerVolumeMounts:
        - mountPath: /var/lib/docker
          name: var-lib-docker
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - REDACTED
            topologyKey: "kubernetes.io/hostname"
```
