### ISSUE TITLE
v0.20 Problem with authentication on controller-manager

### ISSUE THREAD

**Issue by grzegorzkawkaosik** [actions-runner-controller/actions-runner-controller#829]
**Describe the bug**
It seems that controller-manager deployment from yaml is not using environment variables correctly.

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. deploy actions-runner-controller v0.20.0 from [release page](https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.20.0/actions-runner-controller.yaml)
1. deploy secret with github app key and ids
1. Try deploying any runner
1. Get error in controller-manager saying that key file has length 0

**Expected behavior**
Github runner should be registered

**Environment (please complete the following information):**
 - Controller Version: 0.20.0
 - Deployment Method: `kubectl apply`

**Additional context**
I have created a workaround by manually providing required arguments to /manager binary, see below:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager
  namespace: actions-runner-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        command:
        - "/manager" 
        args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --sync-period=10m
        - "-github-app-private-key" 
        - $(GITHUB_APP_PRIVATE_KEY)
        - "-github-app-id"
        - $(GITHUB_APP_ID)
        - "-github-app-installation-id"
        - $(GITHUB_APP_INSTALLATION_ID)
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: github_token
              name: controller-manager
              optional: true
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              key: github_app_id
              name: controller-manager
              optional: true
        - name: GITHUB_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              key: github_app_installation_id
              name: controller-manager
              optional: true
        - name: GITHUB_APP_PRIVATE_KEY
          value: /etc/actions-runner-controller/github_app_private_key
        image: summerwind/actions-runner-controller:v0.20.0
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /etc/actions-runner-controller
          name: controller-manager
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: quay.io/brancz/kube-rbac-proxy:v0.10.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      - name: controller-manager
        secret:
          secretName: controller-manager
---
```

**Comment by mumoshu** [comment]
> Get error in controller-manager saying that certificate file has length 0

Which certificate are you referring? I thought the GitHub App authentication only requires key, app id, and installation id, but cert.

**Comment by grzegorzkawkaosik** [comment]
Yes, sorry, I meant key.

**Comment by mumoshu** [comment]
Thanks! Then it should just work.

How does the content of your secret look like?

**Comment by grzegorzkawkaosik** [comment]
`kubectl describe secret controller-manager`

```
Name:         controller-manager
Namespace:    actions-runner-system
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
github_app_id:               6 bytes
github_app_installation_id:  8 bytes
github_app_private_key:      1679 bytes
```

**Comment by toast-gear** [comment]
I've been trying to replicate this and have been unable to do so. We haven't touch anything in the area of this code in the latest release so I think this issue must be environmental. Are you able to provide any more details? I've tried replicating with both Helm and kubectl deployment methods as well as PAT and GitHub Auth

**Comment by sykora** [comment]
1. I confirmed that the file uses LF line endings (not CRLF) by running `dos2unix key | cmp - key`.
2. There are no events on the controller pod; its logs only contain the message that was implied in the original post: `Error: Client creation failed. authentication failed: using private key of size 0 (...): could not parse private key: Invalid Key: Key must be PEM encoded PKCS1 or PKCS8 private key`

**Comment by mumoshu** [comment]
@manpreet-agoro Thanks. Would you mind trying another setup (helm, k8s manifests, etc without terraform) too so that you can isolate the cause?

**Comment by mad01** [comment]
I have the same issue in v1.20.10-gke.1600. Not sure if this helps. I rebuilt my cluster to v1.20.10-gke.1600 it was running a version of 1.18 before the rebuild. I have not tried to downgrade yet to 1.18 to see if this works. But i have not been able to get this to work since the trying in v1.20.10-gke.1600

**Comment by mad01** [comment]
I tested with the log message fix @mumoshu i could now understand that i missunderstood what the error actually was. I took the client ID from here as the installation ID
<img width="626" alt="Screenshot 2021-11-03 at 09 56 49" src="https://user-images.githubusercontent.com/8710472/140032540-51e3253d-9342-4b4c-8de3-a1959f5ef7ea.png">
e 

The fix was to take the actual installation ID from the app settings here `https://github.com/organizations/<org>/settings/installations` when selecting the app i was working on the installation ID can be found in the url here 
`https://github.com/organizations/<org>/settings/installations/<installation id>`

**Comment by mumoshu** [comment]
@mad01 Thanks. That helps a lot!

Perhaps we'd better add a validation for installation id so that the controller fails to start with a more helpful message like `installation id must be an integer value, but was *provided installed id here*`?

**Comment by mad01** [comment]
I think that might have helped even more. since the install ID is a int64 and the client ID is a string, that would quickly hint that it might be wrong

**Comment by BeyondEvil** [comment]
For some poor soul finding this issue and none of the previous solutions help, here's what happened to me (I'm using External Secrets Operator):

This did not work:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-github-token
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        github_app_id: "12345678"
        github_app_installation_id: "87654321"
        github_app_private_key: |
             "{{ .privateKey }}"

  data:
  - secretKey: privateKey
    remoteRef:
      key: "arc/arc/github-key"
```

But this did (notice `github_app_private_key`):

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-github-token
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        github_app_id: "12345678"
        github_app_installation_id: "87654321"
        github_app_private_key: "{{ .privateKey }}"

  data:
  - secretKey: privateKey
    remoteRef:
      key: "arc/arc/github-key"
```
