### ISSUE TITLE
Upgrade v0.20.0 and dockerenable = false

### ISSUE THREAD

**Issue by vinvli** [actions-runner-controller/actions-runner-controller#835]
Deployed the new v0.20.0 version but if I add the flag dockerEnabled: false it fails with the error in the controller log:

`Reconciler error	{"reconciler group": "actions.summerwind.dev", "reconciler kind": "Runner", "name": "github-runner-bn4xw-55gx9", "namespace": "github-runner", "error": "Pod \"github-runner-bn4xw-55gx9\" is invalid: spec.containers[1].image: Required value"}`

We use the following example deployment:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner
  namespace: github-runner
spec:
  replicas: 1
  template:
    spec:
      organization: org-IT
      ephemeral: true
      dockerEnabled: false
      resources:
        limits:
          memory: "2Gi"
        requests:
          memory: "1Gi"
      image: privateacr.azurecr.io/github/actions-runner:v2.283.1-ubuntu-20.04
      env:
      - name: NODE_EXTRA_CA_CERTS
        value: /usr/local/share/ca-certificates/rootca.pem
```

If I revert back to 0.19.0 it works as expected (no dind is injected)
