### ISSUE TITLE
`runnerset`:mountPath must be unique

### ISSUE THREAD

**Issue by pratikbalar** [actions-runner-controller/actions-runner-controller#840]
**Describe the bug**
cannot mount volume in runnerset at `workDir`

**To Reproduce**
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: improwised-runner
spec:
  replicas: 1
  organization: improwised
  selector:
    matchLabels:
      app: improwised-runner
  serviceName: improwised-runner
  workDir: /home/runner/repo
  ephemeral: true
  template:
    metadata:
      labels:
        app: improwised-runner
    spec:
      containers:
      - name: runner
        imagePullPolicy: IfNotPresent
        env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
        volumeMounts:
          - name: repo
            mountPath: /home/runner/repo
      - name: docker
        resources:
          limits:
            cpu: "3.5"
            memory: "15.5Gi"
          requests:
            cpu: "2"
            memory: "5Gi"
      volumes:
        - name: repo
          persistentVolumeClaim:
            claimName: repo
  volumeClaimTemplates:
  - metadata:
      name: repo
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
```

logs in k3s
```logs
Sep 23 08:57:56 node-1 k3s[2606]: I0923 08:57:56.651040    2606 event.go:291] "Event occurred" object="actions-runner-system/my-runner" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulCreate" message="create Claim repo-imp`rowised-runner-0 Pod my-runner-0 in StatefulSet my-runner success"
Sep 23 08:57:56 node-1 k3s[2606]: I0923 08:57:56.651050    2606 event.go:291] "Event occurred" object="actions-runner-system/repo-my-runner-0" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="WaitForFirstConsumer" message="waiting for first consumer to be created before binding"
Sep 23 08:57:56 node-1 k3s[2606]: E0923 08:57:56.653231    2606 fieldmanager.go:191] "[SHOULD NOT HAPPEN] failed to update managedFields" err="failed to convert new object (/v1, Kind=Pod) to smd typed: .spec.containers[name=\"runner\"].volumeMounts: duplicate entries for key [mountPath=\"/home/runner/repo\"]" VersionKind="/, Kind="
Sep 23 08:57:56 node-1 k3s[2606]: E0923 08:57:56.660120    2606 stateful_set.go:392] error syncing StatefulSet actions-runner-system/my-runner, requeuing: Pod "my-runner-0" is invalid: spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/home/runner/repo": must be unique
Sep 23 08:57:56 node-1 k3s[2606]: I0923 08:57:56.660226    2606 event.go:291] "Event occurred" object="actions-runner-system/my-runner" kind="StatefulSet" apiVersion="apps/v1" type="Warning" reason="FailedCreate" message="create Pod my-runner-0 in StatefulSet my-runner failed error: Pod \"my-runner-0\" is invalid: spec.containers[0].volumeMounts[2].mountPath: Invalid value: \"/home/runner/repo\": must be unique"
```

controller logs
```logs
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:57:36.141Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-runner-set-pod", "UID": "efe24bdc-d673-42d8-bdfe-7eee9137e033", "kind": "/v1, Kind=Pod", "resource": {"group":"","version":"v1","resource":"pods"}}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:57:36.142Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-runner-set-pod", "code": 200, "reason": "", "UID": "efe24bdc-d673-42d8-bdfe-7eee9137e033", "allowed": true}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:57:43.820Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-runner-set-pod", "UID": "f0c7592a-17fe-4850-b7e6-c5082a02798b", "kind": "/v1, Kind=Pod", "resource": {"group":"","version":"v1","resource":"pods"}}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:57:43.820Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-runner-set-pod", "code": 200, "reason": "", "UID": "f0c7592a-17fe-4850-b7e6-c5082a02798b", "allowed": true}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:57:46.838Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-runner-set-pod", "UID": "493ee61b-ebed-4485-abce-c2a9e207005a", "kind": "/v1, Kind=Pod", "resource": {"group":"","version":"v1","resource":"pods"}}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:57:46.838Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-runner-set-pod", "code": 200, "reason": "", "UID": "493ee61b-ebed-4485-abce-c2a9e207005a", "allowed": true}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:57:49.699Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-runner-set-pod", "UID": "41fc0eba-cc79-4da7-a169-5dab6665a9c6", "kind": "/v1, Kind=Pod", "resource": {"group":"","version":"v1","resource":"pods"}}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:57:49.699Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-runner-set-pod", "code": 200, "reason": "", "UID": "41fc0eba-cc79-4da7-a169-5dab6665a9c6", "allowed": true}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:57:56.654Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-runner-set-pod", "UID": "0d56b7e5-a16a-4a97-a431-9b998eb1b918", "kind": "/v1, Kind=Pod", "resource": {"group":"","version":"v1","resource":"pods"}}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:57:56.656Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-runner-set-pod", "code": 200, "reason": "", "UID": "0d56b7e5-a16a-4a97-a431-9b998eb1b918", "allowed": true}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:58:37.635Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-runner-set-pod", "UID": "25acdb8d-bd5a-40e2-a4ad-275bb6a4e33d", "kind": "/v1, Kind=Pod", "resource": {"group":"","version":"v1","resource":"pods"}}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:58:37.637Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-runner-set-pod", "code": 200, "reason": "", "UID": "25acdb8d-bd5a-40e2-a4ad-275bb6a4e33d", "allowed": true}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:59:59.579Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-runner-set-pod", "UID": "874233c9-bbda-4249-8187-c1ece71fcd31", "kind": "/v1, Kind=Pod", "resource": {"group":"","version":"v1","resource":"pods"}}
controller-manager-5cd5469769-mczsw manager 2021-09-23T08:59:59.579Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-runner-set-pod", "code": 200, "reason": "", "UID": "874233c9-bbda-4249-8187-c1ece71fcd31", "allowed": true}
```

**Environment (please complete the following information):**
 - Controller Version : 0.20.0
 - Deployment Method: `kc apply -f action-runner.yaml`
 - K3s version `k3s version v1.21.4+k3s1 (3e250fdb) go version go1.16.6`

**Comment by alex-mozejko** [comment]
hello, 

i think i saw a similar thing, unfortunately i didn't keep any logs. 

the result of this error though was that the controller seemed to spam my api server by creating a whole bunch of `runner` CRs and bring my cluster to a chugging standstill :( 

the runner deployment i was using was: 

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-myorg-medium
spec:
  replicas: 1
  template:
    spec:
      labels:
        - myorg-medium
      organization: myorg
      image: myorg.azurecr.io/my-custom-dind:latest
      volumeMounts:
        - name: runner
          mountPath: /runner
      volumes:
        - name: runner
          emptyDir: {}
      dockerdWithinRunnerContainer: true
```

but i fixed by removing the emptyDir mounted at `/runner`. 

the emptyDir was needed for a previous release and this issue only arose after updating to the latest version.
