### ISSUE TITLE
runner not able to connect to docker

### ISSUE THREAD

**Issue by xabi93** [actions-runner-controller/actions-runner-controller#847]
**Describe the bug**
Time to time docker:dind container throws the following error:
`evel=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc`

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
- Deploy the github-runner-controller with helm chart
- Apply the following configuration:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner-deploy
  namespace: actions-runner-system
spec:
  template:
    spec:
      organization: org-name
      volumes:
      - name: docker-data-ci
        persistentVolumeClaim:
          claimName: docker-data-ci
      dockerVolumeMounts:
      - mountPath: /var/lib/docker
        name: docker-data-ci
      

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "docker-data-ci"
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: github-runner-deploy
  minReplicas: 0
  maxReplicas: 5
  scaleUpTriggers:
  - githubEvent: {}
    duration: "5m"

```

**Expected behavior**
Docker:dind container connects sucessfully

**Screenshots**
<img width="1886" alt="Screenshot 2021-09-27 at 17 40 05" src="https://user-images.githubusercontent.com/6052966/134940634-4e6d4c9a-658e-46ea-9499-b878c3958ea6.png">

**Environment (please complete the following information):**
 - Controller Version 0.20.0
 - Deployment Method: Helm
 - Helm Chart Version: 0.13.0

**Additional context**
Maybe I have the issue on my side and I have something incorrectly setup

**Comment by mumoshu** [comment]
@xabi93 Thanks for reporting! I have no idea how we could make it occur. Perhaps too low memory available to your dind container that is preventing it from launching containerd? What if you set resource request/limit for memory?

**Comment by xabi93** [comment]
@mumoshu thanks for the response, the issue was on my end, I was trying to share the /var/lib/docker in multiple docker containers

**Comment by rxa313** [comment]
@mumoshu  sorry to hijack this.. it's the most recent issue regarding docker.

Is there any documentation/support for `RunnerSet` to support `dockerVolumeMounts:`?  I checked the CRDS and notice it's only available for `RunnerDeployments`

There's not too much that I've seen around docker layer cache/docker image caching and it would be useful to speed up larger docker builds.

We've sped up our maven/gradle builds by adding a PVC to `runner` containers path: `/home/runner/` and the `.m2`, `.gradle` etc.. are being stored there.

For docker images, can we similarly mount a PVC to the `docker` container and path: `/var/lib/docker` to speed up docker builds? Then maybe support for `dockerVolumeMounts` is not required for `RunnerSet`

**Comment by mumoshu** [comment]
@rxa313 I thought you could add a container named `docker` under `spec.template.containers` and configure volume mouts there. Would you mind trying that?

**Comment by rxa313** [comment]
@mumoshu  I added this: 

```yaml
   - name: docker
        imagePullPolicy: Always
        image: docker.cpartdc01.xxx.com/xx_docker:dind
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /usr/local/share/ca-certificates/root.crt
        volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-volume
```
And in Rancher on the `docker` container it shows this:

<img width="923" alt="Screen Shot 2021-11-12 at 7 35 49 AM" src="https://user-images.githubusercontent.com/74605500/141468187-073c78d7-59b8-467b-bac7-416d5333aa18.png">

I know there are some limitations to caching/sharing between runners from #944 - but I was hoping mounting a PVC to the path would work a similar way as mounting `/home/runner` did for our maven and gradle builds.

At the end of the day we would just run a `docker prune` to clear the stored images in `/var/lib/docker` so it's fresh for the next day, while allowing us to speed up builds during working hours.
