### ISSUE TITLE
`Annotations` don't work on `runners` 

### ISSUE THREAD

**Issue by ozlotusflare** [actions-runner-controller/actions-runner-controller#855]
**Describe the bug**

Hey everyone !
I added `annotations` spec to my `RunnerDeployment` as described [here](https://github.com/actions-runner-controller/actions-runner-controller#additional-tweaks)
Here is my example
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-self-hosted-runner
spec:
  template:
    metadata:
      annotations:
        ecr-enable: true # custom annotation
...
```
and deployed changes.
Here is my `kubectl describe runnerdeployments.actions.summerwind.dev gha-self-hosted-runner` output:
```bash
Name:         gha-self-hosted-runner
Namespace:    ci
Labels:       kustomize.toolkit.fluxcd.io/name=application-app-of-apps
              kustomize.toolkit.fluxcd.io/namespace=gotk-system
Annotations:  ecr-enable: true # custom annotation
              kustomize.toolkit.fluxcd.io/checksum: b744b9bdb7f7fe35d74daa73ab42749bd5f604c8
API Version:  actions.summerwind.dev/v1alpha1
Kind:         RunnerDeployment
...
```
But, when I ran describe for running pod I saw next output:
```bash
Name:         gha-self-hosted-runner-jmg8l-4tfp4
Namespace:    ci
Priority:     0
Node:         ip-192-168-20-210.ec2.internal/192.168.20.210
Start Time:   Wed, 29 Sep 2021 20:22:38 +0300
Labels:       pod-template-hash=749fd4569f
              runner-deployment-name=gha-self-hosted-runner
              runner-template-hash=67cf64b6d7
Annotations:  <none> # No custom annotation
Status:       Running
...
```
For some reason this annotations didn’t apply for `Runners`.
 
**Checks**

- [ ] My actions-runner-controller version  does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Create `RunnerDeployment` with annotations.
2. Run `kubectl desribe pod`
3. See empty Annotation field 

**Expected behavior**
See Annotation in Pod Description as well as in `RunnerDeployment`

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [0.19.0]
 - Deployment Method [Helm]
 - Helm Chart Version [0.12.2]

**Comment by mumoshu** [comment]
@ozlotusflare Hey! Would you mind checking your configuration once again?

This:

```
Name:         gha-self-hosted-runner
Namespace:    ci
Labels:       kustomize.toolkit.fluxcd.io/name=application-app-of-apps
              kustomize.toolkit.fluxcd.io/namespace=gotk-system
Annotations:  ecr-enable: true # custom annotation
              kustomize.toolkit.fluxcd.io/checksum: b744b9bdb7f7fe35d74daa73ab42749bd5f604c8
API Version:  actions.summerwind.dev/v1alpha1
Kind:         RunnerDeployment
...
```

says that you had this manifest, where `annotations` are under runnerdeployment.metadata rather than under the template. So your manifest should look like the below:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-self-hosted-runner
  annotations:
    ecr-enable: true # custom annotation
spec:
  template:
    metadata:
...
```

But you said your manifest is like:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-self-hosted-runner
spec:
  template:
    metadata:
      annotations:
        ecr-enable: true # custom annotation
...
```

I'm pretty confused. What's your actual manifest?

To be clear, you need to set `runnerdeployment.spec.template.metadata.annotations` rather than `runnerdeployment.metadata.annotations` to make it propagated down to runners and runner pods.
