### ISSUE TITLE
enterprise runner horizontal scale error with webhook 

### ISSUE THREAD

**Issue by roshvin** [actions-runner-controller/actions-runner-controller#892]
**Describe the bug**
enterprise runner Horizontal auto scale error . and its not scaling 
but repo and org level horizontal scaling is working 

controller log 

2021-10-14T12:20:09.659Z        INFO    controllers.Runner      Scale target not found. If this is unexpected, ensure that there is exactly one repository-wide or organizational runner deployment that matches this webhook event  {"event": "workflow_job", "hookID": "45", "delivery": "12c4eb20-2ce9-11ec-9840-f5605bef85ef", "workflowJob.status": "in_progress", "workflowJob.labels": [], "repository.name": "repo", "repository.owner.login": "ROK-ACTION-TEST", "repository.owner.type": "Organization", "action": "started"}
2021-10-14T12:20:36.734Z        INFO    controllers.Runner      finding repository-wide runner  {"event": "workflow_job", "hookID": "45", "delivery": "22e8b180-2ce9-11ec-8058-205f3fdaa6e0", "workflowJob.status": "completed", "workflowJob.labels": [], "repository.name": "repo", "repository.owner.login": "ROK-ACTION-TEST", "repository.owner.type": "Organization", "action": "completed", "repository": "ROK-ACTION-TEST/repo"}
2021-10-14T12:20:36.734Z        ERROR   controllers.Runner      handling check_run event        {"event": "workflow_job", "hookID": "45", "delivery": "22e8b180-2ce9-11ec-8058-205f3fdaa6e0", "workflowJob.status": "completed", "workflowJob.labels": [], "repository.name": "repo", "repository.owner.login": "ROK-ACTION-TEST", "repository.owner.type": "Organization", "action": "completed", "error": "cache contained <nil>, which is not an Object"}
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2046
net/http.(*ServeMux).ServeHTTP
        /usr/local/go/src/net/http/server.go:2424
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2878
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1929

deployment yaml 
```

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dot-runner
spec:
  replicas: 1
  template:
    spec:
      enterprise: test
      labels:
      - dot-enterprise-runner
      env: []
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      image: gha-caas-runner-generic
      dockerEnabled: false
      securityContext:
        runAsUser: 1000
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
   name: ent-runner-auto-scaller
spec:
  scaleTargetRef:
    name: myrunners
  scaleUpTriggers:
  - githubEvent: {}
    duration: "3m"
```

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**Expected behavior**
enterprise runner should scan based on workflow run 

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.20.2]
 - Deployment Method [e.g. Helm and Kustomize ]
 - Helm Chart Version [e.g. 0.13.2, if applicable]

**Additional context**

autoscalling of runner is working at repo level and Org level with webhook
