### ISSUE TITLE
Docker daemon is not running in "actions-runner-dind" image again

### ISSUE THREAD

**Issue by andridzi** [actions-runner-controller/actions-runner-controller#924]
I'm getting next error when trying to run `docker ps` from workflow or directly in POD
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
Docker image:  `summerwind/actions-runner-dind:v2.283.3-ubuntu-20.04`

There were similar issue in https://github.com/actions-runner-controller/actions-runner-controller/issues/461

After mounting docker.sock from the host machine it's working, but it is not an expected behavior I guess.

**Comment by andridzi** [comment]
sorry for the delay with answer
```
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: shared-runner
  namespace: actions-runner
spec:
  replicas: 1
  template:
    spec:
      organization: XXXXXXXXX
      labels:
        - shared-runner
      image: summerwind/actions-runner-dind:v2.283.3-ubuntu-20.04
      dockerdWithinRunnerContainer: true
      imagePullPolicy: IfNotPresent
```

and during the workflow run or directly from inside the POD I'm getting 

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

environment: GKE cluster `1.21.4-gke.2300`
