### ISSUE TITLE
Using Helm installation, the `webhook-service` contains prefix

### ISSUE THREAD

**Issue by sbrinkerhoff** [actions-runner-controller/actions-runner-controller#933]
**Describe the bug**
When attempting to deploy with the Helm chart, a `webhook-service` service exists, however it is prefixed and a runner yaml cannot be applied.

**Checks**

**To Reproduce**

# Runner.yaml
```
# runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: kubernetes-hosted-runners
spec:
  replicas: 2
  template:
    spec:
      enterprise: where-i-work
      group: "Enterprise Runners"
      labels:
        - RunnerLabel

```

# Manifest Deployment

This appears to work fine...

```
❯ kubectl delete namespace actions-runner-system
namespace "actions-runner-system" deleted

❯ kubectl apply -f https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.20.2/actions-runner-controller.yaml

❯ kubectl create secret generic controller-manager \
    -n actions-runner-system \
    --from-literal=github_token=xxxxxxxx
    
 ❯ kubectl -n actions-runner-system get endpoints
NAME                                 ENDPOINTS            AGE
controller-manager-metrics-service   100.77.171.54:8443   3m21s
webhook-service                      100.77.171.54:9443   3m21s
```

# Helm Deployment

```
❯ kubectl delete namespace actions-runner-system
namespace "actions-runner-system" deleted

❯ helm upgrade --install --namespace actions-runner-system --create-namespace \
             --wait actions-runner-controller actions-runner-controller/actions-runner-controller
Release "actions-runner-controller" does not exist. Installing it now.

❯ kubectl create secret generic controller-manager \
    -n actions-runner-system \
    --from-literal=github_token=xxxxxxxx
    
❯ kubectl -n actions-runner-system get endpoints
NAME                                        ENDPOINTS             AGE
actions-runner-controller-metrics-service   100.77.170.236:8443   101s
actions-runner-controller-webhook           100.77.170.236:9443   101s

❯ kubectl apply -f github-actions-controller/runner.yaml
Error from server (InternalError): error when creating "github-actions-controller/runner.yaml": Internal error occurred: failed calling webhook "mutate.runnerdeployment.actions.summerwind.dev": Post "https://webhook-service.actions-runner-system.svc:443/mutate-actions-summerwind-dev-v1alpha1-runnerdeployment?timeout=10s": service "webhook-service" not found
```

**Expected behavior**
The helm and manifest deployments should be nearly identical.
