### ISSUE TITLE
Controller setup for multiple organizations

### ISSUE THREAD

**Issue by FearlessHyena** [actions-runner-controller/actions-runner-controller#939]
Hi I'm currently setting this up on GHES after going through the docs and it works fine for a RunnerDeployment/HRA setup

I'm using Webhooks for the autoscaling and an Nginx Ingress Controller in front of the webhook server 

```yaml
githubWebhookServer:
  enabled: true
  imagePullSecrets: []
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/acme-challenge-type = "http01"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: mydomain.com
          paths:
          - path: /
```

I'm struggling to get this working for multiple Orgs however. 

I tried installing the RunnerDeployment and HRA and a runner controller in separate namespaces and then setting the  `singleNamespace` to `true` and setting the `watchNamespace` to the corresponding namespace but I'm not sure how the webhook server needs to be setup in that scenario

Any help would be appreciated
Thanks!

**Comment by FearlessHyena** [comment]
I was able to get this working a little while back so closing

**Comment by FearlessHyena** [comment]
Sorry for the delay @toast-gear 

In addition to my original post I basically had to create a separate path for each Org

```yaml
githubWebhookServer:
  enabled: true
  imagePullSecrets: []
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/acme-challenge-type = "http01"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: mydomain.com
          paths:
          - path: /my-org-1 # use a separate path for each Org
```

Also since I wanted to use the same GitHub App for all the Orgs and I disabled the Webhook in the GitHub App and instead added a separate webhook manually in each Org matching the same path above
After that it seemed to work properly

Hopefully once #906 is released (or it already is?) it should be much cleaner to use Enterprise level runners instead (I'd be happy to test that out on GHES 3.3)
