### ISSUE TITLE
How to terminate a runner/job  after 5 min , irrespective of the  job status 

### ISSUE THREAD

**Issue by roshvin** [actions-runner-controller/actions-runner-controller#941]
**Describe the bug**

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

**Expected behavior**
How to terminate a runner/job  after 5 min , irrespective of the  job status 
we are giving free short living runners for users , so we need to restrict the run only for 5 min and irrespective of job status , we need to terminate the runner /job 

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.18.2]
 - Deployment Method [e.g. Helm and Kustomize ]
 - Helm Chart Version [e.g. 0.11.0, if applicable]

**Additional context**

**Comment by roshvin** [comment]
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
   name: ent-runner-auto-scaller
spec:
  scaleDownDelaySecondsAfterScaleOut: 60
  scaleTargetRef:
    name: dot-runner
  minReplicas: 0
  maxReplicas: 30
  scaleUpTriggers:
  - githubEvent: {}
    duration: "3m"
```

**Comment by mumoshu** [comment]
@roshvin Which runner image do you use actually? `xxxxxxxxxxx/actions-runner:v0.20.3` seems to contain the controller version. It should include a runner version.

Also, 

> How to terminate a runner/job after 5 min , irrespective of the job status

This is uncontrollable from the controller-side. You should set up a CI pipeline that verifies your workflow to have a correct timeout settings in it.

**Comment by roshvin** [comment]
@mumoshu  i am using latest runner version summerwind/actions-runner:latest . did the tag locally to match with controller version.
but i am using summerwind/actions-runner:latest only

i was under the assumption that below setting will terminate the runner after 5 min. 

scaleDownDelaySecondsAfterScaleOut: 300

**Comment by mumoshu** [comment]
> did the tag locally to match with controller version.

What do you mean by this? You can browse https://hub.docker.com/r/summerwind/actions-runner-controller and https://hub.docker.com/r/summerwind/actions-runner to find latest tags for each.

It's okay if `image: xxxxxxxxxxx/actions-runner:v0.20.3` in your first example was a mistake. I just wanted to be extra sure you can't mixing thins up!

> i was under the assumption that below setting will terminate the runner after 5 min.
> scaleDownDelaySecondsAfterScaleOut: 300

That's the minimum delay takes in place when you tried to scale down after a scale up. That's different from "terminate this runner once it completes the job".

actions-runner-controller has no way to know if a runner has successfully started or completed a job. So by design it's impossible!

**Comment by roshvin** [comment]
@mumoshu thanks for the update. 
then everything is working as expected . But when i try to include below option in runnerdeployment. the runners are not getting connected . getting the attached error. 

```
 env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
```

![image](https://user-images.githubusercontent.com/11057966/141427679-5ef8a0bd-71cb-40b5-9c90-675d0d7d654a.png)

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dot-runner
spec:
  replicas: 0
  template:
    spec:
      enterprise: testent
      labels:
      - dot-enterprise-runner
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      image: xxxxxxxxxxx/actions-runner:latest
      env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
      dockerEnabled: false
      securityContext:
        runAsUser: 1000

```
