### ISSUE TITLE
Document Docker Caching Limitations

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#944]
We regularly get people trying to share their `/var/lib/docker` between runners which is an extreme no no. `dockerd` is designed to have exclusive access to `/var/lib/docker`.

We need to add to the docs the fact that you can't achieve layer caching between pods this way to reduce the amount of issues we need to respond to with the same comments.

https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache this is the only native means for caching layers between runners, if someone has a more custom solution a entry in the `discussions` tab would be great.

**Comment by erichorwath** [comment]
For me, a cluster internal Docker registry works great as buildx cache:
https://github.com/actions-runner-controller/actions-runner-controller/discussions/717#discussioncomment-1560238

**Comment by peimanja** [comment]
another approach would be using the local cache by providing a shared volume for runners. Like using an EFS (if you are on AWS) that could be mounted in a path on all runners.

**Comment by antodoms** [comment]
@peimanja have you tried shared volume cache via EFS? if so do you have an example you would like to share?

**Comment by peimanja** [comment]
@antodoms so let's say you have a `PersistentVolumeClaim` like:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runners-shared-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi
```

then in your runner spec you can add something like:

```yaml
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: runners-shared-volume-claim
      volumeMounts:
        - name: shared-volume
          mountPath: /opt/shared
```
Then you can use https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#local-cache
