### ISSUE TITLE
How to configure auto scale runners based on the number of checks

### ISSUE THREAD

**Issue by nic-chen** [actions-runner-controller/actions-runner-controller#958]
Hi, Community

The number of checks in different repositories is different. 

Some repositories have only a few checks, but some repositories have more than 20 checks. 

So I hope that every time I create a PR,  the controller can automatically scale runners by the number of checks. 

How should I configure it? 

Thanks!

**Comment by nic-chen** [comment]
My configuration:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
   name: example-runners
spec:
  template:
    spec:
      repository: org/repo
      image: summerwind/actions-runner:latest
      imagePullPolicy: IfNotPresent
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: example-runners
  minReplicas: 1
  maxReplicas: 15
  scaleUpTriggers:
  - githubEvent: {}
    duration: "1m"
```

It seems that only one runner can be created for each PR.
