### ISSUE TITLE
How to configure Webhook driven autoscaling via Loadbalancer

### ISSUE THREAD

**Issue by Jawayria** [actions-runner-controller/actions-runner-controller#989]
I am trying to configure the Webhook driven autoscaling policy. Here is my values.yml file
```
syncPeriod: 2m
githubWebhookServer:
  enabled: true
  syncPeriod: 2m
  service:
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: http
        protocol: TCP
        name: http
```

I have added a Webhook in my GitHub repo and the Payload URL is in the format `http://<dns-for-load-balancer>:<nodeport>`. But events never reach The GitHub Webhook server load balancer. On my GitHub repo I get this error in Webhook section 
`We couldn’t deliver this payload: failed to connect to host`

Can you please figure out any mistake I am making here? Do I need to set up another load balancer or ingress etc.?
