### ISSUE TITLE
failed to create containerd container: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount956276389: no users found

### ISSUE THREAD

**Issue by bartcode** [actions-runner-controller/actions-runner-controller#998]
**Describe the bug**

I've set up a `RunnerDeployment` using a custom image. When I deploy this, it seems to work at first. But as soon as a second runner is created, it fails with an error:

```
failed to create containerd container: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount956276389: no users found
```

My configuration is as follows:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner
spec:
  template:
    spec:
      repository: my-repo
      dockerEnabled: false
      image: my-custom-image:0.0.1
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-autoscaler
spec:
  scaleTargetRef:
    name: runner
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'    # The percentage of busy runners at which the number of desired runners are re-evaluated to scale up
      scaleDownThreshold: '0.3'   # The percentage of busy runners at which the number of desired runners are re-evaluated to scale down
      scaleUpFactor: '1.4'        # The scale up multiplier factor applied to desired count
      scaleDownFactor: '0.7'      # The scale down multiplier factor applied to desired count
```

The custom image is based on `ubuntu:focal` and installs a few commonly used libraries. The last few lines are as follows:
```
USER runner:runner

ENTRYPOINT ["dumb-init"]

CMD ["sh", "/usr/local/bin/start.sh"]  # Start GitHub Runner
```

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature -> **yes**
- [x] I'm using an unreleased version of the controller I built from HEAD of the default branch -> **no**

I've deployed Helm chart version 0.15.0 to the cluster.

**To Reproduce**
1. Deploy the configuration above.
2. Make sure a second runner is set up.
3. See that only the first runner is successfully created.

**Expected behavior**
The second runner should be up and running and not show `CreateContainerError`.

**Screenshots**

![image](https://user-images.githubusercontent.com/24415187/145440784-fed97860-019c-45d3-bcb4-dbaa7bec2a4f.png)

**Environment (please complete the following information):**
 - Controller Version 0.20.3
 - Deployment Method: Helm
 - Helm Chart Version: 0.15.0
